Task5
KFalcon2022/intensive-tasks-2024 pull request #104
Opened 2024-11-18 13:03 UTC by ardmtr

дополнительную потом, хотелось бы узнать правильно ли пока еду. Или всё переделывать )

2024-11-18 21:00 UTC, EvgeneZhurov requested changes

2024-11-18 21:00 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task3/Task3.java
> +
много лишних ненужных пустых строк

2024-11-18 21:00 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task5/Task5.java
> +        double Area = getAreaByHeron(a, b, c);
не по верблюжьей нотации

2024-11-18 21:00 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task5/Task5.java
> +        return ((a * b * c) / (4 * Math.sqrt(halfPerimeter * (halfPerimeter - a) * (halfPerimeter - b) * (halfPerimeter - c))));
Вы писали метод поиска площади. Пользуйтесь им.

2024-11-19 07:11 UTC, ardmtr commented on src/main/java/com/walking/intensive/chapter1/task3/Task3.java
> +
не понял немного, как в коммит залезла task3 вообще.

2024-11-19 07:36 UTC, EvgeneZhurov approved these changes

2024-11-19 07:37 UTC, closed without merging