Task2
KFalcon2022/intensive-tasks-2024 pull request #109
Opened 2024-11-18 14:27 UTC by i5t4b3r

2024-11-18 21:33 UTC, KateKhodko requested changes
На следующую заадчу открыть мр с одним файлом в изменениях, где будет только эта задача

2024-11-18 21:33 UTC, KateKhodko commented on src/main/java/com/walking/intensive/chapter1/task2/Task2.java
> +        switch (flatNumber % FLATS_ON_THE_FLOR) {
По правилам оформления в switch case должен входить default

2024-11-18 21:33 UTC, KateKhodko commented on src/main/java/com/walking/intensive/chapter1/task2/Task2.java
> +        int currentFloor = (int) Math.ceil((double) (flatNumber - (flatsInEntrance * (currentEntrance - 1))) / FLATS_ON_THE_FLOR);
По правилам оформления строка не должна превышать 120 символов в длину

2024-11-18 21:33 UTC, KateKhodko commented on src/main/java/com/walking/intensive/chapter1/task2/Task2.java
> +        int quantityAllFlats = floorAmount * entranceAmount * FLATS_ON_THE_FLOR;
Тут опечатка, FLOOR

2024-11-18 21:33 UTC, KateKhodko commented on src/main/java/com/walking/intensive/chapter1/task2/Task2.java
> +        System.out.println("Enter floor amount:");
Тут английский, ниже по коду русский, лучше все на одном языке сделать

2024-11-19 06:32 UTC, i5t4b3r commented
Исправил замечания, прошу проверить

2024-11-19 09:39 UTC, closed without merging

2024-11-20 12:42 UTC, i5t4b3r commented
Прошу изменить оценку в таблице, спасибо!