Task1
KFalcon2022/intensive-tasks-2024 pull request #117
Opened 2024-11-18 15:46 UTC by LVictor-SF

2024-11-18 20:09 UTC, ekolokolov requested changes
Некорректное исполнение на значениях: 5, 6, 7, 8, 9, 111, 112, 113,114

2024-11-18 20:09 UTC, ekolokolov commented on src/main/java/com/walking/intensive/chapter1/task1/Task1.java
> +            output = "Вам " + age + " год";
отдельная переменная не нужна можно сразу писать 
`return "Вам " + age + " год";`

2024-11-19 09:08 UTC, ekolokolov requested changes
Осталось поправить на отрицательные значения. Я запустил на -10 и получил "Вам -10 лет"

2024-11-19 12:03 UTC, LVictor-SF commented
Так, хорошо, добавил в начало тест на отрицательные значения, судя по всему 0 лет - тоже возраст. А  как тогда лучше выйти из if? если оставить некорректный ввод то он выглядит излишним, так как никогда не будет использован. Конструкция без else возможна, но после if всё равно нужно указать дефолтный возврат, указать пустую строку? Это законно в рамках данной задачи?

2024-11-19 18:41 UTC, ekolokolov approved these changes
Зачтено

2024-11-19 18:41 UTC, closed without merging