Task3
KFalcon2022/intensive-tasks-2024 pull request #118
Opened 2024-11-18 15:47 UTC by kozinaksa

2024-11-18 21:40 UTC, EvgeneZhurov requested changes

2024-11-18 21:40 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task3/Task3.java
> +        return (year % 400 == 0 || (year % 400 % 100 != 0 && year % 400 % 4 == 0)) ? true : false;
если логическое условие true, то вернет true. Дам подсказку, можно возвращать просто логическое условие без тернарного оператора :)

2024-11-18 22:24 UTC, EvgeneZhurov requested changes

2024-11-18 22:24 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task3/Task3.java
> +        return year % 400 == 0 || (year % 400 % 100 != 0 && year % 400 % 4 == 0);
year % 400 % 100 - то есть Вы берете число и потом берете остаток от деления на 400, а потом из него берете остаток от деления на 100. Будет ли разница, если сразу взять остаток от деления на 100 без 400?

2024-11-18 22:59 UTC, kozinaksa commented on src/main/java/com/walking/intensive/chapter1/task3/Task3.java
> +        return year % 400 == 0 || (year % 400 % 100 != 0 && year % 400 % 4 == 0);
Не будет, т.к. 400 делится на 100 без остатка )

2024-11-19 07:52 UTC, EvgeneZhurov requested changes

2024-11-19 07:52 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task3/Task3.java
> +        return year % 400 == 0 || (year % 100 != 0 && year % 400 % 4 == 0);
year % 400 % 4 == 0 не исправлено

2024-11-19 15:02 UTC, EvgeneZhurov requested changes

2024-11-19 17:09 UTC, closed without merging