Task3
KFalcon2022/intensive-tasks-2024 pull request #127
Opened 2024-11-18 17:06 UTC by MrTokim

2024-11-18 22:03 UTC, EvgeneZhurov requested changes

2024-11-18 22:03 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task3/Task3.java
> +        if (year <= 0) {
Если поменять логическое условие на противоположное, можно вставить его в другой if, тогда код будет читаться легче. без лишних ветвлений.

2024-11-18 22:03 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task3/Task3.java
> +        if (year % 4 == 0 && year % 100 != 0 | year % 400 == 0) {
можно возвращать логическое условие из if, тогда ветвление не понадобится.

2024-11-18 22:03 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task3/Task3.java
> +        if (year % 4 == 0 && year % 100 != 0 | year % 400 == 0) {
Лучше знать разницу меду || и |

2024-11-19 16:09 UTC, EvgeneZhurov requested changes

2024-11-19 16:09 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task3/Task3.java
> +        return (year >= 0 && year % 4 == 0 && (year % 100 != 0 || year % 400 == 0));
лучше убрать лишние скобки

2024-11-19 16:19 UTC, MrTokim commented on src/main/java/com/walking/intensive/chapter1/task3/Task3.java
> +        return (year >= 0 && year % 4 == 0 && (year % 100 != 0 || year % 400 == 0));
Если их убрать то при вводе отрицательного значение кратного 400 будет "true".

2024-11-19 16:20 UTC, MrTokim commented on src/main/java/com/walking/intensive/chapter1/task3/Task3.java
> +        return (year >= 0 && year % 4 == 0 && (year % 100 != 0 || year % 400 == 0));
Сейчас подумал, можно просто их поменять местами и тогда скобки не нужны:)

2024-11-19 16:28 UTC, EvgeneZhurov requested changes

2024-11-19 16:28 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task3/Task3.java
> +        return ( year % 100 != 0 || year % 400 == 0 && year >= 0 && year % 4 == 0);
лучше убрать лишние скобки

2024-11-19 17:10 UTC, EvgeneZhurov approved these changes

2024-11-19 17:11 UTC, closed without merging