Task 4
KFalcon2022/intensive-tasks-2024 pull request #130
Opened 2024-11-18 17:54 UTC by 0rloff

2024-11-18 22:06 UTC, EvgeneZhurov requested changes

2024-11-18 22:06 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task4/Task4.java
> +            } else if (b == 0 || c == 0) {
после return не пишут else, либо будет return из метода, либо и без else код продолжит исполняться.

2024-11-18 22:06 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task4/Task4.java
> +            if (b == c && c == 0) {
лучше не делать вложенных ветвлений без необходимости.

2024-11-19 08:56 UTC, 0rloff commented on src/main/java/com/walking/intensive/chapter1/task4/Task4.java
> +            } else if (b == 0 || c == 0) {
fixed

2024-11-19 08:56 UTC, 0rloff commented on src/main/java/com/walking/intensive/chapter1/task4/Task4.java
> +            if (b == c && c == 0) {
fixed

2024-11-19 09:29 UTC, EvgeneZhurov requested changes
double a = 1;
        double b = 0;
        double c = -1

 не проходит тест

2024-11-19 10:12 UTC, 0rloff commented
> ```
>     double a = 1;
>     double b = 0;
>     double c = -1
> ```
> 
> не проходит тест

Спасибо, поправил

2024-11-19 10:34 UTC, EvgeneZhurov requested changes

2024-11-19 10:34 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task4/Task4.java
> +            if (powX < 0) {
Просьба объяснить, что изменится. если выбросить код с 52 по 69 строку?

2024-11-19 10:34 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task4/Task4.java
> +            double powX = -c / a;
Лучше стараться избегать вложенных ветвлений, когда они не нужны, это ухудшает читаемость кода, а так же не вуалировать скрытые значения.  if (b == 0) { if (c == b) . За переменной скрывается 0, лучше так и написать. Нужно стремиться к демонстративности при чтении кода.

2024-11-19 11:32 UTC, 0rloff commented on src/main/java/com/walking/intensive/chapter1/task4/Task4.java
> +            if (powX < 0) {
Ничего не изменится, потому что неполные квадратные уравнения можно решить так же, как и полные)
Спасибо, исправил

2024-11-19 11:39 UTC, 0rloff commented on src/main/java/com/walking/intensive/chapter1/task4/Task4.java
> +            double powX = -c / a;
Спасибо, исправил

2024-11-19 15:44 UTC, closed without merging