Task4
KFalcon2022/intensive-tasks-2024 pull request #131
Opened 2024-11-18 18:07 UTC by kozinaksa

2024-11-18 22:08 UTC, EvgeneZhurov requested changes

2024-11-18 22:08 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task4/Task4.java
> +        } else if (a == 0 && b == 0) {
после return не ставится else. Либо будет выход из метода, либо он продолжит исполняться и без else.

2024-11-18 22:08 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task4/Task4.java
> +        double d = Math.pow(b, 2) - 4 * a * c;
Лучше стараться давать переменным максимально релевантные имена

2024-11-18 22:08 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task4/Task4.java
> +        double x1 = (-b + Math.pow(d, 0.5)) / 2 * a;
лучше Math.sqrt

2024-11-18 22:41 UTC, kozinaksa commented on src/main/java/com/walking/intensive/chapter1/task4/Task4.java
> +        double d = Math.pow(b, 2) - 4 * a * c;
А назвать переменную "D" можно (самое релевантное имя) или нельзя (т.к. не класс называем)?

2024-11-19 07:43 UTC, EvgeneZhurov approved these changes
Принято. Хорошо.

2024-11-19 07:43 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task4/Task4.java
> +        if (a == 0) {
лучше отделять блоки кода (например if) пустыми строками с обеих сторон, если это не начало или конец метода

2024-11-19 07:47 UTC, closed without merging