task4
KFalcon2022/intensive-tasks-2024 pull request #134
Opened 2024-11-18 18:43 UTC by Rewertkin

2024-11-18 22:21 UTC, EvgeneZhurov requested changes

2024-11-18 22:21 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task4/Task4.java
> +        } else if (a == 0 & b == 0 & c == 0) {
после return не пишут else. Либо будет return, либо метод и так продолжит исполняться без else. Просьба поправить везде в коде.

2024-11-18 22:21 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task4/Task4.java
> +            if (d == 0) {
лучше обойтись без вложенных ветвлений, используйте || или  &&

2024-11-18 22:21 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task4/Task4.java
> +            double d = Math.pow(b, 2) - (4 * a * c);
старайтесь давать максимально релевантные имена.

2024-11-19 18:59 UTC, EvgeneZhurov requested changes

2024-11-19 18:59 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task4/Task4.java
> +        if (a != 0 & discriminant > 0) {
if (a == 0 & b == 0 & c == 0) {
            return "Бесконечное множество решений";
        } 
Если поставить это условие выше, то в условии 
        if (a == 0 & b == 0 & c != 0) {
            return "Некорректные входные данные";
        }
можно убрать лишнее логическое условие.

2024-11-19 18:59 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task4/Task4.java
> +        if (a != 0 & discriminant > 0) {
лучше сделать отдельно условие a == 0. тогда остальной код будет читаться легче и не придется a != 0

2024-11-19 18:59 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task4/Task4.java
> +        if (a == 0 & ( c == 0 || b == 0)) {
между && и & есть разница, лучше знать какая.

2024-11-19 18:59 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task4/Task4.java
> +        if (a == 0 & ( c == 0 || b == 0)) {
если "a" == 0 и "b" != 0 линейное уравнение не должно содержать логического условия с параметром 2с"

2024-11-21 17:15 UTC, Rewertkin commented on src/main/java/com/walking/intensive/chapter1/task4/Task4.java
>              return "Некорректные входные данные";
Получается полностью убираем return "Некорректные входные данные"; и такие случаи тоже выводим в return "Количество решений: 0." ?
Опирался на тестовые данные, там собственно для случаев, где a == b == 0 указывается сообщение некорректные данные.

2024-11-21 20:43 UTC, EvgeneZhurov requested changes

2024-11-21 20:43 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task4/Task4.java
> +            return "Некорректные входные данные";//выставлено на примере тестовых данных
решения должны идти в порядке возрастания

2024-11-22 12:57 UTC, Rewertkin commented on src/main/java/com/walking/intensive/chapter1/task4/Task4.java
> +            return "Некорректные входные данные";//выставлено на примере тестовых данных
корни сейчас идут в порядке возрастания (на прошлом ревью был убран массив), сейчас сортировка происходит по следующему коду(стр 65-68):
if (x2 > x1) {
                double temp = x1;
                x1 = x2;
                x2 = temp;
            }
            return String.format("Количество решений: 2. Корни: %.0f;%.0f", x1, x2);

2024-11-22 20:00 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task4/Task4.java
> +            return "Некорректные входные данные";//выставлено на примере тестовых данных
double a = -1;
        double b = 3;
        double c = 4;
введите и посмотрите на ответ.

2024-11-22 20:13 UTC, Rewertkin commented on src/main/java/com/walking/intensive/chapter1/task4/Task4.java
> +            return "Некорректные входные данные";//выставлено на примере тестовых данных
исправил

2024-11-22 20:17 UTC, EvgeneZhurov approved these changes

2024-11-22 20:17 UTC, closed without merging