ver 1.0
KFalcon2022/intensive-tasks-2024 pull request #142
Opened 2024-11-18 21:39 UTC by LVictor-SF

2024-11-18 23:44 UTC, Zawadskiy requested changes

2024-11-18 23:44 UTC, Zawadskiy commented on src/main/java/com/walking/intensive/chapter1/task2/Task2.java
> +        flatLocation = flatNumber + " кв - " + entranceNumber + " подъезд, " + floorNumber + " этаж, " + locationOnFloor;
Error: eckstyle] [ERROR] /home/runner/work/intensive-tasks-2024/intensive-tasks-2024/src/main/java/com/walking/intensive/chapter1/task2/Task2.java:93: Line is longer than 120 characters (found 121). [LineLength]

2024-11-18 23:44 UTC, Zawadskiy commented on src/main/java/com/walking/intensive/chapter1/task2/Task2.java
> +        } else if (flatNumber > flatAmountOnFloor * floorAmount * entranceAmount) {
Если есть return в блоке if, тогда else не пишем.

2024-11-18 23:44 UTC, Zawadskiy commented on src/main/java/com/walking/intensive/chapter1/task2/Task2.java
> +        switch (flatNumberOnFloor) {
Есть вот такой удобніій switch
locationOnFloor = switch (что-то там) {
                case 0 -> "справа от лифта, вправо";
                case 1 -> "слева от лифта, влево";
                case 2 -> "слева от лифта, вправо";
                case 3 -> "справа от лифта, влево";
                default -> locationOnFloor;
            };

2024-11-18 23:44 UTC, Zawadskiy commented on src/main/java/com/walking/intensive/chapter1/task2/Task2.java
> +        if (flatNumber % flatAmountInEntrance != 0) {
entranceNumber и  floorNumber можно віічислить и проще) Сделаешь - молодец, нет - тоже ок.

2024-11-19 07:02 UTC, LVictor-SF commented on src/main/java/com/walking/intensive/chapter1/task2/Task2.java
>      static String getFlatLocation(int floorAmount, int entranceAmount, int flatNumber) {
Что такое pr?

2024-11-19 07:06 UTC, LVictor-SF commented on src/main/java/com/walking/intensive/chapter1/task2/Task2.java
> +        } else if (flatNumber > flatAmountOnFloor * floorAmount * entranceAmount) {
О_О оформить через switch? Добавить лишнюю переменную? Разделить на 2 отдельных if? Другой вариант?

2024-11-19 07:31 UTC, Zawadskiy commented on src/main/java/com/walking/intensive/chapter1/task2/Task2.java
> +        } else if (flatNumber > flatAmountOnFloor * floorAmount * entranceAmount) {
if() {
return;
}
if(){
}

2024-11-19 15:23 UTC, Zawadskiy approved these changes

2024-11-19 15:23 UTC, closed without merging