Task2
KFalcon2022/intensive-tasks-2024 pull request #143
Opened 2024-11-18 23:15 UTC by kps-d

2024-11-18 23:36 UTC, Zawadskiy requested changes

2024-11-18 23:36 UTC, Zawadskiy commented on src/main/java/com/walking/intensive/chapter1/task2/Task2.java
> +            if((endFlat % 4) == 0) {
Error: eckstyle] [ERROR] /home/runner/work/intensive-tasks-2024/intensive-tasks-2024/src/main/java/com/walking/intensive/chapter1/task2/Task2.java:73:13: 'if' is not followed by whitespace. [WhitespaceAround]

И зачем тебе лишние () ?

2024-11-18 23:36 UTC, Zawadskiy commented on src/main/java/com/walking/intensive/chapter1/task2/Task2.java
> +        if ((floorAmount * 4 * entranceAmount) < flatNumber) {
Хотелось біі знать что за магическое число такое 4. Касается всех мест где оно используется.

2024-11-18 23:36 UTC, Zawadskiy commented on src/main/java/com/walking/intensive/chapter1/task2/Task2.java
> +        if (maxNumFlatOnFloor == flatNumber) {
Не уверен проходили ли, но можно if заменить на switch.

2024-11-18 23:36 UTC, Zawadskiy commented on src/main/java/com/walking/intensive/chapter1/task2/Task2.java
> +        int numFloor; //номер этажа
numEntrance и numFloor можно віічислить проще и почему не entranceNum/floorNum?

2024-11-19 22:02 UTC, kps-d commented on src/main/java/com/walking/intensive/chapter1/task2/Task2.java
> +        if ((floorAmount * 4 * entranceAmount) < flatNumber) {
Ввел переменную

2024-11-19 22:04 UTC, kps-d commented on src/main/java/com/walking/intensive/chapter1/task2/Task2.java
> +        if (maxNumFlatOnFloor == flatNumber) {
Заменил на switch

2024-11-19 22:04 UTC, kps-d commented on src/main/java/com/walking/intensive/chapter1/task2/Task2.java
> +        int numFloor; //номер этажа
Переменные поменял. Метод проще пока не могу найти(

2024-11-19 22:13 UTC, Zawadskiy commented on src/main/java/com/walking/intensive/chapter1/task2/Task2.java
> +        int numFloor; //номер этажа
И так сойдет. Но для себя можешь подумать.

2024-11-19 22:13 UTC, Zawadskiy approved these changes

2024-11-19 22:13 UTC, closed without merging