Task 2
KFalcon2022/intensive-tasks-2024 pull request #150
Opened 2024-11-19 05:21 UTC by gentrus

gentrus

2024-11-19 05:29 UTC, Zawadskiy requested changes

2024-11-19 05:29 UTC, Zawadskiy commented on src/main/java/com/walking/intensive/chapter1/task2/Task2.java
>      static String getFlatLocation(int floorAmount, int entranceAmount, int flatNumber) {
9 tests completed, 1 failed
Task2Test > getFlatLocationTest(String, int, int, int) > [1] 40 кв - 1 подъезд, 10 этаж, справа от лифта, вправо, 10, 3, 40 FAILED
    org.opentest4j.AssertionFailedError at Task2Test.java:
    Тест помер. Исправь или докажи что тест не верніій.

2024-11-19 05:29 UTC, Zawadskiy commented on src/main/java/com/walking/intensive/chapter1/task2/Task2.java
> +        switch (direction) {
Можно написать return switch() ...

2024-11-19 05:29 UTC, Zawadskiy commented on src/main/java/com/walking/intensive/chapter1/task2/Task2.java
> +
Дефолтное значение где?

2024-11-19 05:29 UTC, Zawadskiy commented on src/main/java/com/walking/intensive/chapter1/task2/Task2.java
> +        return "";
Очень плохо вііглядит.

2024-11-19 05:29 UTC, Zawadskiy commented on src/main/java/com/walking/intensive/chapter1/task2/Task2.java
> +        String direction1 = "слева от лифта, ";
Ну вот вііносить єто в отдельнііе переменнііе чтобіі потом конкатенцию сделать такое себе решение.

2024-11-19 05:52 UTC, gentrus commented on src/main/java/com/walking/intensive/chapter1/task2/Task2.java
> +
дефолтное значение вместо "case 4" сделать?

2024-11-19 06:04 UTC, Zawadskiy commented on src/main/java/com/walking/intensive/chapter1/task2/Task2.java
> +
ага

2024-11-21 15:02 UTC, gentrus commented on src/main/java/com/walking/intensive/chapter1/task2/Task2.java
> +        String direction1 = "слева от лифта, ";
Исправил)

2024-11-21 15:58 UTC, gentrus commented
Исправил)

2024-11-22 00:32 UTC, Zawadskiy requested changes

2024-11-22 00:32 UTC, Zawadskiy commented on src/main/java/com/walking/intensive/chapter1/task2/Task2.java
> +        return switch (direction) {
Длина строки в 120 символов =)

Error: eckstyle] [ERROR] /home/runner/work/intensive-tasks-2024/intensive-tasks-2024/src/main/java/com/walking/intensive/chapter1/task2/Task2.java:74: Line is longer than 120 characters (found 131). [LineLength]
Error: eckstyle] [ERROR] /home/runner/work/intensive-tasks-2024/intensive-tasks-2024/src/main/java/com/walking/intensive/chapter1/task2/Task2.java:76: Line is longer than 120 characters (found 132). [LineLength]
> Task :checkstyleMain
Error: eckstyle] [ERROR] /home/runner/work/intensive-tasks-2024/intensive-tasks-2024/src/main/java/com/walking/intensive/chapter1/task2/Task2.java:78: Line is longer than 120 characters (found 132). [LineLength]
Error: eckstyle] [ERROR] /home/runner/work/intensive-tasks-2024/intensive-tasks-2024/src/main/java/com/walking/intensive/chapter1/task2/Task2.java:80: Line is longer than 120 characters (found 133). [LineLength]

2024-11-22 04:33 UTC, gentrus commented on src/main/java/com/walking/intensive/chapter1/task2/Task2.java
> +        return switch (direction) {
Исправил

2024-11-22 08:34 UTC, Zawadskiy requested changes

2024-11-22 08:34 UTC, Zawadskiy commented on src/main/java/com/walking/intensive/chapter1/task2/Task2.java
> +            default ->
Пропустил видимо, но дефолтное значение оставляют для ошибки, итого 1-4.

2024-11-23 00:38 UTC, Zawadskiy approved these changes

2024-11-23 00:38 UTC, closed without merging