Task1
KFalcon2022/intensive-tasks-2024 pull request #151
Opened 2024-11-19 07:06 UTC by rtsnik

Решение Task1.

2024-11-19 08:05 UTC, EvgeneZhurov requested changes

2024-11-19 08:05 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task1/Task1.java
> +                remainder = age - age/100*100; //отсекаем 100-ые порядки
Просьба перечитать правила оформления кода. Код требуется выравнивать перед отправкой на проверку.

2024-11-19 08:05 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task1/Task1.java
> +                        result = "Вам " + age + " лет";
в местном комьюнити принято выделать условия ветвления {}? даже если речь идет об одной строке. Просьба поправить везде, где это требуется.

2024-11-19 08:05 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task1/Task1.java
> +                        result = "Вам " + age + " лет";
Разные ветвления дают один и тот же результат "лет". Лучше составить логические условия так, чтобы одно ветвление давало одно слово.

2024-11-19 08:05 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task1/Task1.java
> +                    if(remainder == 1) {
много вложенных ненужных ветвлений. Лучше избегать без крайней необходимости, как в данной задаче.

2024-11-19 08:57 UTC, rtsnik commented
От переменной String ageString отказываться не стал. С ней есть ощущение завершенности метода.

2024-11-24 16:28 UTC, EvgeneZhurov requested changes

2024-11-24 16:28 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task1/Task1.java
> +            ageString = "Вам " + age + " год";
просьба сделать return

2024-11-24 16:28 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task1/Task1.java
> +            ageString = "Вам " + age + " года";
просьба сделать return

2024-11-24 16:28 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task1/Task1.java
> +            ageString = "Вам " + age + " лет";
просьба сделать return

2024-11-24 16:28 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task1/Task1.java
> +            ageString = "Вам " + age + " лет";
У Вас слово "лет" имеет два return. Попробуйте написать логические условия так, чтобы на каждое слово был ровно один return

2024-11-24 20:58 UTC, rtsnik commented on src/main/java/com/walking/intensive/chapter1/task1/Task1.java
> +            ageString = "Вам " + age + " лет";
Так понял, что надо стремиться к тому, чтобы на каждый "вид" return вызывался только один раз.

2024-11-24 21:03 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task1/Task1.java
> +            ageString = "Вам " + age + " лет";
да, нужно правильно подобрать логические условия.

2024-11-25 07:22 UTC, EvgeneZhurov requested changes

2024-11-25 07:22 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task1/Task1.java
>          } else {
после return не ставят else

2024-11-26 06:44 UTC, rtsnik commented on src/main/java/com/walking/intensive/chapter1/task1/Task1.java
>          } else {
Убрал

2024-11-26 18:55 UTC, EvgeneZhurov approved these changes

2024-11-26 18:55 UTC, closed without merging