gentrus
KFalcon2022/intensive-tasks-2024 pull request #159
Opened 2024-11-19 09:59 UTC by gentrus

Task4

2024-11-19 10:39 UTC, EvgeneZhurov commented
gentrus - просьба поправить название задачи на Task4

2024-11-19 10:51 UTC, EvgeneZhurov requested changes

2024-11-19 10:51 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task4/Task4.java
> +            return "Бесконечное множество решений";
Просьба перечитать правила оформления кода. Код нужно выравнивать

2024-11-19 10:51 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task4/Task4.java
> +        }
Если a == 0 && b == 0 && c != 0 "Решений нет"
Если a == 0 && b != 0  единственное решение: какое?

2024-11-19 12:41 UTC, gentrus commented on src/main/java/com/walking/intensive/chapter1/task4/Task4.java
> +        }
Если a == 0 && b != 0, то решение:  -c / b? Или я чего то недопонял.
Помню в школе учили только 3 исхода))

2024-11-19 15:10 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task4/Task4.java
> +        }
Это от школы зависит. "то решение: -c / b?" - да.

2024-11-19 16:03 UTC, gentrus commented on src/main/java/com/walking/intensive/chapter1/task4/Task4.java
> +        }
теперь понял, что не дописал решения неполных крадратных уравнений. И как я понял в тесте вывод корней не по возрастанию а по убыванию?

2024-11-19 16:39 UTC, EvgeneZhurov requested changes

2024-11-19 16:39 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task4/Task4.java
>              } else {
после return не пишут else. Либо будет выход из метода, либо и без else метод продолжит исполняться.

2024-11-20 05:51 UTC, gentrus commented on src/main/java/com/walking/intensive/chapter1/task4/Task4.java
>              return "Количество решений: 1. Корень: " + (int) (-c / b);
А как мне вывести double в консоль без точки с десятой частью (1.0)? Тест ругается
![изображение_2024-11-20_085122950](https://github.com/user-attachments/assets/14e6f97e-4b8b-493a-a94e-d9398bdeec7a)

2024-11-20 19:25 UTC, EvgeneZhurov requested changes

2024-11-20 19:25 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task4/Task4.java
> +        if (b==0&&c==0) {
код перед отправкой необходимо выравнивать. Просьба повторить правила оформления кода.

2024-11-20 19:25 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task4/Task4.java
> +            return "Некорректные входные данные";
неверно, данные корректны. Верный ответ : решений нет

2024-11-20 19:25 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task4/Task4.java
> +        if (b==0&&c==0) {
этот блок можно просто удалить

2024-11-20 19:25 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task4/Task4.java
> +        }
просьба выполнить эти логические условия

2024-11-21 04:52 UTC, gentrus commented on src/main/java/com/walking/intensive/chapter1/task4/Task4.java
> +            return "Некорректные входные данные";
![image](https://github.com/user-attachments/assets/32e4248a-b461-48aa-b4c9-f2e5cf6bf7e4)
это у меня тест не обновленный?

2024-11-21 05:07 UTC, gentrus commented on src/main/java/com/walking/intensive/chapter1/task4/Task4.java
> +        if (b==0&&c==0) {
если я удалю условие a==0, то программа при а==0, b!=0, c!=0 начнет вычислять дискриминант, не?

2024-11-21 19:38 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task4/Task4.java
> +        if (b==0&&c==0) {
Вас не просят удалить условие "a" == 0, Вас просят удалить блок с логическими условиями if (b==0&&c==0), этот блок не имеет отношения к "а".

2024-11-21 20:25 UTC, gentrus commented on src/main/java/com/walking/intensive/chapter1/task4/Task4.java
> +        if (b==0&&c==0) {
дошло) исправил.

2024-11-21 20:40 UTC, EvgeneZhurov requested changes

2024-11-21 20:40 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task4/Task4.java
> +        if (b == 0 && c != 0) {
Как и писал ранее код с 50 по 61 строку можно смело удалять

2024-11-21 20:40 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task4/Task4.java
>              if (((-b + Math.sqrt(discriminant)) / (2 * a)) > ((-b - Math.sqrt(discriminant)) / (2 * a))) {
не заставляйте программу считать одно и то же большое количество раз

2024-11-21 20:40 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task4/Task4.java
>                  return "Количество решений: 2. Корни: " + ((-b + Math.sqrt(discriminant)) / (2 * a)) + ";" + ((-b - Math.sqrt(discriminant)) / (2 * a));
Правильно понял логическое условие? Если m>n, то return в порядке убывания?

2024-11-21 21:38 UTC, gentrus commented on src/main/java/com/walking/intensive/chapter1/task4/Task4.java
>                  return "Количество решений: 2. Корни: " + ((-b + Math.sqrt(discriminant)) / (2 * a)) + ";" + ((-b - Math.sqrt(discriminant)) / (2 * a));
Да так и есть, написано ещё до обновления теста, там ответы были по убыванию.

2024-11-22 08:04 UTC, EvgeneZhurov requested changes

2024-11-22 08:04 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task4/Task4.java
> +                return "Количество решений: 2. Корни: " + sqrt1 + ";" + sqrt2;
По условию задачи корни должны располагаться в порядке возрастания, у Вас наоборот. 
PS чтобы избежать ненужного ветвления можно использовать Math.max и Math.min

2024-11-22 10:28 UTC, EvgeneZhurov approved these changes

2024-11-22 10:29 UTC, closed without merging