Task 1
KFalcon2022/intensive-tasks-2024 pull request #161
Opened 2024-11-19 10:17 UTC by YashaMars

2024-11-19 10:42 UTC, EvgeneZhurov requested changes

2024-11-19 12:25 UTC, YashaMars reviewed
Переделал

2024-11-19 15:04 UTC, EvgeneZhurov requested changes

2024-11-19 15:04 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task1/Task1.java
> +        if (age < 0 || age > 127) { // отсекаем невозможные значения
Два return под слово лет. нужно по одному на каждое слово.

2024-11-24 16:30 UTC, EvgeneZhurov requested changes

2024-11-24 16:30 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task1/Task1.java
>          return switch (lastDigit) {
чем здесь плох switch case - тем, что через него возвращаются не все условия. Либо нужно реализовать метод так, чтобы все ответы шли через него, или нужно от него отказаться.

2024-12-13 08:04 UTC, EvgeneZhurov commented
Просьба открыть новый PR, если требуется проверка

2024-12-13 08:04 UTC, closed without merging