Task5
KFalcon2022/intensive-tasks-2024 pull request #182
Opened 2024-11-19 14:43 UTC by Rewertkin

2024-11-19 18:40 UTC, EvgeneZhurov requested changes

2024-11-19 18:40 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task4/Task4.java
> +        } else if (a == 0 & b == 0 & c == 0) {
после return не пишут else. Либо будет выход из метода, либо и без else метод продолжит выполняться. Поправьте везде и продолжим общение.

2024-11-19 18:40 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task4/Task4.java
> +            if (d == 0) {
в этой задаче не требуется вложенных ветвлений.

2024-11-19 18:40 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task4/Task4.java
> +            double d = Math.pow(b, 2) - (4 * a * c);
лучше стараться давать максимально информативные имена

2024-11-19 18:53 UTC, EvgeneZhurov commented
это 4 задача вроде

2024-11-19 18:54 UTC, Rewertkin commented
Прошу игнорировать файл task4(был загружен по ошибке), в рамках данного RP высылается на проверку task5

2024-11-19 19:15 UTC, EvgeneZhurov approved these changes
Принято, отлично

2024-11-19 19:15 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task5/Task5.java
> +
arrayOfAngles - Лучше стараться не писать предлоги в названиях. В английском языке если развернуть слова местами, то предлог исчезает anglesArray

2024-11-19 20:17 UTC, EvgeneZhurov requested changes
тесты проходятся. Просьба поправить замечания.

2024-11-19 20:17 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task5/Task5.java
> +        }else{
после return не пишут else

2024-11-19 20:17 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task5/Task5.java
> +        arrayOfHeights = new double[3];
лучше стараться избегать предлогов в названиях. Можно поменять местами слова, тогда предлог пропадет heightsArray. Просьба поправить везде в коде

2024-11-19 20:17 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task5/Task5.java
> +        double s = getAreaByHeron(a, b, c);
лучше стараться давать максимально релевантные имена

2024-11-19 20:17 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task5/Task5.java
> +        return getAreaByHeron(a, b, c) / ((a+ b + c) / 2);
код нужно выравнивать. Просьба повторить правила оформления кода

2024-11-19 20:17 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task5/Task5.java
> +        return (a * b * c) / (4 * getAreaByHeron(a, b, c));
скобки лишние. Меньше символов, легче читается

2024-11-19 20:17 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task5/Task5.java
> +    static boolean checkFailSides(double a, double b, double c) {
между & и && есть разница

2024-11-19 20:17 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task5/Task5.java
> +        return !(b + c > a & a + c > b & a + b > c & a > 0 & b > 0 & c > 0);
чтобы избавиться от скобок и отрицания можно поменять логические условия.

2024-11-20 19:49 UTC, EvgeneZhurov requested changes
Просьба написать мне в личку

2024-11-22 19:38 UTC, EvgeneZhurov approved these changes

2024-11-22 19:38 UTC, closed without merging