Task2
KFalcon2022/intensive-tasks-2024 pull request #193
Opened 2024-11-19 18:27 UTC by IVRomash

2024-11-19 20:05 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter1/task1/Task1.java
> +        if (age % 10 == 0 || (age > 10 && age < 15) || age % 10 > 4 || (age > 110 && age < 115)) {
Нет проверки для отрицательного вораста

2024-11-19 20:12 UTC, KFalcon2022 requested changes

2024-11-19 20:12 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter1/task1/Task1.java
> +        }
этого файла в данном ПРе быть не должно

2024-11-19 20:12 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter1/task2/Task2.java
> +        } else if (floorAmount < 1 || entranceAmount < 1 || flatNumber < 1) {
зачем `else if`, если при срабатывании предыдущего условия выполнение метода завершится? программа и так до этой строчки не дойдет. Поэтому достаточно обычного `if`

2024-11-19 20:12 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter1/task2/Task2.java
> +        int floorNumber = 1 + ((flatNumber - 1) % (flatAmount / entranceAmount) / 4);
переменные стоит объявлять и инициировать как можно ближе к месту их использования. Ниже два if'а, в которых эти переменные не нужны:)

2024-11-19 20:12 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter1/task2/Task2.java
> +        } else if (flatNumber % 4 == 1 || flatNumber % 4 == 2) {
Какой смысл в этой конструкции, если внутри ты все равно повторно проверяешь `flatNumber % 4 == 1`?

2024-11-19 20:12 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter1/task2/Task2.java
> +        } else {
Учитывая, что ты и так смотришь все возможные остатки от деления на 4 - есть конструкция, которая сюда подойдет намного лучше, чем if-else

2024-11-19 20:12 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter1/task2/Task2.java
>      }
Как исправишь - маякни в ЛС. https://t.me/ironicMotherfucker

2024-11-20 18:13 UTC, KFalcon2022 requested changes

2024-11-20 18:13 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter1/task2/Task2.java
> +        };
не стесняйся пустые строки использовать при разделении логических блоков кода внутри метода. Иначе все сливается в единый набор символов

2024-11-20 18:13 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter1/task2/Task2.java
> +        return switch (flatNumber % 4) {
кажется более логичным инициализировать переменную результатом этого switch-case. И потом уже со значением переменной собрать итоговую строку. Ибо в текущем подходе сразу две проблемы:
1. Тебе пришлось вынести 4 переменных с результатом switch-case прямо перед ним (подозреваю, чтобы в 120 символов влезть)
2. Любое изменение в требованиях по виду конечной строки заставит изменять код сразу в четырех местах. Логичнее свети такое изменение к одному месту:)

2024-11-20 18:13 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter1/task2/Task2.java
> +            default -> flatNumber + " кв - " + entranceNumber + " подъезд, " + floorNumber + option4;
не стоит использовать default вместо последнего case'а. Задача default в ситуациях, когда на каждый исход есть отдельно определенный case - выступать маркером ошибок.

Условно, завтра кто-то заменит условие `flatNumber % 4` на `flatNumber % 5`. И не изменит тело switch-case. При текущем подходе программа продолжит работать. Некорректно, но никак не извещая о некорректном поведении

2024-11-21 09:02 UTC, IVRomash commented on src/main/java/com/walking/intensive/chapter1/task1/Task1.java
> +        }
Подскажи, пожалуйста, а сейчас как-то можно ненужные файлы убрать из ПРа или уже поздно?

2024-11-21 15:33 UTC, IVRomash commented on src/main/java/com/walking/intensive/chapter1/task2/Task2.java
> +            default -> flatNumber + " кв - " + entranceNumber + " подъезд, " + floorNumber + option4;
Я убрал default и вместо него использовал последний case. Но при компиляции падала ошибка "the switch statement does not cover all possible input values", поэтому добавил default. Понимаю, что скорее всего это некорректно.
подскажи, пожалуйста, можно ли как-то было избавиться от default или нужно было его добавить всё-таки?

2024-11-21 20:07 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter1/task2/Task2.java
> +        };
Исправил ровно там, где это было не надо:)

2024-11-21 20:07 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter1/task2/Task2.java
> +            default -> flatNumber + " кв - " + entranceNumber + " подъезд, " + floorNumber + option4;
Сейчас хорошо сделано. В некоторых ситуациях default можно опустить. Например, при полном переборе элементов Enum'а. Может вспомнишь про это, когда до них дойдешь) Пока же лучше просто оставляй везде

2024-11-21 20:09 UTC, KFalcon2022 approved these changes

2024-11-21 20:09 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter1/task2/Task2.java
> +        int flatAmount = floorAmount * entranceAmount * 4;
эту переменную логичнее вычислять после if'а ниже. Ведь она может банально не понадобиться:)

2024-11-21 20:09 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter1/task2/Task2.java
>  }
Оставшиеся замечания считаю мелкими и оставляю на самостоятельное исправление. Задача зачтена

2024-11-21 20:09 UTC, closed without merging