Task 1
KFalcon2022/intensive-tasks-2024 pull request #202
Opened 2024-11-19 19:36 UTC by Enhusikpro

if else с кучей ИЛИ, подскажите, пожалуйста, как оптимальнее было бы сделать?

2024-11-19 19:48 UTC, ekolokolov requested changes
Давай начнем с правки мелочей и там дойдем до итогового решения.
Как поправишь замечания попробуй запустить например на 111 годах.

2024-11-19 19:48 UTC, ekolokolov commented on src/main/java/com/walking/intensive/chapter1/task1/Task1.java
> +        else if (age > 4 & age < 21) {
фигурная скобка и  else должны быть на одной строке вот так 
} else {

2024-11-19 19:48 UTC, ekolokolov commented on src/main/java/com/walking/intensive/chapter1/task1/Task1.java
> +        else if (ageDiv == 0 | ageDiv == 5 | ageDiv == 6 | ageDiv == 7 | ageDiv == 8 | ageDiv == 9) {
`ageDiv == 5 | ageDiv == 6 | ageDiv == 7 | ageDiv == 8 | ageDiv == 9` можно записать как 
` ageDiv >= 5 && ageDiv <=9`

2024-11-19 19:48 UTC, ekolokolov commented on src/main/java/com/walking/intensive/chapter1/task1/Task1.java
> +            result = "Вам " + age + " лет";
Тут не нужна переменная . можно сразу писать 
`return "Вам " + age + " лет";`

2024-11-24 11:19 UTC, ekolokolov requested changes
На лекции 2 мы разбирали основные ошибки. Можешь посмотреть запись

2024-11-24 11:19 UTC, ekolokolov commented on src/main/java/com/walking/intensive/chapter1/task1/Task1.java
> +        } else if ((age > 4 & age < 21) | (age > 104 & age < 121)) {
Else после return писать не нужно.

2024-11-24 11:19 UTC, ekolokolov commented on src/main/java/com/walking/intensive/chapter1/task1/Task1.java
> +        } else if ((ageDiv == 0) | (ageDiv >=5 && ageDiv <= 9)) {
`ageDiv <= 9` всегда истинен. Можно удалить.

2024-11-24 11:19 UTC, ekolokolov commented on src/main/java/com/walking/intensive/chapter1/task1/Task1.java
> +        return null;
Этот return тут зачем?

2024-11-26 08:01 UTC, Enhusikpro commented on src/main/java/com/walking/intensive/chapter1/task1/Task1.java
> +        return null;
Добрый день! Если я убираю последний return = idea ругается на его отсутствие

2024-11-28 15:50 UTC, ekolokolov requested changes

2024-11-28 15:50 UTC, ekolokolov commented on src/main/java/com/walking/intensive/chapter1/task1/Task1.java
> +            return "Вам " + age + " лет";
Эти условия можно объединить.

2024-11-28 15:50 UTC, ekolokolov commented on src/main/java/com/walking/intensive/chapter1/task1/Task1.java
> +        if (ageDiv >= 2) {
если у тебя есть строка `return "";` то ты ее скорее всего добавил чтобы компилятор не ругался. По факту же до этой строки код никогда не выполнится. Это значит что последний if выполняется в любом случае. Значит его можно удалить.

2024-12-15 11:41 UTC, closed without merging