Task2
KFalcon2022/intensive-tasks-2024 pull request #203
Opened 2024-11-19 19:41 UTC by alonecat13

2024-11-19 19:52 UTC, EvgeneZhurov requested changes
Поправьте замечания и продолжим общение по существу

2024-11-19 19:52 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task1/Task1.java
> +            return "Вам " + age + " года goda";
Проверяться будет только вторая задача

2024-11-19 19:52 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task2/Task2.java
> +        String fullResult = "";
Блоки if лучше отделять пустыми строками с обеих сторон, так читается легче

2024-11-19 19:52 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task2/Task2.java
> +            System.out.println("Неверные вводные параметры!!!");
лучше return

2024-11-19 19:52 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task2/Task2.java
> +        if (floorAmount > 0 && entranceAmount > 0 && flatNumber > 0 && flatNumber <= maxflatNumber) {
валидация была выше.

2024-11-19 19:52 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task2/Task2.java
> +                if (floorNumber % 4 == 0) {
почитайте про магическое число java, здесь это число 4

2024-11-19 19:52 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task2/Task2.java
> +            fullResult = flatNumber + " кв – " + ((flatNumber / maxFlatsOnEntrance) + 1) + " подъезд, " + floorNumber;
если называть возвращаемую переменную как имя метода, только без глагола читаемость код авозрастет

2024-11-20 10:06 UTC, alonecat13 commented on src/main/java/com/walking/intensive/chapter1/task2/Task2.java
> +                if (floorNumber % 4 == 0) {
fixed

2024-11-20 10:07 UTC, alonecat13 commented on src/main/java/com/walking/intensive/chapter1/task2/Task2.java
> +            fullResult = flatNumber + " кв – " + ((flatNumber / maxFlatsOnEntrance) + 1) + " подъезд, " + floorNumber;
fixed.

2024-11-20 10:07 UTC, alonecat13 commented on src/main/java/com/walking/intensive/chapter1/task2/Task2.java
> +        if (floorAmount > 0 && entranceAmount > 0 && flatNumber > 0 && flatNumber <= maxflatNumber) {
fixed.

2024-11-20 10:07 UTC, alonecat13 commented on src/main/java/com/walking/intensive/chapter1/task2/Task2.java
> +            System.out.println("Неверные вводные параметры!!!");
fixed.

2024-11-20 10:08 UTC, alonecat13 commented on src/main/java/com/walking/intensive/chapter1/task2/Task2.java
> +        String fullResult = "";
fixed.

2024-11-20 10:09 UTC, alonecat13 commented on src/main/java/com/walking/intensive/chapter1/task1/Task1.java
> +            return "Вам " + age + " года goda";
как можно вычистить репозиторий \ бранч от Task1?

2024-11-20 19:19 UTC, EvgeneZhurov requested changes

2024-11-20 19:19 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task2/Task2.java
> +
40 кв – 2 подъезд, 10справа от лифта, вправо
не хватает пробела.

2024-11-20 19:19 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task2/Task2.java
int flatsOnFloor = 4; лучше сделать константой используя модификатор доступа final

2024-12-04 09:34 UTC, closed without merging

2024-12-04 09:34 UTC, EvgeneZhurov commented
Просьба открыть новый PR, если нужна проверка.