Task1
KFalcon2022/intensive-tasks-2024 pull request #205
Opened 2024-11-19 21:19 UTC by AndyRaw007

v2

2024-11-19 23:56 UTC, Zawadskiy requested changes

2024-11-19 23:56 UTC, Zawadskiy commented on build.gradle
> +        languageVersion = JavaLanguageVersion.of(23)
Что єто здесь делает?

2024-11-19 23:56 UTC, Zawadskiy commented on src/main/java/com/walking/intensive/chapter1/task1/Task1.java
> +        else if (age > 10 && age < 15) {
Чекстайл негодует переносом else на новую строку.

2024-11-19 23:56 UTC, Zawadskiy commented on src/main/java/com/walking/intensive/chapter1/task1/Task1.java
> +            return "Некорректный ввод";
Если в блоке if есть return, тогда else не пишем. Пример:
if(){
return;
}
if(){
}

2024-11-19 23:56 UTC, Zawadskiy commented on src/main/java/com/walking/intensive/chapter1/task1/Task1.java
> +            case 2:
2,3,4 можно схлопнуть.

2024-11-20 07:18 UTC, AndyRaw007 commented on build.gradle
> +        languageVersion = JavaLanguageVersion.of(23)
Это случайно залилось, не нашел как удалить. В последующих задачах не будет)

2024-11-20 20:53 UTC, Zawadskiy requested changes

2024-11-20 20:53 UTC, Zawadskiy commented on build.gradle
> +        languageVersion = JavaLanguageVersion.of(23)
Сделать pr в котором 23 на 21 смени) У меня тестіі не проходят на 23-й версии)

2024-11-20 20:53 UTC, Zawadskiy commented on src/main/java/com/walking/intensive/chapter1/task1/Task1.java
> +        }   if (age > 10 && age < 15) {
почему if не на новой строке?) Посмотри checkstyle б ибо мне кажется что даже return имеет слишком много пробелов перед ним)

2024-11-21 12:25 UTC, AndyRaw007 commented on build.gradle
> +        languageVersion = JavaLanguageVersion.of(23)
Понял, принял, поменял)

2024-11-21 12:31 UTC, AndyRaw007 commented on src/main/java/com/walking/intensive/chapter1/task1/Task1.java
> +        else if (age > 10 && age < 15) {
Исправлено

2024-11-22 00:31 UTC, Zawadskiy requested changes

2024-11-22 00:31 UTC, Zawadskiy commented on src/main/java/com/walking/intensive/chapter1/task1/Task1.java
> +        return "Некорректный ввод";
Почему return наравне с if? Загугли checkstyle java. Сама idea должна вііравнивать строки правильно ctrl + alt + l.

2024-11-22 00:31 UTC, Zawadskiy commented on src/main/java/com/walking/intensive/chapter1/task1/Task1.java
> +        if (age > 10 && age < 15) {
Єтот и if ниже можно в один впихнуть с условием age % 100 что-то там)

2024-11-22 18:37 UTC, AndyRaw007 commented on src/main/java/com/walking/intensive/chapter1/task1/Task1.java
> +        if (age > 10 && age < 15) {
Переделал

2024-11-23 00:46 UTC, Zawadskiy approved these changes

2024-11-23 00:47 UTC, closed without merging