Task3
KFalcon2022/intensive-tasks-2024 pull request #207
Opened 2024-11-19 23:05 UTC by kps-d

2024-11-19 23:58 UTC, Zawadskiy requested changes

2024-11-19 23:58 UTC, Zawadskiy commented on src/main/java/com/walking/intensive/chapter1/task3/Task3.java
> +        if (year % 400 == 0) {
Почему біі не сделать одно boolean вііражение вместо нескольких if и того что в return?

2024-11-20 17:58 UTC, kps-d commented on src/main/java/com/walking/intensive/chapter1/task3/Task3.java
> +        if (year % 400 == 0) {
Готово)

2024-11-20 20:49 UTC, Zawadskiy approved these changes

2024-11-20 20:49 UTC, closed without merging