Task 4
KFalcon2022/intensive-tasks-2024 pull request #209
Opened 2024-11-20 01:28 UTC by NazarLysyi

2024-11-20 02:49 UTC, Zawadskiy requested changes

2024-11-20 02:49 UTC, Zawadskiy commented on src/main/java/com/walking/intensive/chapter1/task4/Task4.java
> +            return "Количество решений: 2. Корни: " + formatRoot(Math.min(root1, root2)) + ";" + formatRoot(Math.max(root1, root2));
Error: eckstyle] [ERROR] /home/runner/work/intensive-tasks-2024/intensive-tasks-2024/src/main/java/com/walking/intensive/chapter1/task4/Task4.java:48: Line is longer than 120 characters (found 132). [LineLength]

2024-11-20 02:49 UTC, Zawadskiy commented on src/main/java/com/walking/intensive/chapter1/task4/Task4.java
> +    static String formatRoot(double root) {
Зачем ЄТО?

2024-11-20 02:49 UTC, Zawadskiy commented on src/main/java/com/walking/intensive/chapter1/task4/Task4.java
> +        } else if (a == 0 && b == 0) {
Если в блоке if есть return, то else не пишем. продолжаем как отдельніій if если бііло if/else или просто пишем дальше код если просто if.

2024-11-20 02:49 UTC, Zawadskiy commented on src/main/java/com/walking/intensive/chapter1/task4/Task4.java
> +            return "Количество решений: 2. Корни: " + formatRoot(Math.min(root1, root2)) + ";" + formatRoot(Math.max(root1, root2));
И тестіі тоже пройди =) 
> Task :test FAILED

Task4Test > solveEquationTest(String, double, double, double) > [15] Количество решений: 1. Корень: 1.0, 0, -2, 2 FAILED
    org.opentest4j.AssertionFailedError at Task4Test.java:18

Task4Test > solveEquationTest(String, double, double, double) > [16] Количество решений: 1. Корень: 2.0, 0, -2, 4 FAILED
    org.opentest4j.AssertionFailedError at Task4Test.java:18

Task4Test > solveEquationTest(String, double, double, double) > [17] Количество решений: 1. Корень: 4.0, 0, -2, 8 FAILED
    org.opentest4j.AssertionFailedError at Task4Test.java:18

Task4Test > solveEquationTest(String, double, double, double) > [18] Количество решений: 1. Корень: 2.0, 0, 20, -[40](https://github.com/KFalcon2022/intensive-tasks-2024/actions/runs/11924960191/job/33238308039?pr=209#step:6:41) FAILED
    org.opentest4j.AssertionFailedError at Task4Test.java:18

Task4Test > solveEquationTest(String, double, double, double) > [19] Количество решений: 1. Корень: 8.0, 0, 10, -80 FAILED
    org.opentest4j.AssertionFailedError at Task4Test.java:18

Task4Test > solveEquationTest(String, double, double, double) > [20] Количество решений: 1. Корень: 0.0, 1, 0, 0 FAILED
    org.opentest4j.AssertionFailedError at Task4Test.java:18

Task4Test > solveEquationTest(String, double, double, double) > [21] Количество решений: 1. Корень: 1.0, 1, -2, 1 FAILED
    org.opentest4j.AssertionFailedError at Task4Test.java:18

Task4Test > solveEquationTest(String, double, double, double) > [22] Количество решений: 1. Корень: 2.0, 1, -4, 4 FAILED
    org.opentest4j.AssertionFailedError at Task4Test.java:18

Task4Test > solveEquationTest(String, double, double, double) > [23] Количество решений: 1. Корень: 3.0, 1, -6, 9 FAILED
    org.opentest4j.AssertionFailedError at Task4Test.java:18

Task4Test > solveEquationTest(String, double, double, double) > [24] Количество решений: 1. Корень: 4.0, 1, -8, 16 FAILED
    org.opentest4j.AssertionFailedError at Task4Test.java:18

Task4Test > solveEquationTest(String, double, double, double) > [25] Количество решений: 1. Корень: 5.0, 1, -10, 25 FAILED
    org.opentest4j.AssertionFailedError at Task4Test.java:18

Task4Test > solveEquationTest(String, double, double, double) > [26] Количество решений: 2. Корни: -5.0;-4.0, 1, 9, 20 FAILED
    org.opentest4j.AssertionFailedError at Task4Test.java:18

Task4Test > solveEquationTest(String, double, double, double) > [27] Количество решений: 2. Корни: -3.0;-2.0, 1, 5, 6 FAILED
    org.opentest4j.AssertionFailedError at Task4Test.java:18


30 tests completed, 16 failed
Task4Test > solveEquationTest(String, double, double, double) > [28] Количество решений: 2. Корни: 3.0;5.0, 1, -8, 15 FAILED
    org.opentest4j.AssertionFailedError at Task4Test.java:18

Task4Test > solveEquationTest(String, double, double, double) > [29] Количество решений: 2. Корни: -9.0;5.0, 1, 4, -[45](https://github.com/KFalcon2022/intensive-tasks-2024/actions/runs/11924960191/job/33238308039?pr=209#step:6:46) FAILED
    org.opentest4j.AssertionFailedError at Task4Test.java:18

Task4Test > solveEquationTest(String, double, double, double) > [30] Количество решений: 2. Корни: -1.0;4.0, -1, 3, 4 FAILED
    org.opentest4j.AssertionFailedError at Task4Test.java:18

FAILURE: Build failed with an exception.

2024-11-21 00:51 UTC, NazarLysyi commented on src/main/java/com/walking/intensive/chapter1/task4/Task4.java
> +    static String formatRoot(double root) {
в тестах была ошибка с 1.0, сделал форматирование вывода. не знал что есть правки

2024-11-21 00:52 UTC, NazarLysyi commented on src/main/java/com/walking/intensive/chapter1/task4/Task4.java
> +            return "Количество решений: 2. Корни: " + formatRoot(Math.min(root1, root2)) + ";" + formatRoot(Math.max(root1, root2));
код написан до правок в тестах) ребейс сделал, ща поправлю

2024-11-21 01:13 UTC, closed without merging