Task6
KFalcon2022/intensive-tasks-2024 pull request #225
Opened 2024-11-20 11:28 UTC by gentrus

2024-11-20 19:54 UTC, KateKhodko requested changes

2024-11-20 19:54 UTC, KateKhodko commented on src/main/java/com/walking/intensive/chapter2/task6/Task6.java
> +                    return n;
Лучше будет использовать while с условием выхода из цикла

2024-11-20 19:54 UTC, KateKhodko commented on src/main/java/com/walking/intensive/chapter2/task6/Task6.java
> +                return m;
Лучше будет использовать while с условием выхода из цикла

2024-11-20 19:54 UTC, KateKhodko commented on src/main/java/com/walking/intensive/chapter2/task6/Task6.java
> +                }
Можно эти условия объединить через &&

2024-11-20 19:54 UTC, KateKhodko commented on src/main/java/com/walking/intensive/chapter2/task6/Task6.java
> +                    return i;
Можно эти условия объединить через &&

2024-11-20 19:54 UTC, KateKhodko commented on src/main/java/com/walking/intensive/chapter2/task6/Task6.java
> +        for (; ; ) {
Тут тоже можно попробовать сделать через while с условием, бесконечные циклы не best practies

2024-11-21 15:06 UTC, gentrus commented on src/main/java/com/walking/intensive/chapter2/task6/Task6.java
> +        for (; ; ) {
Исправил. Спасибо за развернутые комментарии)

2024-11-21 15:36 UTC, closed without merging