Task4
KFalcon2022/intensive-tasks-2024 pull request #229
Opened 2024-11-20 12:49 UTC by michael-altf4

2024-11-20 20:10 UTC, EvgeneZhurov requested changes

2024-11-20 20:10 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task4/Task4.java
> +        if (a == 0 && b == 0) return "Бесконечное множество решений.";
Просьба выделать блок кода после if () скобками{}, даже если всего одна строка кода. Так принято в местном комьюнити.

2024-11-20 20:10 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task4/Task4.java
> +        if (a == 0 && b == 0) return "Бесконечное множество решений.";
Если параметр c == 0, то бесконечно, если не равен, то "Решений нет"

2024-11-20 20:10 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task4/Task4.java
> +        double discriminant = b * b - 4 * a * c;
не рассмотрен случай, когда b!=0 при a=0. Будет единственное решение x = - с/b

2024-11-20 20:10 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task4/Task4.java
> +        else if (discriminant == 0) return "Количество решений: 1. Корень: " + (int) b / 2 * (-a);
после return не ставится else

2024-11-20 20:10 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task4/Task4.java
> +        else if (discriminant == 0) return "Количество решений: 1. Корень: " + (int) b / 2 * (-a);
решение может быть любым вещественным числом

2024-11-21 04:47 UTC, michael-altf4 commented on src/main/java/com/walking/intensive/chapter1/task4/Task4.java
> +        else if (discriminant == 0) return "Количество решений: 1. Корень: " + (int) b / 2 * (-a);
Не совсем понял фразу. Такой случай происходит в выражении 0xx+0x+0=0. Он рассмотрен вначале. Что нужно поправить в данном блоке

2024-11-21 19:33 UTC, EvgeneZhurov requested changes

2024-11-21 19:33 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task4/Task4.java
> +            return "Количество решений: 1. Корень: " + (int) (-c) / b;
решение не обязательно целое число

2024-11-21 19:33 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task4/Task4.java
> +        if (a == 0 && b != 0) {
b != 0 Idea подсвечивает варнинг. Это условие и так выполнится, потому что вверху выполнено условие, что b == 0

2024-11-22 15:48 UTC, michael-altf4 commented on src/main/java/com/walking/intensive/chapter1/task4/Task4.java
> +        if (a == 0 && b != 0) {
Убрал else return выше. Варнинг исчез

2024-11-22 19:49 UTC, EvgeneZhurov requested changes

2024-11-24 09:05 UTC, EvgeneZhurov approved these changes

2024-11-24 09:05 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task4/Task4.java
>          if (a == 0 && b != 0) {
между блоками кода можно ставить пустые строки если это не начало и конец метода. Повысится читаемость кода.

2024-11-24 09:06 UTC, EvgeneZhurov commented
хорошо 👍

2024-11-24 09:06 UTC, closed without merging