Task6
KFalcon2022/intensive-tasks-2024 pull request #231
Opened 2024-11-20 13:46 UTC by PabloQuetzalcoatl

2024-11-24 16:34 UTC, EvgeneZhurov requested changes

2024-11-24 16:34 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter2/task6/Task6.java
>              int ostatok = a % b;
Лучше не называть переменные кириллицей

2024-11-24 16:34 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter2/task6/Task6.java
> +        int a = Math.max(m, n);
Задача может быть засчитана и без этого метода, просьба написать в ответе будете ли Вы ее делать.

2024-11-24 16:34 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter2/task6/Task6.java
> +        if (m <= 0 || n <= 0) {
просьба реализовать метод через рекурсию

2024-11-24 19:13 UTC, PabloQuetzalcoatl commented on src/main/java/com/walking/intensive/chapter2/task6/Task6.java
> +        int a = Math.max(m, n);
Всенепременно буду.

2024-11-26 19:46 UTC, EvgeneZhurov approved these changes

2024-11-26 19:47 UTC, closed without merging