Task 2
KFalcon2022/intensive-tasks-2024 pull request #236
Opened 2024-11-20 14:15 UTC by AndinaZS

2024-11-20 21:07 UTC, EvgeneZhurov requested changes

2024-11-20 21:07 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task2/Task2.java
> +        } else if (isFlatOnFloor) {
после return не ставят else

2024-11-20 21:07 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task2/Task2.java
> +        boolean isFlatOnFloor = floorAmount * entranceAmount * 4 < flatNumber;
советую почитать про магическое число java

2024-11-20 21:07 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task2/Task2.java
>      static String getFlatLocation(int floorAmount, int entranceAmount, int flatNumber) {
Неверная логика создания метода. Метод фактически является валидацией, логичнее было создать метод валидации отдельно. Название не отражает работу метода.

2024-11-21 06:46 UTC, AndinaZS commented on src/main/java/com/walking/intensive/chapter1/task2/Task2.java
> +        } else if (isFlatOnFloor) {
сделала с переменной, другой вариант не придумался..

2024-11-21 06:48 UTC, AndinaZS commented on src/main/java/com/walking/intensive/chapter1/task2/Task2.java
>      static String getFlatLocation(int floorAmount, int entranceAmount, int flatNumber) {
убрала валидацию напрямую в условие. показалось, что делать отдельные методы излишне.

2024-11-21 20:26 UTC, EvgeneZhurov approved these changes
69 пустая строка лишняя, местное комьюнити такое не приветствует.

2024-11-21 20:26 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task2/Task2.java
>      static String getFlatLocation(int floorAmount, int entranceAmount, int flatNumber) {
речь была о другом. У Вас название метода отличается от того, какая логика работает внутри. Не суть.

2024-11-21 20:26 UTC, closed without merging