Task 3
KFalcon2022/intensive-tasks-2024 pull request #237
Opened 2024-11-20 14:17 UTC by AndinaZS

2024-11-20 21:02 UTC, EvgeneZhurov requested changes

2024-11-20 21:02 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task3/Task3.java
> +        return condition1 & !condition2 & condition3;
Между & и && есть разница. && более эффективный.

2024-11-20 21:02 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task3/Task3.java
> +        boolean condition3 = year % 4 == 0;
просьба в одну строку перечислить возвращаемые условия без введения переменных

2024-11-21 06:27 UTC, AndinaZS commented on src/main/java/com/walking/intensive/chapter1/task3/Task3.java
> +        return condition1 & !condition2 & condition3;
спасибо, почитала разницу, поправила.

2024-11-21 06:27 UTC, AndinaZS commented on src/main/java/com/walking/intensive/chapter1/task3/Task3.java
> +        boolean condition3 = year % 4 == 0;
исправила

2024-11-21 20:10 UTC, EvgeneZhurov requested changes

2024-11-21 20:10 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task3/Task3.java
> +        return year > 1581 && !(year % 100 == 0 && year % 400 != 0) & year % 4 == 0;
лучше пытаться создавать логические условия без отрицания разворачивая их. Приведу пример: Это не было бы неправильно сказать „нет“ не в той ситуации. Пытайтесь казать прямо чего Вы хотите.

2024-11-22 07:11 UTC, EvgeneZhurov approved these changes

2024-11-22 07:11 UTC, closed without merging