task1
KFalcon2022/intensive-tasks-2024 pull request #24
Opened 2024-11-16 19:37 UTC by tux33me

2024-11-16 19:51 UTC, EvgeneZhurov requested changes

2024-11-16 19:51 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task1/Task1.java
> +
Просьба чуть переписать логические условия. Сделайте 4 разных return из метода. Код будет более читаемым. Например подумайте какое из логических условий легче всего написать, чтобы это было читаемо и напишите логической условие именно для него, потом для остальных. В целом задача решена верно.

2024-11-16 19:51 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task1/Task1.java
> +        String ending = " лет";
можно не вводить строку, чуть ниже требование к оформлению задачи, чтобы код был более читаемым.

2024-11-17 05:36 UTC, tux33me commented on src/main/java/com/walking/intensive/chapter1/task1/Task1.java
> +
Сделал 5. Если делать 4, получается опять слишком сложное условие.
Если можно, задам вопрос. С таким количеством return не проще допустить ошибку, чем с одним в конце метода? Скажем, допустить ошибку в формировании строки "Вам" или пропустить пробел и т.д. Получается некое дублирование кода и ctrl-c ctrl-v) Или я неправильно понял задачу?

2024-11-17 09:04 UTC, EvgeneZhurov requested changes

2024-11-17 09:04 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task1/Task1.java
> +            if (age % 10 > 1 && age % 10 < 5) {
двойное вложение не требуется, можно перечислить логические условия в одном if без вложения

2024-11-17 16:52 UTC, EvgeneZhurov approved these changes
принято

2024-11-17 16:53 UTC, closed without merging