Task 3
KFalcon2022/intensive-tasks-2024 pull request #249
Opened 2024-11-20 19:13 UTC by ox000

2024-11-20 20:56 UTC, EvgeneZhurov requested changes

2024-11-20 20:56 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task3/Task3.java
> +        } else if (year % 4 == 0 && year % 100 != 0) {
после return не ставят else. Либо будет выход из метода, либо метод продолжи исполняться и без else.

2024-11-20 20:56 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task3/Task3.java
> +        if (year < 1582) {
попробуйте собрать одно больше логическое условие используя || или && и вернуть его. Тогда ветвление не понадобится

2024-11-24 12:22 UTC, EvgeneZhurov requested changes

2024-11-24 12:22 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task3/Task3.java
> +        return ((year % 4 == 0 && year % 100 != 0) || year % 400 == 0) && year > 1582;
просьба убрать лишние скобки.

2024-11-24 12:42 UTC, ox000 commented on src/main/java/com/walking/intensive/chapter1/task3/Task3.java
> +        return ((year % 4 == 0 && year % 100 != 0) || year % 400 == 0) && year > 1582;
я попробовал еще вообще без скобок, тесты проходит, но кажется как-то неправильно

2024-11-24 15:41 UTC, EvgeneZhurov approved these changes

2024-11-24 15:41 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task3/Task3.java
лишняя пустая строка

2024-11-24 15:41 UTC, closed without merging