Task4
KFalcon2022/intensive-tasks-2024 pull request #259
Opened 2024-11-20 22:38 UTC by LVictor-SF

2024-11-21 00:47 UTC, Zawadskiy requested changes

2024-11-21 00:47 UTC, Zawadskiy commented on src/main/java/com/walking/intensive/chapter1/task4/Task4.java
>      static String solveEquation(double a, double b, double c) {
30 tests completed, 20 failed
Не нужно кастовать результат к int.

2024-11-21 00:47 UTC, Zawadskiy commented on src/main/java/com/walking/intensive/chapter1/task4/Task4.java
> +
Лишняя пустая строка.

2024-11-21 00:47 UTC, Zawadskiy commented on src/main/java/com/walking/intensive/chapter1/task4/Task4.java
> +        }
Пустая строка.

2024-11-21 00:47 UTC, Zawadskiy commented on src/main/java/com/walking/intensive/chapter1/task4/Task4.java
> +            x1 = (0 - b) / (2 * a);
Если в логическом блоке только return, то пишем только его.
     if (d < 0) {
            return "Количество решений: 0" + ".";
     }
Иначе не єтономим на пустііх строках.
if () {

some text;

return;
}

2024-11-22 00:25 UTC, Zawadskiy requested changes

2024-11-22 00:25 UTC, Zawadskiy commented on src/main/java/com/walking/intensive/chapter1/task4/Task4.java
>      static String solveEquation(double a, double b, double c) {
> Task :test FAILED

Task4Test > solveEquationTest(String, double, double, double) > [1] Количество решений: 0., 0, 0, -10 FAILED
    org.opentest4j.AssertionFailedError at Task4Test.java:18

Task4Test > solveEquationTest(String, double, double, double) > [2] Количество решений: 0., 0, 0, 1 FAILED
    org.opentest4j.AssertionFailedError at Task4Test.java:18

Task4Test > solveEquationTest(String, double, double, double) > [3] Количество решений: 0., 0, 0, 4 FAILED
    org.opentest4j.AssertionFailedError at Task4Test.java:18

Task4Test > solveEquationTest(String, double, double, double) > [4] Бесконечное множество решений., 0, 0, 0 FAILED
    org.opentest4j.AssertionFailedError at Task4Test.java:18

Task4Test > solveEquationTest(String, double, double, double) > [26] Количество решений: 2. Корни: -5.0;-4.0, 1, 9, 20 FAILED
    org.opentest4j.AssertionFailedError at Task4Test.java:18

Task4Test > solveEquationTest(String, double, double, double) > [27] Количество решений: 2. Корни: -3.0;-2.0, 1, 5, 6 FAILED
    org.opentest4j.AssertionFailedError at Task4Test.java:18
30 tests completed, 9 failed

2024-11-22 00:25 UTC, Zawadskiy commented on src/main/java/com/walking/intensive/chapter1/task4/Task4.java
> +            return "Некорректные входные данные";
<p>Метод должен возвращать в виде строки количество решений, а также сами решения в указанном ниже формате:
 * <ul>
 * <li> "Количество решений: 2. Корни: -4;4"
 * <li> "Количество решений: 1. Корень: 0"
 * <li> "Количество решений: 0."
 * <li> "Бесконечное множество решений."
 * </ul>

2024-11-23 00:45 UTC, Zawadskiy requested changes

2024-11-23 00:45 UTC, Zawadskiy commented on src/main/java/com/walking/intensive/chapter1/task4/Task4.java
> +            return "Количество решений: 0" + ".";
Почему не в одной строке? Зачем здесь конкатенация?

2024-11-23 00:45 UTC, Zawadskiy commented on src/main/java/com/walking/intensive/chapter1/task4/Task4.java
> +            return "Бесконечное множество решений";
Где точка? =)
Task4Test > solveEquationTest(String, double, double, double) > [1] Количество решений: 0., 0, 0, -10 FAILED
    org.opentest4j.AssertionFailedError at Task4Test.java:18

Task4Test > solveEquationTest(String, double, double, double) > [2] Количество решений: 0., 0, 0, 1 FAILED

    org.opentest4j.AssertionFailedError at Task4Test.java:18
30 tests completed, 4 failed

2024-11-23 00:45 UTC, Zawadskiy commented on src/main/java/com/walking/intensive/chapter1/task4/Task4.java
> +            return "Бесконечное множество решений";
FAILURE: Build failed with an exception.
Task4Test > solveEquationTest(String, double, double, double) > [3] Количество решений: 0., 0, 0, 4 FAILED

    org.opentest4j.AssertionFailedError at Task4Test.java:18
* What went wrong:

Execution failed for task ':test'.
Task4Test > solveEquationTest(String, double, double, double) > [4] Бесконечное множество решений., 0, 0, 0 FAILED

2024-11-25 22:04 UTC, Zawadskiy requested changes

2024-11-25 22:04 UTC, Zawadskiy commented on src/main/java/com/walking/intensive/chapter1/task4/Task4.java
> +            return "Некорректные входные данные.";
Откуд тіі єту строку взял?

 * <li> "Количество решений: 2. Корни: -4;4"
 * <li> "Количество решений: 1. Корень: 0"
 * <li> "Количество решений: 0."
 * <li> "Бесконечное множество решений."

2024-11-26 07:46 UTC, LVictor-SF commented on src/main/java/com/walking/intensive/chapter1/task4/Task4.java
> +            return "Некорректные входные данные.";
<p>Если с указанными коэффициентами уравнение некорректно - метод должен вернуть строку
 * "Некорректные входные данные".
 *

2024-11-27 04:20 UTC, Zawadskiy approved these changes

2024-11-27 04:23 UTC, Zawadskiy requested changes

2024-11-27 04:23 UTC, Zawadskiy commented on src/main/java/com/walking/intensive/chapter1/task4/Task4.java
> +        double x2;
Переменнііе обьявляем ближе к месту их использования

2024-11-27 04:23 UTC, Zawadskiy commented on src/main/java/com/walking/intensive/chapter1/task4/Task4.java
> +            x1 = (0 - c) / b;
хз зачем тут в переменную вііносить, буквально строкой ниже возвращается результат
"Количество решений: 1. Корень: " + -c / b;

2024-11-27 04:23 UTC, Zawadskiy commented on src/main/java/com/walking/intensive/chapter1/task4/Task4.java
> +            x1 = (0 - c) / b;
0 - c серйозно?

2024-11-27 04:23 UTC, Zawadskiy commented on src/main/java/com/walking/intensive/chapter1/task4/Task4.java
> +            x1 = (0 - b) / (2 * a);
Аналогично

2024-11-27 04:23 UTC, Zawadskiy commented on src/main/java/com/walking/intensive/chapter1/task4/Task4.java
> +        x1 = (((0 - b) + Math.sqrt(d)) / (2 * a));
-_-  0 - b

2024-11-28 01:41 UTC, Zawadskiy requested changes

2024-11-28 01:41 UTC, Zawadskiy commented on src/main/java/com/walking/intensive/chapter1/task4/Task4.java
> +            return "Количество решений: 1. Корень: " + -b / (2 * a);
Предполагаю что у тебя там -0.0 как корень)
30 tests completed, 1 failed
> Task :test FAILED
Task4Test > solveEquationTest(String, double, double, double) > [20] Количество решений: 1. Корень: 0.0, 1, 0, 0

2024-12-12 09:54 UTC, Zawadskiy requested changes

2024-12-12 09:54 UTC, Zawadskiy commented on src/main/java/com/walking/intensive/chapter1/task4/Task4.java
> +            return "Количество решений: 1. Корень: " + (-b / (2 * a));
и как єто должно бііло помочь?)
> Task :test FAILED
Task4Test > solveEquationTest(String, double, double, double) > [20] Количество решений: 1. Корень: 0.0, 1, 0, 0 FAILED
30 tests completed, 1 failed

2024-12-12 10:14 UTC, LVictor-SF commented on src/main/java/com/walking/intensive/chapter1/task4/Task4.java
> +            return "Количество решений: 1. Корень: " + (-b / (2 * a));
Ну смотри, я не понимаю в чем проблема, в чем ошибка и пытаюсь исправить как могу. Ты хоть объясни нормально в чем проблема?
Количество решений: 1. Корень: 0.0, 1, 0, 0 FAILED - эт что значит?. Что при коэф-ах 1,0,0 должен быть корень 0.0? А у меня что? - 0.0? Я тогда не знаю что делать,  с отрицательным 0 в java не знаком, он вообще есть? Или этот - залетный?

2024-12-12 10:16 UTC, LVictor-SF commented on src/main/java/com/walking/intensive/chapter1/task4/Task4.java
> +            return "Количество решений: 1. Корень: " + (-b / (2 * a));
Вроде раньше такой ошибки не выдавал, так?

2024-12-12 10:19 UTC, Zawadskiy commented on src/main/java/com/walking/intensive/chapter1/task4/Task4.java
> +            return "Количество решений: 1. Корень: " + (-b / (2 * a));
Раньше тоже бііла ошибка прохождения теста) Вообще можешь посмотреть как люди в других задачах решали єту проблему)

2024-12-12 12:27 UTC, Zawadskiy requested changes

2024-12-12 12:27 UTC, Zawadskiy commented on src/main/java/com/walking/intensive/chapter1/task4/Task4.java
> +            return "Количество решений: 1. Корень: " + -b / (2 * a);
-b / (2 * a); - зачем єто считать еще раз?)

2024-12-12 12:29 UTC, Zawadskiy requested changes

2024-12-12 12:29 UTC, Zawadskiy commented on src/main/java/com/walking/intensive/chapter1/task4/Task4.java
> +            double x1 = -b / (2 * a);
Пустііе строки где?

2024-12-12 12:31 UTC, closed without merging