Task5
KFalcon2022/intensive-tasks-2024 pull request #262
Opened 2024-11-21 05:58 UTC by michael-altf4

2024-11-21 16:32 UTC, KateKhodko commented on src/main/java/com/walking/intensive/chapter1/task5/Task5.java
> +    static double areaByHeron = getAreaByHeron(a, b, c);
1) Статик переменные пишутся в начале класса, перед объявлением метода `main`
2) Если это уже объявлено как статик, то пишем в верхнем регистре, то есть `areaByHeron` -> `AREA_BY_HERO`
3) Если мы захотим переиспользовать метод, например, поиск высот, то нам придется каждый раз менять значения полей для всего класса `a, b, c`, потому что от них зависит площадь. Поэтому площадь лучше расчитывать внутри вызываемого метода, а статик значения `a, b, c` уйдут вместе с ним

2024-11-21 16:34 UTC, KateKhodko commented on src/main/java/com/walking/intensive/chapter1/task5/Task5.java
> +        heights[2] = 2 * areaByHeron / c;
`areaByHeron` - рассчитывать тут по входным параметрам, а не при инициализации класса

2024-11-21 16:46 UTC, KateKhodko commented on src/main/java/com/walking/intensive/chapter1/task5/Task5.java
> +        }
Вот эта проверка дублируется во многих методах, можно вынести ее в отдельный метод

2024-11-22 11:57 UTC, michael-altf4 commented on src/main/java/com/walking/intensive/chapter1/task5/Task5.java
> +    static double areaByHeron = getAreaByHeron(a, b, c);
Такая оптимизация недопустима?  Делаю вывод с комментария

2024-11-22 23:20 UTC, KateKhodko commented on src/main/java/com/walking/intensive/chapter1/task5/Task5.java
> +    static double areaByHeron = getAreaByHeron(a, b, c);
В таком виде - нет, т.к. при запуске программы ты жестко вычисляешь статическую переменную для всего класса (т.к. сразу вбил определенные значения сторон треугольника), несмотря на то, что твои методы должны работать с различными входными данными

2024-11-22 23:27 UTC, KateKhodko requested changes

2024-11-22 23:27 UTC, KateKhodko commented on src/main/java/com/walking/intensive/chapter1/task5/Task5.java
> +        if (paramIsNegative(a, b, c) || !isTriangle(a, b, c)) {
param**s**IsNegative

2024-11-22 23:27 UTC, KateKhodko commented on src/main/java/com/walking/intensive/chapter1/task5/Task5.java
> +        return (a <= 0 || b <= 0 || c <= 0);
тут скобочки можно не ставить

2024-11-22 23:27 UTC, KateKhodko commented on src/main/java/com/walking/intensive/chapter1/task5/Task5.java
> +        return (a + b > c) && (a + c > b) && (b + c > a);
тут скобочки можно не ставить

2024-11-22 23:27 UTC, KateKhodko commented on src/main/java/com/walking/intensive/chapter1/task5/Task5.java
> +
лишняя пустая строка

2024-11-22 23:27 UTC, KateKhodko commented on src/main/java/com/walking/intensive/chapter1/task5/Task5.java
> +        return (a <= 0 || b <= 0 || c <= 0);
И сверху лишняя пустая строка

2024-11-22 23:27 UTC, KateKhodko commented on src/main/java/com/walking/intensive/chapter1/task5/Task5.java
> +        return (a + b > c) && (a + c > b) && (b + c > a);
И сверху лишняя пустая строка

2024-11-22 23:27 UTC, KateKhodko commented on src/main/java/com/walking/intensive/chapter1/task5/Task5.java
> +
Не нужно разделять пустой строкой тут, смотрится как хороший логический блок

2024-11-23 14:08 UTC, KateKhodko approved these changes

2024-11-23 14:08 UTC, closed without merging