task5
KFalcon2022/intensive-tasks-2024 pull request #263
Opened 2024-11-21 06:05 UTC by Superbia101

Я создал по образцу, для выполнения задач, свой метод. Надеюсь, что не запрещено)

Спасибо Вам.
Вроде пока только начал разбираться, но уже было полезно.
Да и гитхаб лучше узнал )

2024-11-21 16:48 UTC, PuccaGTS requested changes
Давайте поправим

2024-11-22 12:43 UTC, Superbia101 commented on src/main/java/com/walking/intensive/chapter1/task5/Task5.java
> +        if (num[0] >= num[1] + num[2]) {
Чуть доработал, но как Вы советовали не сумел - метод ещё возвращает значения для расчёта. А ка я понял, если он будет возвращать boolean - значения он возвращать уже не сможет?

2024-11-22 12:43 UTC, Superbia101 commented on src/main/java/com/walking/intensive/chapter1/task5/Task5.java
>      static double[] getMedians(double a, double b, double c) {
Исправил

2024-11-22 12:43 UTC, Superbia101 commented on src/main/java/com/walking/intensive/chapter1/task5/Task5.java
> +        return new double[]{Math.acos((num[1] * num[1] + num[0] * num[0] - num[2] * num[2]) / (2 * num[1] * num[0])) * 180 / Math.PI,
Чуть оптимизировал

2024-11-22 15:48 UTC, PuccaGTS approved these changes
гуд

2024-11-22 15:48 UTC, closed without merging