Task1
KFalcon2022/intensive-tasks-2024 pull request #267
Opened 2024-11-21 07:42 UTC by IlgizS

2024-11-21 10:50 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task1/Task1.java
> +        } else if (lastDigit == 1 && preLastDigit != 1) {
после return не ставят else. Лбо будет выход из метода, либо метод продолжит выполняться и без else.

2024-11-21 10:50 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task1/Task1.java
> +        if (age < 0) {
просьба добавить ограничение по возрасту не более 127 лет.

2024-11-21 10:51 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task1/Task1.java
> +        } else if ((lastDigit == 2 || lastDigit == 3 || lastDigit == 4) && preLastDigit != 1) {
если использовать <= и >= логических условий будет меньше

2024-11-22 18:23 UTC, IlgizS commented on src/main/java/com/walking/intensive/chapter1/task1/Task1.java
> +        if (age < 0) {
В тестах возраст больше же

2024-11-22 19:17 UTC, EvgeneZhurov requested changes

2024-11-22 19:17 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task1/Task1.java
> +                ending = "года";
сделайте return и условия без вложенных if

2024-11-22 19:17 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task1/Task1.java
> +                ending = "год";
сделайте return и условия без вложенных if

2024-11-23 21:25 UTC, IlgizS commented on src/main/java/com/walking/intensive/chapter1/task1/Task1.java
> +                ending = "год";
Исправил

2024-11-24 08:58 UTC, EvgeneZhurov approved these changes

2024-11-24 08:58 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task1/Task1.java
лишняя пустая строка

2024-11-24 08:58 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task1/Task1.java
>          }
блоки кода лучше отделять пустыми строками, если это не начало или конец метода.

2024-11-24 08:59 UTC, closed without merging