Task1
KFalcon2022/intensive-tasks-2024 pull request #281
Opened 2024-11-21 16:30 UTC by stillwearit

2024-11-21 17:17 UTC, PuccaGTS requested changes
Давайте поправим

2024-11-21 17:17 UTC, PuccaGTS commented on src/main/java/com/walking/intensive/chapter1/task1/Task1.java
> +        }else{
Блок else тут не имеет никакого смысла, т.к. если верхнее условие не сработает, то код продолжит выполняться.

Поэтому после `}` можно на след строке сразу написать:
`return "Некорректный ввод";`

2024-11-21 17:17 UTC, PuccaGTS commented on src/main/java/com/walking/intensive/chapter1/task1/Task1.java
> +                case 124:
Не самое лучшее решение использовать switch case в этой задаче, код становится длинных и перегруженным.
Попробуйте написать эту программу используя if-else, а в качестве условий передавать например некоторые вычисления: Например `age % 10` - операция получения остатка от деления на 10 может дать вам последнюю цифру возраста, `age % 100` может дать вам последние две цифры возраста.

Подумайте и попробуйте исправить программу)

2024-11-21 17:17 UTC, PuccaGTS commented on src/main/java/com/walking/intensive/chapter1/task1/Task1.java
> +        if (age >= 0 && age < 128) {
почему условие ограниченно 128 лет?) а вдруг черепашка захочет узнать возраст, а ей 211 лет, а программа ей скажет "Некорректный возраст"

2024-11-21 17:48 UTC, stillwearit commented
Спасибо большое, теперь дошло! Не могла никак придумать, как учесть эльфов и черепашек :)

2024-11-22 15:32 UTC, PuccaGTS requested changes
Намного лучше, но есть маленькие замечания, давайте чутка доработаем)

2024-11-22 15:32 UTC, PuccaGTS commented on src/main/java/com/walking/intensive/chapter1/task1/Task1.java
> +                    return "Вам " + age + " лет";
куда-то код поплыл, воспользуйтесь комбинацией Ctrl+Alt+L для авто форматирования кода.

2024-11-22 15:32 UTC, PuccaGTS commented on src/main/java/com/walking/intensive/chapter1/task1/Task1.java
> +        return "Некорректный ввод";
Вот эту штуку можно унести в начала и сделать if (age < 0) то некорректный возраст, зачем нам проходить весь код, чтобы в конце узнать, что возраст изначально был некорректный?)

2024-11-22 15:32 UTC, PuccaGTS commented on src/main/java/com/walking/intensive/chapter1/task1/Task1.java
> +        } else if (age >= 0) {
Если некорректное условие уносим в начало, то тогда тут не нужно блока else if, а делаем просто return Вам .... лет.

2024-11-22 15:32 UTC, PuccaGTS commented on src/main/java/com/walking/intensive/chapter1/task1/Task1.java
> +        } else if (age % 10 == 2 || age % 10 == 3 || age % 10 == 4) {
Расчеты типа age % 10, age % 100 - можно унести в переменные, посчитать один раз  и потом только использовать:)

2024-11-22 16:13 UTC, stillwearit commented
Исправила!

2024-11-22 16:20 UTC, stillwearit commented on src/main/java/com/walking/intensive/chapter1/task1/Task1.java
> +        if (age < 0)
меня во втором задании просто за else после return отругали, поэтому я их тут тоже убрала и фигурные скобочки тоже решила убрать, потому что как я поняла, если после if одна строчка, они не нужны... может, я неправильно поняла... исправлю

2024-11-22 16:22 UTC, PuccaGTS commented on src/main/java/com/walking/intensive/chapter1/task1/Task1.java
> +        if (age < 0)
За скобочки ругать не будут)
В условных блоках они больше помогают, чем ухудшают читабельность кода)

2024-11-22 16:22 UTC, PuccaGTS commented on src/main/java/com/walking/intensive/chapter1/task1/Task1.java
> +        if (age < 0)
Верните скобочки на к условным блокам и закроем уже эту задачу))))

2024-11-22 16:25 UTC, PuccaGTS approved these changes
Спасибо! Зачет!

2024-11-22 16:25 UTC, closed without merging