Task2
KFalcon2022/intensive-tasks-2024 pull request #282
Opened 2024-11-21 18:21 UTC by katrienna

Сделана задача по определению квартиры в доме.

2024-11-21 20:26 UTC, KFalcon2022 requested changes

2024-11-21 20:26 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter1/task2/Task2.java
> +        if ((floorAmount <= 0 || floorAmount > 163) || (entranceAmount <= 0 || entranceAmount > 156) || flatNumber <= 0)
использование {} для тела if обязательно. Даже если тело однострочное

2024-11-21 20:26 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter1/task2/Task2.java
> +                    String.format("%d кв - %d подъезд, %d этаж, слева от лифта, влево", flatNumber, entranceNumber, floor);
строка не должна превышать 120 символов - считается, что именно столько помещается в один экран при стандартных настройках.

2024-11-21 20:26 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter1/task2/Task2.java
> +                    String.format("%d кв - %d подъезд, %d этаж, справа от лифта, вправо", flatNumber, entranceNumber, floor);
Зачем 4 раза собирать практически идентичную строку? Не логичнее ли в case получать именно значение, специфичное именно для этого кейса, а финальный сбор строки разместить ниже, не дублируя код?

И посмотри в сторону метода String#formatted(). Он чуть лаконичнее, чем тот, который ты используешь

2024-11-21 20:26 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter1/task2/Task2.java
> +        if ((floorAmount <= 0 || floorAmount > 163) || (entranceAmount <= 0 || entranceAmount > 156) || flatNumber <= 0)
Чем вызваны ограничения в 163 этажа и 156 подъездов? Из условия задачи они не следуют

2024-11-22 10:36 UTC, katrienna commented on src/main/java/com/walking/intensive/chapter1/task2/Task2.java
> +        if ((floorAmount <= 0 || floorAmount > 163) || (entranceAmount <= 0 || entranceAmount > 156) || flatNumber <= 0)
Ограничения - информация из гугла. Думала, что нужны, а то можно и дом до луны построить)

2024-11-24 11:27 UTC, KFalcon2022 requested changes

2024-11-24 11:27 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter1/task2/Task2.java
> +                    turns = "слева от лифта, влево";
лишний перенос. `case 1 -> turns = "слева от лифта, влево";` - вполне помещается в одну строку.

Кроме того, если ты используешь подобны синтаксис - можно возвращать return прямо из switch. Что-то вроде
```java
String turns = switch(flatNumberOnFloor) {
// кейсы и дефолт
};

2024-11-24 11:27 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter1/task2/Task2.java
> +                    turns = "справа от лифта, вправо";
default обязателен. Иначе если завтра кто-то изменит условие на `(flatNumber - (flatsInEntrance * (entranceNumber - 1))) % 5` - все будет работать, но работать будет некорректно. И отследить такое будет сложно. default, уведомляющий об ошибке, исправит эту проблему

2024-11-24 11:27 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter1/task2/Task2.java
> +
Стало сильно лучше, но надо чутка добить

2024-12-02 18:33 UTC, KFalcon2022 commented
ПР закрыт, т.к. не обновлялся более недели. При необходимости проверки - открывай новый

2024-12-02 18:33 UTC, closed without merging