Task2
KFalcon2022/intensive-tasks-2024 pull request #288
Opened 2024-11-21 20:46 UTC by stillwearit

Мне кажется, я слишком перегруженное решение придумала, но ничего лучше не вышло. Есть только предположение, что можно было задействовать boolean, но я не могу придумать как...

2024-11-21 20:51 UTC, EvgeneZhurov requested changes

2024-11-21 20:51 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task2/Task2.java
> +        } else if (flatNumber > 0 && flatNumber % 4 == 2) {
после return не ставится else

2024-11-21 20:51 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task2/Task2.java
>          return "Некорректные входные данные";
в самом начале метода сделайте валидацию данных, проверяя корректность ввода квартиры, чтобы она была положительной и не превышала количества квартир в доме и тогда flatNumber > 0 и тогда можно не дублировать это логическое условие везде в коде.

2024-11-21 20:51 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task2/Task2.java
> +        } else if (flatNumber > 0 && flatNumber % 4 == 3) {
у Вас ровно 4 валидных исхода, switch case лучше подходит

2024-11-22 12:43 UTC, stillwearit commented
Спасибо! Кажется, теперь поняла!

2024-11-22 19:34 UTC, EvgeneZhurov approved these changes

2024-11-22 19:35 UTC, closed without merging