Task 6
KFalcon2022/intensive-tasks-2024 pull request #293
Opened 2024-11-22 10:14 UTC by artem2301

2024-11-22 10:40 UTC, EvgeneZhurov requested changes

2024-11-22 10:40 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter2/task6/Task6.java
> +        List<Integer> multipliersM = getMultipliersOfNumber(m);
В данном интенсиве не принимаются задачи с использованием коллекций.

2024-11-22 10:55 UTC, artem2301 commented on src/main/java/com/walking/intensive/chapter2/task6/Task6.java
> +        List<Integer> multipliersM = getMultipliersOfNumber(m);
ясно, переделаю.

2024-11-24 18:35 UTC, EvgeneZhurov requested changes

2024-11-24 18:35 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter2/task6/Task6.java
>          if (m < 1 || n < 1) {
просьба выбросить валидацию из алгоритма

2024-11-24 18:35 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter2/task6/Task6.java
> +            return m;
это необходимо выбросить и поставить и поставить: если n ==0 вернуть m

2024-11-24 18:35 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter2/task6/Task6.java
> +        if (m > n) {
это необходимо выбросить

2024-11-24 18:35 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter2/task6/Task6.java
> +        return getGcdByEuclideanAlgorithm(m, n - m);
в качестве аргументов нужно подставить: n , m%n

2024-11-26 20:01 UTC, EvgeneZhurov approved these changes

2024-11-26 20:01 UTC, closed without merging