Task2
KFalcon2022/intensive-tasks-2024 pull request #294
Opened 2024-11-22 10:55 UTC by beamingrus

2024-11-22 11:14 UTC, EvgeneZhurov requested changes

2024-11-22 11:14 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task2/Task2.java
> +
в методе лучше ничего не печатать при отправке, потому что метод должен возвращать строку, а не печатать ее

2024-11-22 11:14 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task2/Task2.java
> +
while (flatNumber > wholeHouseCapacity) {
            flatCalcResult = "Такой квартиры не существует";
        }
        while (flatNumber < 1) {
            flatCalcResult = "Некорректные входные данные";
       Если логическое условие попадет в цикл, из него будет уже не выйти.

2024-11-22 11:18 UTC, beamingrus commented on src/main/java/com/walking/intensive/chapter1/task2/Task2.java
> +
почему-то return flatCalcResult; не срабатывал на отладке

2024-11-22 11:19 UTC, beamingrus commented on src/main/java/com/walking/intensive/chapter1/task2/Task2.java
> +
пардоньте, добавлю брейков

2024-11-22 19:31 UTC, EvgeneZhurov requested changes

2024-11-22 19:31 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task2/Task2.java
>              flatCalcResult = "Такой квартиры не существует";
Лучше сделать return

2024-11-22 19:31 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task2/Task2.java
>              flatCalcResult = "Некорректные входные данные";
Лучше сделать return

2024-11-22 19:31 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task2/Task2.java
> +        else
после else не хватает {}. Так принято в местном комьюнити.

2024-11-22 19:31 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task2/Task2.java
> +        if (flatNumber > wholeHouseCapacity) {
советую почитать про магическое число java

2024-12-04 09:36 UTC, EvgeneZhurov commented
Просьба открыть новый PR, если нужна проверка.

2024-12-04 09:36 UTC, closed without merging