Task4
KFalcon2022/intensive-tasks-2024 pull request #304
Opened 2024-11-22 17:49 UTC by ElowLiet

2024-11-23 00:06 UTC, KateKhodko requested changes

2024-11-23 00:06 UTC, KateKhodko commented on src/main/java/com/walking/intensive/chapter1/task4/Task4.java
> +            double specialCase1 = (-b - Math.sqrt(discriminantValue)) / (2 * a);
`specialCase1, specialCase2, specialCase3` - переменная не отражает его суть (сейчас это как специальный случай). Как вариант можно попробовать `singleRoot, firstsRoot, secondRoot`

2024-11-23 00:06 UTC, KateKhodko commented on src/main/java/com/walking/intensive/chapter1/task4/Task4.java
> +    private static double formatRoot(double root) {
А тут как раз мы можем не только ведь корень передать, а любое по смыслу значение

2024-11-23 06:39 UTC, ElowLiet commented
Исправил

2024-11-23 14:29 UTC, KateKhodko requested changes

2024-11-23 14:29 UTC, KateKhodko commented on src/main/java/com/walking/intensive/chapter1/task4/Task4.java
> +        else if (discriminantValue == 0) {
`} else if {`, не переносим `else` на новую строку, не забывай прожимать форматирование кода

2024-11-23 14:56 UTC, ElowLiet commented on src/main/java/com/walking/intensive/chapter1/task4/Task4.java
> +        else if (discriminantValue == 0) {
Поправил, однако, коммент пришлось удалить.

2024-11-24 00:27 UTC, KateKhodko commented on src/main/java/com/walking/intensive/chapter1/task4/Task4.java
> +        else if (discriminantValue == 0) {
Можно было написать `} else if (discriminantValue == 0) {     // Один корень`

2024-11-24 00:33 UTC, KateKhodko requested changes

2024-11-24 00:33 UTC, KateKhodko commented on src/main/java/com/walking/intensive/chapter1/task4/Task4.java
> +                    Math.max(firstRoot, secondRoot));
Не бойся переносить единственную скобочку на новую строчку, тут ведь дело читаемости, а не компактности кода

2024-11-24 00:33 UTC, KateKhodko commented on src/main/java/com/walking/intensive/chapter1/task4/Task4.java
> +                    return "Количество решений: 0.";
если `с != 0`, то мы все равно выведем кол-во решений 0, не нужен тут блок `else`

2024-11-24 06:24 UTC, ElowLiet commented on src/main/java/com/walking/intensive/chapter1/task4/Task4.java
> +                    return "Количество решений: 0.";
Да, действительно, else не нужен. Добавил коммент для else if и перенес скобочку на новую строчку.

2024-11-26 08:33 UTC, ElowLiet commented on src/main/java/com/walking/intensive/chapter1/task4/Task4.java
> +                if (c == 0) {
Исправил, разделил три условия на отдельные условные операторы. Прикрепляю скрин вывода к значениям (0,0,-10).
![Screen Shot 2024-11-26 at 11 32 33 AM](https://github.com/user-attachments/assets/a955b466-2592-4453-a172-04a0390af38f)

2024-11-26 18:53 UTC, KateKhodko approved these changes

2024-11-26 18:53 UTC, KateKhodko commented on src/main/java/com/walking/intensive/chapter1/task4/Task4.java
> +            return String.format("Количество решений: 2. Корни: %.1f;%.1f",
Строку тоже можно было бы сразу переносить на следующую строчку

2024-11-26 18:53 UTC, closed without merging