Task5
KFalcon2022/intensive-tasks-2024 pull request #307
Opened 2024-11-22 20:58 UTC by andreyv24

2024-11-23 00:14 UTC, KateKhodko commented
На будущее: добавляй имена коммитам, отражающие его краткую суть

2024-11-23 00:25 UTC, KateKhodko requested changes

2024-11-23 00:25 UTC, KateKhodko commented on src/main/java/com/walking/intensive/chapter1/task5/Task5.java
> +            return new double[]{};
1) Оформляем через [camelCase](https://www.techtarget.com/whatis/definition/CamelCase#:~:text=CamelCase%20is%20a%20way%20to,programming%20and%20computer%20naming%20conventions.)
2) Добавь разделение на логические блоки (например, где идут вычисления, где мы сохраняем в массив и т.д.)
3) `else` не нужен, т.к. если зайдет в блок с `if`, то он и так выйдет из метода
4) Валидацию можно сразу инвертировать (`!isTriangleExists`), не придется листать что будет после основного блока и придем к одному маленькому `if` блоку
5) `else` блок лучше выделять через фигурные

2024-11-23 00:25 UTC, KateKhodko commented on src/main/java/com/walking/intensive/chapter1/task5/Task5.java
> +}
Оставляем пустую строчку в конце файла

2024-11-23 00:25 UTC, KateKhodko commented on src/test/java/com/walking/intensive/chapter1/task5/Task5Test.java
> +        assertArrayEquals(new double[]{4.615384615384615, 5.0, 12.0}, getHeights(12, 13, 5), 1e-10);
Изменения делаем только в 1 файле, нигде больше

2024-11-23 00:25 UTC, KateKhodko commented on src/main/java/com/walking/intensive/chapter1/task5/Task5.java
> +    }
Как будто можно уйти от использования `if`

2024-11-23 15:21 UTC, andreyv24 commented on src/main/java/com/walking/intensive/chapter1/task5/Task5.java
> +}
ок.

2024-11-23 15:22 UTC, andreyv24 commented on src/test/java/com/walking/intensive/chapter1/task5/Task5Test.java
> +        assertArrayEquals(new double[]{4.615384615384615, 5.0, 12.0}, getHeights(12, 13, 5), 1e-10);
ок

2024-11-23 15:23 UTC, andreyv24 commented
ок

2024-11-23 15:54 UTC, andreyv24 commented on src/main/java/com/walking/intensive/chapter1/task5/Task5.java
> +            return new double[]{};
1. Ок.
2. А как это оформить, пробелами или как-то по другому, есть некие правила оформления, где можно их посмотреть ?
3. Понятно.
4. Не совсем понял: вначале код когда треугольник не существует, потом код если он существует и идут вычисления. Это имеется ввиду ? 
5. Ок

2024-11-23 15:55 UTC, andreyv24 commented
Спасибо за замечания!

2024-11-23 16:15 UTC, andreyv24 commented on src/main/java/com/walking/intensive/chapter1/task5/Task5.java
> +    }
Похоже да, ... скорректирую.

2024-11-24 00:37 UTC, KateKhodko commented on src/main/java/com/walking/intensive/chapter1/task5/Task5.java
> +            return new double[]{};
2. Пустыми строчками
3. Ты можешь сразу проверить, существует ли такой треугольник и если нет, то вернуть соотвествующее значение, иначе программа продолжит выполнение (то есть весь блок `if` сократиться до этой проверки)

2024-11-24 00:42 UTC, KateKhodko requested changes

2024-11-24 00:42 UTC, KateKhodko commented on src/main/java/com/walking/intensive/chapter1/task5/Task5.java
> +        }
Фигурные скобки тут не нужны

2024-11-24 00:42 UTC, KateKhodko commented on src/main/java/com/walking/intensive/chapter1/task5/Task5.java
> +        {
Фигурные скобки тут не нужны

2024-11-24 00:42 UTC, KateKhodko commented on src/main/java/com/walking/intensive/chapter1/task5/Task5.java
> +        {
Фигурные скобки тут не нужны

2024-11-24 00:42 UTC, KateKhodko commented on src/main/java/com/walking/intensive/chapter1/task5/Task5.java
> +        {
Фигурные скобки тут не нужны

2024-11-24 00:42 UTC, KateKhodko commented on src/main/java/com/walking/intensive/chapter1/task5/Task5.java
> +        {
Фигурные скобки тут не нужны

2024-11-24 00:42 UTC, KateKhodko commented on src/main/java/com/walking/intensive/chapter1/task5/Task5.java
> +        {
Фигурные скобки тут не нужны

2024-11-24 00:42 UTC, KateKhodko commented on src/main/java/com/walking/intensive/chapter1/task5/Task5.java
> +        {
Фигурные скобки тут не нужны

2024-11-24 00:42 UTC, KateKhodko commented on src/main/java/com/walking/intensive/chapter1/task5/Task5.java
> +        {
Фигурные скобки тут не нужны

2024-11-24 00:42 UTC, KateKhodko commented on src/test/java/com/walking/intensive/chapter1/task5/Task5Test.java
> +        assertArrayEquals(new double[]{4.615384615384615, 5.0, 12.0}, getHeights(12, 13, 5), 1e-10);
Не исправлено

2024-11-24 00:42 UTC, KateKhodko commented on src/main/java/com/walking/intensive/chapter1/task5/Task5.java
> +        }
Про логические блоки: вывод результата и работой с массивом можно тоже разделить:
```
            heights[0] = heightA;
            heights[1] = heightB;
            heights[2] = heightC;
            Arrays.sort(heights);
            
            return heights;
```

2024-11-25 21:11 UTC, andreyv24 commented on src/main/java/com/walking/intensive/chapter1/task5/Task5.java
> +        }
убрал

2024-11-25 21:11 UTC, andreyv24 commented on src/main/java/com/walking/intensive/chapter1/task5/Task5.java
> +        {
убрал

2024-11-25 21:11 UTC, andreyv24 commented on src/main/java/com/walking/intensive/chapter1/task5/Task5.java
> +        {
убрал

2024-11-25 21:11 UTC, andreyv24 commented on src/main/java/com/walking/intensive/chapter1/task5/Task5.java
> +        {
убрал

2024-11-25 21:11 UTC, andreyv24 commented on src/main/java/com/walking/intensive/chapter1/task5/Task5.java
> +        {
убрал

2024-11-25 21:12 UTC, andreyv24 commented on src/main/java/com/walking/intensive/chapter1/task5/Task5.java
> +        {
убрал

2024-11-25 21:13 UTC, andreyv24 commented on src/main/java/com/walking/intensive/chapter1/task5/Task5.java
> +        }
Разделил везде.

2024-11-25 21:15 UTC, andreyv24 commented on src/test/java/com/walking/intensive/chapter1/task5/Task5Test.java
> +        assertArrayEquals(new double[]{4.615384615384615, 5.0, 12.0}, getHeights(12, 13, 5), 1e-10);
Удалил хвост, вместо 4.615384615384615 теперь 4.61.

2024-11-25 23:43 UTC, KateKhodko requested changes

2024-11-25 23:43 UTC, KateKhodko commented on src/test/java/com/walking/intensive/chapter1/task5/Task5Test.java
> +        assertArrayEquals(new double[]{4.61, 5.0, 12.0}, getHeights(12, 13, 5), 1e-10);
просто удали эту строчку и подлей без нее, видимо случайно продублировалась с 
`assertArrayEquals(new double[]{4.615384615384615, 5.0, 12.0}, getHeights(12, 13, 5), 1e-10);`

2024-11-25 23:43 UTC, KateKhodko commented on src/main/java/com/walking/intensive/chapter1/task5/Task5.java
> +        double[] heights = new double[3];
```
double[] heights = new double[3];
if (!ifTriangleExist(a, b, c)) {
    return new double[]{};
}

double square = getTriangleSquare(a, b, c);
double heightA = (2 * square) / a;
double heightB = (2 * square) / b;
double heightC = (2 * square) / c;

heights[0] = heightA;
heights[1] = heightB;
heights[2] = heightC;
Arrays.sort(heights);

return heights;
```

2024-11-25 23:43 UTC, KateKhodko commented on src/main/java/com/walking/intensive/chapter1/task5/Task5.java
> +        double[] heights = new double[3];
if всегда со скобками, блоки внутри методов не пишем, отделяем пустыми строками

2024-11-25 23:43 UTC, KateKhodko commented on src/main/java/com/walking/intensive/chapter1/task5/Task5.java
> +        double[] heights = new double[3];
Везде по коду это глянь и поправь

2024-11-26 00:12 UTC, andreyv24 commented on src/test/java/com/walking/intensive/chapter1/task5/Task5Test.java
> +        assertArrayEquals(new double[]{4.61, 5.0, 12.0}, getHeights(12, 13, 5), 1e-10);
ок, удалю.

2024-11-26 00:23 UTC, andreyv24 commented on src/main/java/com/walking/intensive/chapter1/task5/Task5.java
> +        double[] heights = new double[3];
> if всегда со скобками
Здесь не понял. Ранее же было замечание, что скобки нужно убрать ? 
![2024-11-26_03-14-45](https://github.com/user-attachments/assets/4d91f95d-6fd0-4dd2-b976-4a9ac8236800)

> блоки внутри методов не пишем, отделяем пустыми строками
Вот это тоже не понял.

2024-12-03 16:35 UTC, andreyv24 commented
Внёс корректировку по замечаниям по всему тексту кода.

2024-12-04 21:34 UTC, KateKhodko approved these changes

2024-12-04 21:35 UTC, closed without merging