Task5
KFalcon2022/intensive-tasks-2024 pull request #312
Opened 2024-11-23 07:03 UTC by Neverhoodof

2024-11-23 08:03 UTC, Zawadskiy requested changes

2024-11-23 09:08 UTC, Neverhoodof commented on src/main/java/com/walking/intensive/chapter1/task5/Task5.java
>      public static void main(String[] args) {
Не понимаю как провести Checkstyle

2024-11-23 09:11 UTC, Neverhoodof commented on src/main/java/com/walking/intensive/chapter1/task5/Task5.java
>      public static void main(String[] args) {
Хм, нашел вроде

2024-11-23 21:51 UTC, Zawadskiy requested changes

2024-11-23 21:51 UTC, Zawadskiy commented on src/main/java/com/walking/intensive/chapter1/task5/Task5.java
> +        return (a * b * c) / (4 * Math.sqrt(semiPerimeter * (semiPerimeter - a) * (semiPerimeter - b) * (semiPerimeter - c)));
Error: eckstyle] [ERROR] /home/runner/work/intensive-tasks-2024/intensive-tasks-2024/src/main/java/com/walking/intensive/chapter1/task5/Task5.java:120: Line is longer than 120 characters (found 126). [LineLength]

2024-11-24 06:01 UTC, Zawadskiy approved these changes

2024-11-24 06:01 UTC, Zawadskiy commented on src/main/java/com/walking/intensive/chapter1/task5/Task5.java
> +
> Task :checkstyleMain
Error: eckstyle] [ERROR] /home/runner/work/intensive-tasks-2024/intensive-tasks-2024/src/main/java/com/walking/intensive/chapter1/task5/Task5.java:117: Line has trailing spaces. [RegexpSingleline]

2024-11-24 06:01 UTC, closed without merging