Task1
KFalcon2022/intensive-tasks-2024 pull request #323
Opened 2024-11-23 16:36 UTC by dspnstn

Здравствуйте. 
Проверил с разными значениями в методе main() - всё правильно.
При запуске тестов почему-то проходят только первые три (с "Некорректным вводом"), остальные проваливаются. 
Что я упускаю?
Спасибо.

2024-11-24 01:07 UTC, KateKhodko commented
Проблема в том, что вы используете иную кодировку (символы для сохранения в `ageResult` используются латинские). Необходимо поменять кодировку на `UTF-8` и тогда тесты пройдут

2024-11-24 01:07 UTC, KateKhodko requested changes

2024-11-25 11:48 UTC, dspnstn commented
> Проблема в том, что вы используете иную кодировку (символы для сохранения в `ageResult` используются латинские). Необходимо поменять кодировку на `UTF-8` и тогда тесты пройдут

Поменял на UTF-8 и в IDEA (несколькими способами), и в Windows. В нижнем правом углу IDEA и на вкладке класса, и на вкладке тестов показывает File Encoding UTF-8.
Почему-то всё равно проваливаются все те же тесты. Что ещё можно попробовать?

2024-11-25 23:12 UTC, KateKhodko requested changes

2024-11-25 23:12 UTC, KateKhodko commented on src/main/java/com/walking/intensive/chapter1/task1/Task1.java
> +        String ageResult = "Bам " + age;
Вот тут в слове "Bам "  буква В как будто не русккая, попробуйте на русскую исправить)

2024-11-26 08:27 UTC, dspnstn commented on src/main/java/com/walking/intensive/chapter1/task1/Task1.java
> +        String ageResult = "Bам " + age;
Переправил. Сработало. Спасибо вам большое! Теперь буду на такое обращать внимание)
Из строки 24 условие равенства нулю пришлось убрать, чтобы проходил тест of("Вам 0 лет", 0) (проходит за счёт else в последнем блоке if),

2024-11-26 18:57 UTC, KateKhodko approved these changes

2024-11-26 18:57 UTC, KateKhodko commented on src/main/java/com/walking/intensive/chapter1/task1/Task1.java
> +        return ageResult;
Между `}` и `return` можно вставить пустую строчку, чтобы разделять логику и итог

2024-11-26 18:57 UTC, closed without merging