Task2
KFalcon2022/intensive-tasks-2024 pull request #325
Opened 2024-11-23 17:56 UTC by AndyRaw007

Тесты все проходят, но думается мне как-то изящнее можно было вывод информации в строку организовать

2024-11-24 01:21 UTC, KateKhodko requested changes

2024-11-24 01:21 UTC, KateKhodko commented on src/main/java/com/walking/intensive/chapter1/task2/Task2.java
> +}
Пустую строчку в конце файла добавляем

2024-11-24 01:21 UTC, KateKhodko commented on src/main/java/com/walking/intensive/chapter1/task2/Task2.java
> +                return flatNumber + " кв - " + numberEnterance + " подъезд, " + level + " этаж, справа от лифта, вправо";
Длинные строки, как вариант можно заранее формировать предложения будущие и далее подставлять нужные значения через `String.format`

2024-11-24 01:21 UTC, KateKhodko commented on src/main/java/com/walking/intensive/chapter1/task2/Task2.java
> +@SuppressWarnings("checkstyle:WhitespaceAround")
А зачем?

2024-11-24 07:49 UTC, AndyRaw007 commented on src/main/java/com/walking/intensive/chapter1/task2/Task2.java
> +}
Добавил, прочитал зачем)

2024-11-24 08:11 UTC, AndyRaw007 commented on src/main/java/com/walking/intensive/chapter1/task2/Task2.java
> +                return flatNumber + " кв - " + numberEnterance + " подъезд, " + level + " этаж, справа от лифта, вправо";
Переделал через String.format

2024-11-24 08:11 UTC, AndyRaw007 commented on src/main/java/com/walking/intensive/chapter1/task2/Task2.java
> +@SuppressWarnings("checkstyle:WhitespaceAround")
Случайно добавилось, убрал

2024-11-25 23:21 UTC, KateKhodko requested changes

2024-11-25 23:21 UTC, KateKhodko commented on src/main/java/com/walking/intensive/chapter1/task2/Task2.java
> +        string4 = "справа от лифта, влево";
Не объявляем переменные через запятую, если можем сразу проинициализировать, то инициализируем сразу

2024-11-25 23:21 UTC, KateKhodko commented on src/main/java/com/walking/intensive/chapter1/task2/Task2.java
> +                return String.format("%d кв - %d подъезд, %d этаж, " + string1, flatNumber, numberEnterance, level);
Как будто `String.format(...)` можно выполнить один раз в конце, а тут просто определять положениие квартиры на этаже

2024-11-26 19:06 UTC, KateKhodko approved these changes

2024-11-26 19:06 UTC, KateKhodko commented on src/main/java/com/walking/intensive/chapter1/task2/Task2.java
> +        var direction = "default";
На будущее: придерживаемся одного стиля объявления переменных, не мешаем объявление через val/var и через конкретные типы

2024-11-26 19:06 UTC, KateKhodko commented on src/main/java/com/walking/intensive/chapter1/task2/Task2.java
> +        return String.format("%d кв - %d подъезд, %d этаж, " + direction, flatNumber, numberEnterance, level);
На будущее: стараемся выделять код "логически". Например:
```
switch (flatNumber % 4) {
            case 0:
                direction = string1;
                break;
            case 1:
                direction = string2;
                break;
            case 2:
                direction = string3;
                break;
            default:
                direction = string4;
        }
        
        return String.format("%d кв - %d подъезд, %d этаж, " + direction, flatNumber, numberEnterance, level);
```
Здесь отделили switch от return, т.к. первый блок выполняет еще логику, а второй - возвращение результата
Второй пример:
```
if (flatNumber <= 0 || entranceAmount <= 0 || flatNumber <= 0) {
            return "Некорректные входные данные";
        }
        if (floorAmount * entranceAmount * 4 < flatNumber) {
            return "Такой квартиры не существует";
        }

        int oneEnterance = floorAmount * 4; // квартир в одном подъезде
        int numberEnterance = flatNumber / oneEnterance; // подъезд
        if (flatNumber % oneEnterance > 0) {
            numberEnterance = numberEnterance + 1;
        }
```
Здесь разделили проверку на корректность входных данных от основной логики

2024-11-26 19:07 UTC, closed without merging