Task3
KFalcon2022/intensive-tasks-2024 pull request #331
Opened 2024-11-23 21:34 UTC by rtsnik

Решение Task3. Коммит №1.

2024-11-24 10:05 UTC, EvgeneZhurov requested changes

2024-11-24 10:05 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task3/Task3.java
> +        if(year < 1600) {
Логические условия можно объединять используя || или &&. Попробуйте создать одно условие и вернуть и тогда if не понадобится.

2024-11-24 22:31 UTC, rtsnik commented on src/main/java/com/walking/intensive/chapter1/task3/Task3.java
> +        if(year < 1600) {
Реализовал в одно условие.

2024-11-25 08:34 UTC, EvgeneZhurov requested changes

2024-11-25 08:34 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task3/Task3.java
> +        return !(year < 1600) && ((year % 100 != 0 || year % 400 == 0) && year % 4 == 0);
если развернуть условие на противоположное и убрать !

2024-11-26 19:05 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task3/Task3.java
> +        return year >= 1600 && ((year % 100 != 0 || year % 400 == 0) && year % 4 == 0);
Есть лишние ненужные скобки

2024-11-26 19:20 UTC, closed without merging