Task 6 is ready
KFalcon2022/intensive-tasks-2024 pull request #332
Opened 2024-11-23 22:13 UTC by iamlonelyplanet

2024-11-24 12:01 UTC, EvgeneZhurov commented
Просьба убрать " is ready"  из названия задачи

2024-11-24 12:16 UTC, EvgeneZhurov requested changes

2024-11-24 12:16 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter2/task6/Task6.java
> +        if (isWrong(m, n)) {
просьба выкинуть валидацию из метода.

2024-11-24 12:16 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter2/task6/Task6.java
> +        while (largestNumber != lowestNumber) {
через рекурсию пожалуйста.

2024-11-24 12:19 UTC, iamlonelyplanet commented on src/main/java/com/walking/intensive/chapter2/task6/Task6.java
> +        while (largestNumber != lowestNumber) {
С чего бы через рекурсию? Не было такого условия в задаче.

2024-11-24 12:25 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter2/task6/Task6.java
> +        while (largestNumber != lowestNumber) {
вот и появилось :)

2024-11-26 19:55 UTC, EvgeneZhurov requested changes

2024-11-26 19:55 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter2/task6/Task6.java
> +            return -1;
просьба выкинуть валидацию

2024-11-26 19:55 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter2/task6/Task6.java
> +        while (lowestNumber != largestNumber) {
Просьба выкинуть весь код из метода.
Условие выхода из рекурсии: Если n = 0, то вернуть m
вернуть вызванный результат метода getGcdByEuclideanAlgorithm с параметрами (n ; m%n)

2024-12-05 19:46 UTC, EvgeneZhurov approved these changes

2024-12-05 19:46 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter2/task6/Task6.java
> +        return m * n / getGcd(m, n); // Если знать НОД (а мы знаем!), то НОК = mn/НОД
Если взять два числа больше миллиона, то их произведение будет больше максимально возможного int и метод отработает некорректно. Лучше сначала одно из них поделить и потом домножить на другое.

2024-12-05 19:46 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter2/task6/Task6.java
> +        return (n % i == 0);
можно без скобок

2024-12-05 19:46 UTC, closed without merging