Task1
KFalcon2022/intensive-tasks-2024 pull request #34
Opened 2024-11-17 08:30 UTC by alonecat13

При компиляции в консоли не отображается кириллица. Как можно починить?
![image](https://github.com/user-attachments/assets/46dd0260-d159-4124-9385-5a9e97bd221b)

2024-11-17 08:38 UTC, EvgeneZhurov requested changes

2024-11-17 15:43 UTC, EvgeneZhurov requested changes

2024-11-17 15:43 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task1/Task1.java
>          } else if (age < 0 || age > 120) {
Валидацию лучше делать в самом начале метода.

2024-11-17 15:43 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task1/Task1.java
> +        } else if ((age % 10 >= 2 && age % 10 <= 4) && age < 120) {
после return не ставится else, либо будет return, либо метод продолжит исполняться и  без else. Просьба поправить везде в коде.

2024-11-17 15:43 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task1/Task1.java
>              return "Вам " + age + " года goda";
слово goda лишнее

2024-11-17 15:43 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task1/Task1.java
>          System.out.println(getAgeString(age));
если в качестве аргумента ввести число 12, то метод вернет: Вам 12 года goda
Ожидалось: Вам 12 лет

2024-11-17 18:32 UTC, alonecat13 commented on src/main/java/com/walking/intensive/chapter1/task1/Task1.java
>          } else if (age < 0 || age > 120) {
исправил, перенёс в начало метода.

2024-11-17 18:33 UTC, alonecat13 commented on src/main/java/com/walking/intensive/chapter1/task1/Task1.java
> +        } else if ((age % 10 >= 2 && age % 10 <= 4) && age < 120) {
исправил.

2024-11-17 18:33 UTC, alonecat13 commented on src/main/java/com/walking/intensive/chapter1/task1/Task1.java
>          System.out.println(getAgeString(age));
исправил.

2024-11-17 18:33 UTC, alonecat13 commented on src/main/java/com/walking/intensive/chapter1/task1/Task1.java
>              return "Вам " + age + " года goda";
убрал лишнее.

2024-11-17 18:41 UTC, EvgeneZhurov requested changes

2024-11-17 18:41 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task1/Task1.java
>          } else {
после return не ставится else. Либо метод вернет строку, либо и без else продолжить исполняться.

2024-11-17 18:41 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task1/Task1.java
> +        if ((age % 10 == 1) && age != 11 && age != 111) {
age != 11 && age != 111  можно короче: остаток от деления на 100 не равен 11

2024-11-17 18:41 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task1/Task1.java
> +        if ((age % 10 >= 2 && age % 10 <= 4) && (age <= 12 && age >= 14)) {
если в качестве аргумента ввести 102. результат: Вам 102 лет

2024-11-17 18:41 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task1/Task1.java
> +        if ((age % 10 >= 2 && age % 10 <= 4) && (age <= 12 && age >= 14)) {
логическое условие составлено неверно.

2024-11-17 18:45 UTC, alonecat13 commented on src/main/java/com/walking/intensive/chapter1/task1/Task1.java
>          } else {
а elseif можно? если нет, то единственное решение я вижу только с вводом переменной и её return в конце.
ЧЯДНТ?

2024-11-17 18:52 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task1/Task1.java
>          } else {
не понял, если честно ничего. Суть проста. После return не имеет ставить else. потому что код и без него продолжит исполняться, если не выйдет через return.

2024-11-17 18:57 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task1/Task1.java
>          } else {
Не переживайте, просто отрабатывайте замечания, если есть вопросы пишите в чат.

2024-11-17 19:00 UTC, alonecat13 commented on src/main/java/com/walking/intensive/chapter1/task1/Task1.java
>          } else {
сегодня, 10 часов назад был коммент:
[EvgeneZhurov](https://github.com/EvgeneZhurov) [10 hours ago](https://github.com/KFalcon2022/intensive-tasks-2024/pull/34#discussion_r1845332042)
Можно не вводить строки, а делать return, просьба поправить.

Поскольку полного понимания return у меня нет, изначально я делал возврат значения из функции через переменную (т.е. после всех if-elseif-else шёл return). Или я неправильно прочитал и "не вводить строки" это относилось к конвертации int->String? (convertAgeToString.endsWith("1"))

2024-11-17 19:05 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task1/Task1.java
>          } else {
имелось ввиду, что у одного метода может быть много return с разными возвращаемыми значениями.

2024-11-18 18:02 UTC, alonecat13 commented on src/main/java/com/walking/intensive/chapter1/task1/Task1.java
>          } else {
fixed

2024-11-18 18:02 UTC, alonecat13 commented on src/main/java/com/walking/intensive/chapter1/task1/Task1.java
> +        if ((age % 10 >= 2 && age % 10 <= 4) && (age <= 12 && age >= 14)) {
fixed

2024-11-18 18:03 UTC, alonecat13 commented on src/main/java/com/walking/intensive/chapter1/task1/Task1.java
> +        if ((age % 10 >= 2 && age % 10 <= 4) && (age <= 12 && age >= 14)) {
fixed

2024-11-18 18:03 UTC, alonecat13 commented on src/main/java/com/walking/intensive/chapter1/task1/Task1.java
> +        if ((age % 10 == 1) && age != 11 && age != 111) {
fixed

2024-11-19 18:54 UTC, alonecat13 commented on src/main/java/com/walking/intensive/chapter1/task1/Task1.java
> +        } else if ((age == 1 || age % 10 == 1) && (age % 100 != 11)) {
fixed

2024-11-19 19:12 UTC, alonecat13 commented on src/main/java/com/walking/intensive/chapter1/task1/Task1.java
> +        if ((age == 1 || age % 10 == 1) && (age % 100 != 11)) {
чувствую себя бесконечно тупым, но поправил =)

2024-11-19 19:18 UTC, EvgeneZhurov approved these changes
принято

2024-11-19 19:18 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task1/Task1.java
> +        if ((age >= 12 && age <= 14) || (age >= 112 && age <= 114)) {
между блоками кода лучше ставить пустые строки, если это не начало или конец метода.

2024-11-19 19:18 UTC, closed without merging