Task6
KFalcon2022/intensive-tasks-2024 pull request #350
Opened 2024-11-24 15:23 UTC by ElowLiet

2024-11-24 19:08 UTC, EvgeneZhurov requested changes

2024-11-24 19:08 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter2/task6/Task6.java
> +        if (isValidInput(m, n)) {
просьба выкинуть валидацию из метода

2024-11-24 19:08 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter2/task6/Task6.java
> +        while (n != 0) {
просьба сделать через рекурсию

2024-11-24 19:08 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter2/task6/Task6.java
> +        }
лучше отделять блоки кода пустыми строками с обеих сторон, если это не начало или конец метода.

2024-11-24 22:16 UTC, ElowLiet commented
Добрый вечер, исправил. Метод рекурсии для случая  _m = -1_ и _n = 0_ выводит ответ -1, точно такой же как и был, однако Test считает его за ошибку (прикрепил скрины-ссылки вывода результата старого и нового кодов).

![Screen Shot 2024-11-25 at 1 08 59 AM](https://github.com/user-attachments/assets/a2a1f5a8-2c21-4b66-9a8c-fdcec736c3cd)
![Screen Shot 2024-11-25 at 1 09 24 AM](https://github.com/user-attachments/assets/bfdbdcfd-6cce-4cc1-b5ea-84718dc9c11c)

2024-11-26 19:36 UTC, EvgeneZhurov approved these changes

2024-11-26 19:36 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter2/task6/Task6.java
> +            if (m % i == 0 && n % i == 0) {
как раз здесь не нужна пустая строка. Она нужна перед return

2024-11-26 19:36 UTC, closed without merging

2024-11-26 20:43 UTC, ElowLiet commented on src/main/java/com/walking/intensive/chapter2/task6/Task6.java
> +            if (m % i == 0 && n % i == 0) {
поправил, запомнил 👍