task7
KFalcon2022/intensive-tasks-2024 pull request #356
Opened 2024-11-24 17:37 UTC by Rewertkin

2024-11-25 19:36 UTC, KFalcon2022 requested changes

2024-11-25 19:36 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter2/task7/Task7.java
> +        for (int i = 1; i <= n / 2; i++) {
можно оптимизировать, считая до sqrt(n), только придется чуть иначе делители учитывать. Фактически, получая целый делитель ты в частном получаешь второй делитель для того же делимого (если поделилось нацело). Т.е. можно уменьшить число операций в цикле

2024-11-25 19:36 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter2/task7/Task7.java
> +            int sumDivisorsI = getSumDivisor(i); //найдем сумму множителей
лишняя буква в названии переменной. Даже если это была римская 1

2024-11-25 19:36 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter2/task7/Task7.java
> +            if (sumDivisorsI > i && sumDivisorsI < n) { //число большее из пары и меньше N
Лишние комменты лишь затрудняют читабельность кода. Их стоит использовать для действительно запутанных алгоритмов, здесь же все достаточно прозрачно

2024-11-25 19:36 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter2/task7/Task7.java
> +    static int getSumDivisor(int n) {
getDivisorSum звучит естественнее

2024-11-25 19:36 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter2/task7/Task7.java
> +    static int getSumDivisor(int n) {
в твоем варианте не хватает of. но с ним будет длиннее без явной выгоды

2024-11-26 14:09 UTC, Rewertkin commented on src/main/java/com/walking/intensive/chapter2/task7/Task7.java
> +        for (int i = 1; i <= n / 2; i++) {
изменил на корень

2024-11-26 14:09 UTC, Rewertkin commented on src/main/java/com/walking/intensive/chapter2/task7/Task7.java
> +            if (sumDivisorsI > i && sumDivisorsI < n) { //число большее из пары и меньше N
удалил очевидные вещи

2024-11-26 14:10 UTC, Rewertkin commented on src/main/java/com/walking/intensive/chapter2/task7/Task7.java
> +    static int getSumDivisor(int n) {
скорректировал

2024-11-27 20:17 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter2/task7/Task7.java
> +            int sumDivisorsI = getSumDivisor(i); //найдем сумму множителей
Не исправлено

2024-11-27 20:18 UTC, KFalcon2022 approved these changes

2024-11-27 20:18 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter2/task7/Task7.java
> +                if (i != n / i && n != n / i) {
вторым условием единицу исключал?) можно было ее просто учесть вне цикла:)

2024-11-27 20:18 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter2/task7/Task7.java
> +    }
оставшиеся замечания не считаю значительными. Задача зачтена

2024-11-27 22:34 UTC, Rewertkin commented on src/main/java/com/walking/intensive/chapter2/task7/Task7.java
> +            int sumDivisorsI = getSumDivisor(i); //найдем сумму множителей
исправил

2024-11-27 22:50 UTC, Rewertkin commented on src/main/java/com/walking/intensive/chapter2/task7/Task7.java
> +                if (i != n / i && n != n / i) {
Хм, если честно не вижу как можно эффективно ее исключить из цикла.
Если в стр 52 i присваивать 2, но не будет сходиться sum из строки 54.

2024-11-27 22:52 UTC, Rewertkin commented on src/main/java/com/walking/intensive/chapter2/task7/Task7.java
> +    }
т.к. задача не была закрыта, поправил переменную

2024-11-28 20:03 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter2/task7/Task7.java
> +                if (i != n / i && n != n / i) {
ну так и сумму можно изначально инициировать единицей. Вот что-что, а единица в делителях любого натурального числа присутствует всегда:)

2024-11-28 20:04 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter2/task7/Task7.java
> +    }
это я просто закрыть забыл, видимо)

2024-11-28 20:04 UTC, closed without merging