task8
KFalcon2022/intensive-tasks-2024 pull request #360
Opened 2024-11-24 18:33 UTC by Rewertkin

2024-11-25 19:39 UTC, KFalcon2022 requested changes

2024-11-25 19:39 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter2/task8/Task8.java
> +            if (checkHappyTicket(i)) {
чаще булеан-методы имеют с is

2024-11-25 19:39 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter2/task8/Task8.java
> +                totalHappyTicket += 1;
totalHappyTicket++?

2024-11-25 19:39 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter2/task8/Task8.java
> +        return (double) totalHappyTicket / (double) totalTickets;
достаточно приведения одного из чисел, оба - избыточно

2024-11-25 19:39 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter2/task8/Task8.java
> +            int number = n % 10;
неочевидное название. n - и так сокращение от number. Можно зедсь что-то вроде currentNumber придумать

2024-11-25 19:39 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter2/task8/Task8.java
> +        return sumRightNum == sumLeftNum;
замечания мелкие, но многовато. Давай добьем

2024-11-26 13:03 UTC, Rewertkin commented on src/main/java/com/walking/intensive/chapter2/task8/Task8.java
> +            if (checkHappyTicket(i)) {
исправил

2024-11-26 13:03 UTC, Rewertkin commented on src/main/java/com/walking/intensive/chapter2/task8/Task8.java
> +                totalHappyTicket += 1;
Изменил

2024-11-26 13:19 UTC, Rewertkin commented on src/main/java/com/walking/intensive/chapter2/task8/Task8.java
> +        return (double) totalHappyTicket / (double) totalTickets;
исправил

2024-11-26 13:20 UTC, Rewertkin commented on src/main/java/com/walking/intensive/chapter2/task8/Task8.java
> +            int number = n % 10;
исправил

2024-11-27 20:15 UTC, KFalcon2022 approved these changes

2024-11-27 20:15 UTC, closed without merging