Task6
KFalcon2022/intensive-tasks-2024 pull request #363
Opened 2024-11-24 19:40 UTC by michael-altf4

2024-11-25 22:20 UTC, Zawadskiy requested changes

2024-11-25 22:20 UTC, Zawadskiy commented on src/main/java/com/walking/intensive/chapter2/task6/Task6.java
>      static int getLcm(int m, int n) {
> Task :test FAILED

Task6Test > getNodByEuclideanAlgorithmTest(int, int, int) > [6] -1, 0, 20 FAILED
    org.opentest4j.AssertionFailedError at Task6Test.java:[33](https://github.com/KFalcon2022/intensive-tasks-2024/actions/runs/11999026446/job/33506314384?pr=363#step:6:34)

24 tests completed, 1 failed

2024-11-25 22:21 UTC, Zawadskiy requested changes

2024-11-25 22:21 UTC, Zawadskiy commented on src/main/java/com/walking/intensive/chapter2/task6/Task6.java
>      static int getGcdByEuclideanAlgorithm(int m, int n) {
> Task :test FAILED

Task6Test > getNodByEuclideanAlgorithmTest(int, int, int) > [6] -1, 0, 20 FAILED
    org.opentest4j.AssertionFailedError at Task6Test.java:[33](https://github.com/KFalcon2022/intensive-tasks-2024/actions/runs/11999026446/job/33506314384?pr=363#step:6:34)

24 tests completed, 1 failed

2024-11-26 03:11 UTC, Zawadskiy requested changes

2024-11-26 03:11 UTC, Zawadskiy commented on src/main/java/com/walking/intensive/chapter2/task6/Task6.java
> +        for (int i = smallerNumber; i <= lcm; i++) {
обіічніій перебор) можно и лучше

2024-11-26 03:11 UTC, Zawadskiy commented on src/main/java/com/walking/intensive/chapter2/task6/Task6.java
> +                break;
break в if не лучший вариант

2024-11-26 08:38 UTC, michael-altf4 commented on src/main/java/com/walking/intensive/chapter2/task6/Task6.java
>      static int getGcdByEuclideanAlgorithm(int m, int n) {
Здравствуйте! Вижу тест с 0 на входе не прошел. Но алгоритм с рекурсией предполагает 0 для его корректного завершения. Какие подсказки?

2024-11-27 04:18 UTC, Zawadskiy requested changes

2024-11-27 04:18 UTC, Zawadskiy commented on src/main/java/com/walking/intensive/chapter2/task6/Task6.java
>      static int getGcdByEuclideanAlgorithm(int m, int n) {
Валидация в помощь

2024-11-27 04:18 UTC, Zawadskiy commented on src/main/java/com/walking/intensive/chapter2/task6/Task6.java
> +        if (m < 1 || n < 1) {
єто можно в отдельніій метод віінести

2024-11-27 04:18 UTC, Zawadskiy commented on src/main/java/com/walking/intensive/chapter2/task6/Task6.java
> +        while (true) {
перебор) не саміій єффективніій алгоритм)

2024-11-27 04:18 UTC, Zawadskiy commented on src/main/java/com/walking/intensive/chapter2/task6/Task6.java
> +                break;
break в for цикле идея плохая)

2024-11-28 01:24 UTC, Zawadskiy commented on src/main/java/com/walking/intensive/chapter2/task6/Task6.java
> +    static boolean notValid(int m, int n) {
isValid - if(!isValid) вот так обіічно назіівают

2024-11-28 01:25 UTC, closed without merging