Chapter 1, Task 4
KFalcon2022/intensive-tasks-2024 pull request #368
Opened 2024-11-24 21:22 UTC by Allcash116

2024-11-25 22:48 UTC, Zawadskiy requested changes

2024-11-25 22:48 UTC, Zawadskiy commented on src/main/java/com/walking/intensive/chapter1/task4/Task4.java
> +        double x1, x2;
Error: eckstyle] [ERROR] /home/runner/work/intensive-tasks-2024/intensive-tasks-2024/src/main/java/com/walking/intensive/chapter1/task4/Task4.java:37:9: Each variable declaration must be in its own statement. [MultipleVariableDeclarations]

2024-11-25 22:48 UTC, Zawadskiy commented on src/main/java/com/walking/intensive/chapter1/task4/Task4.java
> +        double D = (b * b) - (4 * a * c);
Error: eckstyle] [ERROR] /home/runner/work/intensive-tasks-2024/intensive-tasks-2024/src/main/java/com/walking/intensive/chapter1/task4/Task4.java:38:16: Name 'D' must match pattern '^[a-z][a-zA-Z0-9]*$'. [LocalVariableName]

2024-11-25 22:48 UTC, Zawadskiy commented on src/main/java/com/walking/intensive/chapter1/task4/Task4.java
> +            x1 = 0;
Зачем здесь єто?

2024-11-25 22:48 UTC, Zawadskiy commented on src/main/java/com/walking/intensive/chapter1/task4/Task4.java
> +            x1 = -(c / b);
И вот єто тоже. переменная просто лишняя.

2024-11-25 22:48 UTC, Zawadskiy commented on src/main/java/com/walking/intensive/chapter1/task4/Task4.java
> +        } else if (D == 0) {
Усли в блоке if есть return тогда else не пишем, обіічного if достаточно.

2024-11-25 22:48 UTC, Zawadskiy commented on src/main/java/com/walking/intensive/chapter1/task4/Task4.java
> +            x2 = (-b - Math.sqrt(D)) / (2 * a);
Пустііе строки где?

2024-11-25 22:48 UTC, Zawadskiy commented on src/main/java/com/walking/intensive/chapter1/task4/Task4.java
> +        return null;
Что єто за ужас?)

2024-11-25 22:50 UTC, Zawadskiy requested changes

2024-11-25 22:50 UTC, Zawadskiy commented on src/main/java/com/walking/intensive/chapter1/task4/Task4.java
>      static String solveEquation(double a, double b, double c) {
p.s. Делай нормальнііе названия pr. Мне лень их менять.

2024-11-27 03:49 UTC, Zawadskiy requested changes

2024-11-27 03:49 UTC, Zawadskiy commented on build.gradle
> +        languageVersion = JavaLanguageVersion.of(23)
Что єто здесь делает?

2024-11-27 09:08 UTC, Allcash116 commented on build.gradle
> +        languageVersion = JavaLanguageVersion.of(23)
У меня стоит 23 версия ещё в начале посоветовали это поменять. Может я не правильно делаю pull request?

2024-11-27 09:13 UTC, Allcash116 commented on build.gradle
> +        languageVersion = JavaLanguageVersion.of(23)
Наверное не надо было комитить градл. Понял учту больше не буду

2024-11-28 01:18 UTC, Zawadskiy commented on build.gradle
> +        languageVersion = JavaLanguageVersion.of(23)
А теперь біі єто убрать. У меня из-за него тестіі не проходят, как следствие задача ревью не пройдет)

2024-12-13 08:22 UTC, Zawadskiy commented
Срок внесения правок вышел, при необходимости ревью - откройте новый Pull Request

2024-12-13 08:22 UTC, closed without merging