Task1
KFalcon2022/intensive-tasks-2024 pull request #369
Opened 2024-11-24 23:13 UTC by mameevdi

2024-11-25 21:15 UTC, ekolokolov requested changes

2024-11-25 21:15 UTC, ekolokolov commented on src/main/java/com/walking/intensive/chapter1/task1/Task1.java
> +            System.out.print("Некорректный ввод");
Нельзя использовать печать в консоль. 
По тексту задачи 
`Реализуйте метод getAgeString(), который будет принимать параметром целое число (возраст) и возвращать строку`. 
У тебя метод печатает в консоль и всегда возвращает пустую строку.

2024-11-25 21:58 UTC, mameevdi reviewed
Исправил ошибку. Метод передаёт только строку. В консоль выводится через метод println в основном теле программы.

2024-12-15 11:43 UTC, ekolokolov approved these changes

2024-12-15 11:43 UTC, ekolokolov commented on src/main/java/com/walking/intensive/chapter1/task1/Task1.java
> +            phraseYears = "Некорректный ввод";
Новую переменную можно не вводить. Можно сразу писать return. Даже нужно.

2024-12-15 11:44 UTC, ekolokolov approved these changes
Зачтено

2024-12-15 11:44 UTC, closed without merging