Task 1 completed
KFalcon2022/intensive-tasks-2024 pull request #371
Opened 2024-11-24 23:45 UTC by Showmeyrcode

2024-11-25 21:19 UTC, ekolokolov requested changes
Переименовать ПР по требованиям.

2024-11-25 21:19 UTC, ekolokolov commented on src/main/java/com/walking/intensive/chapter1/task1/Task1.java
> +            return ("Некорректный ввод");
Тут скобки не нужны

2024-11-25 21:19 UTC, ekolokolov commented on src/main/java/com/walking/intensive/chapter1/task1/Task1.java
> +            return ("Вам " + age + " лет");
Ну и тут не нужны

2024-11-25 21:19 UTC, ekolokolov commented on src/main/java/com/walking/intensive/chapter1/task1/Task1.java
> +        return switch (remainder) {
Попробуй эту задачу решить без свича. Слишком много тут условий

2024-11-30 19:22 UTC, Showmeyrcode commented
> Переименовать ПР по требованиям.

Не очень понял, что подразумевается под ПР. Переменные? Уточни плиз

2024-11-30 19:24 UTC, ekolokolov commented
> > Переименовать ПР по требованиям.
> 
> Не очень понял, что подразумевается под ПР. Переменные? Уточни плиз

ПР = PR = Pull Request. 
https://github.com/KFalcon2022/intensive-tasks-2024/blob/master/README.md

2024-12-02 14:22 UTC, ekolokolov requested changes

2024-12-02 14:22 UTC, ekolokolov commented on src/main/java/com/walking/intensive/chapter1/task1/Task1.java
> +        } else if (remainder == 0 || remainder == 5 || remainder == 6 || remainder == 7 || remainder == 8 || remainder == 9) {
Вот это можно написать короче через <  и >

2024-12-15 11:29 UTC, closed without merging