Task5
KFalcon2022/intensive-tasks-2024 pull request #372
Opened 2024-11-25 01:38 UTC by rtsnik

Решение Task5.

2024-11-25 22:54 UTC, Zawadskiy requested changes

2024-11-25 22:54 UTC, Zawadskiy commented on src/main/java/com/walking/intensive/chapter1/task5/Task5.java
> +        if (a <= 0.0 || b <= 0.0 || c <= 0.0 || (a + b) <= c || (a + c) <= b || (b + c) <= a) {
Интересная проверка, которая делается несколько раз в разнііх методах) Что же можно с єтим сделать?)

2024-11-25 22:54 UTC, Zawadskiy commented on src/main/java/com/walking/intensive/chapter1/task5/Task5.java
> +        double p = 0.5 * (a + b + c);
Пустііе строки между логическими блоками где?)

2024-11-26 06:40 UTC, rtsnik commented on src/main/java/com/walking/intensive/chapter1/task5/Task5.java
> +        if (a <= 0.0 || b <= 0.0 || c <= 0.0 || (a + b) <= c || (a + c) <= b || (b + c) <= a) {
Как вариант вынести в отдельный метод.

2024-11-27 04:04 UTC, Zawadskiy requested changes

2024-11-27 04:04 UTC, Zawadskiy commented on src/main/java/com/walking/intensive/chapter1/task5/Task5.java
> +        return heights;
не забііваем о лишних строках между логическими блоками

2024-11-27 23:10 UTC, rtsnik commented on src/main/java/com/walking/intensive/chapter1/task5/Task5.java
> +        return heights;
В данном случае только return логически стоит отделить?

2024-11-28 01:39 UTC, Zawadskiy requested changes

2024-11-28 01:39 UTC, Zawadskiy commented on src/main/java/com/walking/intensive/chapter1/task5/Task5.java
> +        return heights;
Нет. Я біі вот так сделал -> p+rootOfSemiPerimeter, hA+Hb+Hc,  heights+его сортировка, return.

2024-12-13 08:23 UTC, Zawadskiy commented
Срок внесения правок вышел, при необходимости ревью - откройте новый Pull Request

2024-12-13 08:23 UTC, closed without merging