task10
KFalcon2022/intensive-tasks-2024 pull request #382
Opened 2024-11-25 10:35 UTC by Rewertkin

2024-11-25 17:43 UTC, KFalcon2022 requested changes

2024-11-25 17:43 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter2/task10/Task10.java
> +        // удалим из строчки всё, кроме букв
не хватает проверки на пустую строку и, опционально на null. Поскольку с ссылочными типами толком не знакомы, проверки на null можно опустить, но пустая строка обязательна к проверке.

2024-11-25 17:43 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter2/task10/Task10.java
> +        String clearString = inputString.replaceAll("[^а-яА-Я]", "");
Так неинтересно, хоть и допустимо:)

2024-11-25 17:43 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter2/task10/Task10.java
> +        for (int i = clearString.length() - 1; i >= 0; i--) {
А нам точно надо еликом строку сравнивать? Не логичнее сравнивать посимвольно, пока до середины не дойдем? Только надо заранее все в lower/upper-case перевести

2024-11-26 19:39 UTC, KFalcon2022 requested changes

2024-11-26 19:39 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter2/task10/Task10.java
> +        if (inputString.length() < 2 || inputString.equals("  ")) {
на будущее - есть, например, метод trim(), который удаляет пробелы в начале и конце строки. Иначе твоя проверка остается уязвима - скажем, `"                  "` пройдет валидацию:)

2024-11-26 19:39 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter2/task10/Task10.java
> +            if (clearString.toLowerCase().charAt(i) != clearString.toLowerCase().charAt(clearString.length() - 1 - i)) {
не логичнее toLowerCase() вызвать там же, где и replaceAll?

2024-11-26 19:39 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter2/task10/Task10.java
> +            palidrome += clearString.charAt(i);
почему это не было удалено?

2024-11-26 19:39 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter2/task10/Task10.java
>      }
Алгоритм подобрал правильный, осталось оформление в порядок привести:)

2024-11-26 19:40 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter2/task10/Task10.java
>      }
А, и добавь проверку на null: для `inputString` == null должно возвращаться false. А то тест падает, аж бесит:)

2024-11-27 10:22 UTC, Rewertkin commented on src/main/java/com/walking/intensive/chapter2/task10/Task10.java
> +            if (clearString.toLowerCase().charAt(i) != clearString.toLowerCase().charAt(clearString.length() - 1 - i)) {
скорректировал

2024-11-27 10:34 UTC, Rewertkin commented on src/main/java/com/walking/intensive/chapter2/task10/Task10.java
> +        if (inputString.length() < 2 || inputString.equals("  ")) {
немного переставил проверку на символы, теперь после replaceAll

2024-11-27 10:35 UTC, Rewertkin commented on src/main/java/com/walking/intensive/chapter2/task10/Task10.java
> +            palidrome += clearString.charAt(i);
удалил

2024-11-27 10:37 UTC, Rewertkin commented on src/main/java/com/walking/intensive/chapter2/task10/Task10.java
>      }
добавил

2024-11-27 20:22 UTC, KFalcon2022 approved these changes

2024-11-27 20:22 UTC, closed without merging