Task8
KFalcon2022/intensive-tasks-2024 pull request #385
Opened 2024-11-25 12:11 UTC by Neverhoodof

2024-11-26 02:00 UTC, Zawadskiy requested changes

2024-11-26 02:00 UTC, Zawadskiy commented on src/main/java/com/walking/intensive/chapter2/task8/Task8.java
> +        int summ;                           //Сумма трех цифр числа
переменнііе обьявляем там где юзаем)

2024-11-26 13:45 UTC, Neverhoodof commented on src/main/java/com/walking/intensive/chapter2/task8/Task8.java
> +        int summ;                           //Сумма трех цифр числа
Не совсем понял о чем речь, но на всякий случай переделал =))

2024-11-27 04:01 UTC, Zawadskiy approved these changes

2024-11-27 04:01 UTC, Zawadskiy commented on src/main/java/com/walking/intensive/chapter2/task8/Task8.java
> +        return totalChance/1000000;
Error: eckstyle] [ERROR] /home/runner/work/intensive-tasks-2024/intensive-tasks-2024/src/main/java/com/walking/intensive/chapter2/task8/Task8.java:37:27: '/' is not followed by whitespace. [WhitespaceAround]
Error: eckstyle] [ERROR] /home/runner/work/intensive-tasks-2024/intensive-tasks-2024/src/main/java/com/walking/intensive/chapter2/task8/Task8.java:37:[27](https://github.com/KFalcon2022/intensive-tasks-2024/actions/runs/12031936068/job/33578641940?pr=385#step:4:28): '/' is not preceded with whitespace. [WhitespaceAround]

2024-11-27 04:02 UTC, closed without merging