Task 6
KFalcon2022/intensive-tasks-2024 pull request #400
Opened 2024-11-25 17:44 UTC by HellRus

2024-11-26 01:52 UTC, Zawadskiy requested changes

2024-11-26 01:52 UTC, Zawadskiy commented on src/main/java/com/walking/intensive/chapter2/task6/Task6.java
>      static int getGcdByEuclideanAlgorithm(int m, int n) {
Тут должна бііть рекурсия, а не цикл)

2024-11-26 01:52 UTC, Zawadskiy commented on src/main/java/com/walking/intensive/chapter2/task6/Task6.java
>      static int getLcm(int m, int n) {
между lcm и gcd есть связь) можно использовать ее)

2024-11-26 13:56 UTC, HellRus commented on src/main/java/com/walking/intensive/chapter2/task6/Task6.java
>      static int getGcdByEuclideanAlgorithm(int m, int n) {
Исправил

2024-11-26 13:56 UTC, HellRus commented on src/main/java/com/walking/intensive/chapter2/task6/Task6.java
>      static int getLcm(int m, int n) {
Теперь вычисляем lcm используя gcd

2024-11-27 03:59 UTC, Zawadskiy requested changes

2024-11-27 03:59 UTC, Zawadskiy commented on src/main/java/com/walking/intensive/chapter2/task6/Task6.java
> +        if (m <= 0 || n <=0) {
Error: eckstyle] [ERROR] /home/runner/work/intensive-tasks-2024/intensive-tasks-2024/src/main/java/com/walking/intensive/chapter2/task6/Task6.java:25:25: '<=' is not followed by whitespace. [WhitespaceAround]

2024-11-27 03:59 UTC, Zawadskiy commented on src/main/java/com/walking/intensive/chapter2/task6/Task6.java
> +        if (m <= 0 || n <=0) {
Error: eckstyle] [ERROR] /home/runner/work/intensive-tasks-20[24](https://github.com/KFalcon2022/intensive-tasks-2024/actions/runs/12032116316/job/33578643146?pr=400#step:4:25)/intensive-tasks-2024/src/main/java/com/walking/intensive/chapter2/task6/Task6.java:42:[25](https://github.com/KFalcon2022/intensive-tasks-2024/actions/runs/12032116316/job/33578643146?pr=400#step:4:26): '<=' is not followed by whitespace. [WhitespaceAround]

2024-11-27 03:59 UTC, Zawadskiy commented on src/main/java/com/walking/intensive/chapter2/task6/Task6.java
> +        if (n > 0) {
Ммм, а реверснуть єто?)

2024-11-28 01:28 UTC, Zawadskiy requested changes

2024-11-28 01:28 UTC, Zawadskiy commented on src/main/java/com/walking/intensive/chapter2/task6/Task6.java
> +        if (m <= 0 || n <= 0) {
Интереснііе три строчки. Повторяются в каждом методе. Что же с ними можно сделать?)

2024-11-28 01:28 UTC, Zawadskiy commented on src/main/java/com/walking/intensive/chapter2/task6/Task6.java
> +        for (int i = 1; i <= smallerNumber; i++) {
Ммм, перебор значений) Работает, но можно лучше, но не обязательно.

2024-11-28 09:32 UTC, HellRus commented on src/main/java/com/walking/intensive/chapter2/task6/Task6.java
> +        if (m <= 0 || n <= 0) {
вынес в отдельный метод

2024-11-30 00:47 UTC, Zawadskiy approved these changes

2024-11-30 00:47 UTC, Zawadskiy commented on src/main/java/com/walking/intensive/chapter2/task6/Task6.java
> +    static boolean incorrectInputValidation(int m, int n) {
isValid() или что-то другое простенькое

2024-11-30 00:47 UTC, Zawadskiy commented on src/main/java/com/walking/intensive/chapter2/task6/Task6.java
> +
пустая строка лишняя

2024-11-30 00:47 UTC, closed without merging