Task6
KFalcon2022/intensive-tasks-2024 pull request #404
Opened 2024-11-25 18:24 UTC by LVictor-SF

В третьем задании метод должен вызывать сам себя, правильно я понимаю?

2024-11-26 01:35 UTC, Zawadskiy commented
> В третьем задании метод должен вызывать сам себя, правильно я понимаю?

Насколько помню, должна бііть рекурсия, тогда Да.

2024-11-26 01:45 UTC, Zawadskiy requested changes

2024-11-26 01:45 UTC, Zawadskiy commented on src/main/java/com/walking/intensive/chapter2/task6/Task6.java
> +        for (int i = 1; i < maxValue ; i++) {
Error: eckstyle] [ERROR] /home/runner/work/intensive-tasks-2024/intensive-tasks-2024/src/main/java/com/walking/intensive/chapter2/task6/Task6.java:28:38: ';' is preceded with whitespace. [NoWhitespaceBefore]

2024-11-26 01:45 UTC, Zawadskiy commented on src/main/java/com/walking/intensive/chapter2/task6/Task6.java
> +        return getGcd(m, n);
Хитрожопо, но єто не рекурсия)

2024-11-26 01:45 UTC, Zawadskiy commented on src/main/java/com/walking/intensive/chapter2/task6/Task6.java
> +    static boolean isInvalidValue(int a, int b) {
название метода так себе)

2024-11-26 01:45 UTC, Zawadskiy commented on src/main/java/com/walking/intensive/chapter2/task6/Task6.java
>      static int getLcm(int m, int n) {
все єто можно сделать куда проще юзай gcd)

2024-11-26 08:30 UTC, LVictor-SF commented on src/main/java/com/walking/intensive/chapter2/task6/Task6.java
> +        return getGcd(m, n);
я не пытался решить третье задание, об этом я написал в коммите, просто поставил заглушку что бы не отвлекали лишние ошибки и задал уточняющий вопрос по решению третьей задачи в PR.

2024-11-26 09:17 UTC, LVictor-SF commented on src/main/java/com/walking/intensive/chapter2/task6/Task6.java
> +    static boolean isInvalidValue(int a, int b) {
Что бы вы предпочли?
isDataInvalid
invalidData

2024-11-26 11:03 UTC, Zawadskiy commented on src/main/java/com/walking/intensive/chapter2/task6/Task6.java
> +    static boolean isInvalidValue(int a, int b) {
IsValid()

2024-11-26 11:04 UTC, Zawadskiy commented on src/main/java/com/walking/intensive/chapter2/task6/Task6.java
> +        return getGcd(m, n);
так то нет) Но я хочу чтобіі бііло сделано) Там не сложно.

2024-11-27 03:55 UTC, Zawadskiy approved these changes

2024-11-27 03:55 UTC, Zawadskiy commented on src/main/java/com/walking/intensive/chapter2/task6/Task6.java
> +    static int getGcbByRecursionEuclideanAlgorithm (int m, int n) {
Error: eckstyle] [ERROR] /home/runner/work/intensive-tasks-2024/intensive-tasks-2024/src/main/java/com/walking/intensive/chapter2/task6/Task6.java:76:52: '(' is preceded with whitespace. [MethodParamPad]

2024-11-27 03:56 UTC, closed without merging

2024-11-27 04:12 UTC, Zawadskiy commented on src/main/java/com/walking/intensive/chapter2/task6/Task6.java
> +    static int getGcbByRecursionEuclideanAlgorithm (int m, int n) {
Вообще у тебя нет валидации, но живи