task7
KFalcon2022/intensive-tasks-2024 pull request #414
Opened 2024-11-26 08:12 UTC by Superbia101

2024-11-27 12:02 UTC, EvgeneZhurov requested changes

2024-11-27 12:02 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter2/task7/Task7.java
> +        int possible_friendly_number, friendly_number = 0, sum = 0;
в этом комьюнити больше любят кэмел кейс

2024-11-27 12:02 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter2/task7/Task7.java
> +        return friendly_number;
лучше назвать как метод(без глагола)

2024-11-27 12:02 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter2/task7/Task7.java
> +        }
блоки кода лучше отделять пустыми строками с обеих сторон, если это не начало или конец метода. Так читается легче (просьба поставить перед return)

2024-11-27 12:48 UTC, Superbia101 commented on src/main/java/com/walking/intensive/chapter2/task7/Task7.java
> +        while (div < num / div) {
Поменял

2024-11-27 12:49 UTC, Superbia101 commented on src/main/java/com/walking/intensive/chapter2/task7/Task7.java
> +        int possible_friendly_number, friendly_number = 0, sum = 0;
Видимо отвлёкся или забылся))

2024-11-29 19:28 UTC, EvgeneZhurov approved these changes

2024-11-29 19:28 UTC, closed without merging