task8
KFalcon2022/intensive-tasks-2024 pull request #418
Opened 2024-11-26 11:02 UTC by Superbia101

Тест не прошёл, но посчитано вроде верно

2024-11-27 12:18 UTC, EvgeneZhurov requested changes

2024-11-27 12:18 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter2/task8/Task8.java
> +        for (int i = 0; i < 1000000; i++) {
Ответ на вопрос является ли билетик счастливым лучше вынести в отдельный метод.

2024-11-27 12:18 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter2/task8/Task8.java
> +        int value = 0;
нужно стараться давать максимально релевантные имена. Это не "значение", это "количество счастливых билетиков"

2024-11-27 12:18 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter2/task8/Task8.java
> +        return (double) value / 1000000;
не хватает пустой строки перед return. Блоки кода лучше отделять пустыми строками, если они стоят не в самом начале или конце метода.

2024-11-27 13:08 UTC, Superbia101 commented on src/main/java/com/walking/intensive/chapter2/task8/Task8.java
> +        for (int i = 0; i < 1000000; i++) {
Надеюсь, что понял правильно)

2024-11-29 19:35 UTC, EvgeneZhurov approved these changes

2024-11-29 19:35 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter2/task8/Task8.java
> +        int HappyTicketChance = 0;
не соблюдена верблюжья нотация. Первая буква должна быть маленькой. Старайтесь давать максимально релевантные имена. Это не шанс. Шанс - это вероятность встретить счастливый билетик среди всех. Шанс - это величина не больше единицы. В данном случае это "Количество счастливых билетиков". Искажая смысл переменных Вам будет тяжелее работать с кодом.

2024-11-29 19:35 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter2/task8/Task8.java
> +    static boolean isEqual(int num) {
старайтесь давать максимально релевантные имена. Ваш метод называется getHappyTicketChance, а данный метода отвечает на поставленный вопрос. Логичнее назвать isHappy или isHappyTicket

2024-11-29 19:35 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter2/task8/Task8.java
лишняя пустая строка

2024-11-29 19:36 UTC, closed without merging