Task5
KFalcon2022/intensive-tasks-2024 pull request #427
Opened 2024-11-26 16:46 UTC by stillwearit

2024-11-27 21:27 UTC, KFalcon2022 requested changes

2024-11-27 21:27 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter1/task5/Task5.java
> +        if (a >= b + c || b >= a + c || c >= a + b) {
Зачем дублировать каждый раз?  Можно вынести в метод. И не увидел проверки на отрицательные значения стороны

2024-11-27 21:27 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter1/task5/Task5.java
> +        return (double) Math.sqrt(halfPerimeter * (halfPerimeter - a) * (halfPerimeter - b) * (halfPerimeter - c));
Избыточное приведение типа. sqrt() и так возвращает double

2024-11-27 21:27 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter1/task5/Task5.java
> +        if (height1 < height2 && height1 < height3)  {
полагаю, эта история однотипна для каждого метода с возвращаемым массивом. Не логичнее вынести в отдельный метод и переиспользовать?

2024-11-27 21:27 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter1/task5/Task5.java
> +        double height1 = area * 2 / a;
формулу логично в метод вынести. Ты ее дублируешь трижды, если будет ошибка - в трех местах придется править. Вынесешь в метод - правка нужна будет только в одной строке:)

2024-11-27 21:27 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter1/task5/Task5.java
> +        return (a * b / 2 * sinC);
Однотипные замечания не дублирова

2024-11-28 17:07 UTC, stillwearit commented on src/main/java/com/walking/intensive/chapter1/task5/Task5.java
> +        if (a >= b + c || b >= a + c || c >= a + b) {
спасибо, попробую вынести в метод :) а разве это условие уже не исключает и отрицательные стороны тоже?

2024-11-28 17:25 UTC, stillwearit commented on src/main/java/com/walking/intensive/chapter1/task5/Task5.java
> +        double height1 = area * 2 / a;
не понимаю, разве это не три разные формулы? просто весь метод getHeights вроде только их и содержит, их можно как-то в одну преобразовать?

2024-11-28 20:15 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter1/task5/Task5.java
> +        double height1 = area * 2 / a;
Формула одна и та же. Ты просто подставляешь в них разные значения

2024-11-28 20:16 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter1/task5/Task5.java
> +        if (a >= b + c || b >= a + c || c >= a + b) {
Вообще, кажется, что исключает. Но надо посчитать, чтобы убедиться

2024-11-28 20:26 UTC, KFalcon2022 requested changes

2024-11-28 20:26 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter1/task5/Task5.java
> +}
Файл должен завершаться пустой строкой. https://stackoverflow.com/questions/2287967/why-is-it-recommended-to-have-empty-line-in-the-end-of-a-source-file

2024-11-28 20:26 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter1/task5/Task5.java
> +    static boolean isTriangleExist (double a, double b, double c) {
Пробел перед "(" не ставится

2024-11-28 20:26 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter1/task5/Task5.java
> +    static double getHalfPerimeter (double a, double b, double c) {
Пробел перед "(" не ставится

2024-11-28 20:26 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter1/task5/Task5.java
> +    static double getCosC (double a, double b, double c) {
Пробел перед "(" не ставится

2024-11-28 20:26 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter1/task5/Task5.java
> +    static double[] sortArrays (double doubles1, double doubles2, double doubles3) {
Пробел перед "(" не ставится

2024-11-28 20:26 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter1/task5/Task5.java
> +    static boolean isTriangleExist (double a, double b, double c) {
Сначала располагаются методы, которые потенциально будут вызываться из других классов, потом - те, которые нужны только в пределах текущего. Иначе ты заставляешь человека читать код, смысл которого станет понятен только 10-100-1000 строчек спустя

Позже познакомишься с модификаторами доступа и осознать эту концепцию станет проще

2024-11-28 20:26 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter1/task5/Task5.java
> +    static double getCosC (double a, double b, double c) {
Не самое очевидное название. Лучше getCos()+более говорящие имена параметров, которые пояснят, для какого угла считается косинус

2024-11-28 20:26 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter1/task5/Task5.java
> +    static double[] sortArrays (double doubles1, double doubles2, double doubles3) {
Ты не только сортируешь, но и создаешь массив в этом методе - не самая удачная затея на самом деле. У метода должна быть одна зона ответственности, сейчас - две

Опять же, откуда множественное число в названии метода?

2024-11-28 20:26 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter1/task5/Task5.java
> +        if (isTriangleExist(a, b, c)) {
лучше наоборот. Сначала отрицательные сценарии, потом - позитивные. Потому что позитивные более многословны, из-за чего с большой долей вероятности ты повысишь вложенность кода, который ты и так уже впихнул внутрь if

2024-11-28 20:26 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter1/task5/Task5.java
> +        if (isTriangleExist(a, b, c)) {
Аналогично в методах ниже

2024-11-28 20:26 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter1/task5/Task5.java
> +            double doubles1 = area * 2 / a;
имена переменных должны быть осмысленными. Если это высота - в названии это должно быть отображено

2024-11-28 20:26 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter1/task5/Task5.java
> +           double doubles3 = 180 - doubles1 - doubles2;
Микрооптимизации - спорная тема. Это вычисление дешевле, чем по формуле выше. Но иногда однообразие стоит дороже, чем пару процессорных тактов

2024-11-29 16:12 UTC, stillwearit commented on src/main/java/com/walking/intensive/chapter1/task5/Task5.java
> +    static double[] sortArrays (double doubles1, double doubles2, double doubles3) {
вроде со всеми замечаниями разобралась, но сортировку из метода никак не могу достать, хотя внутри него она работает, судя по дебаггеру

2024-11-29 16:17 UTC, stillwearit commented on src/main/java/com/walking/intensive/chapter1/task5/Task5.java
> +        if (a >= b + c || b >= a + c || c >= a + b) {
я так прикинула, что сравнивать надо для самой большой стороны. если хотя бы одна сторона отрицательная, то бОльшая сторона треугольника будет явно больше суммы двух других.

2024-11-29 16:34 UTC, stillwearit commented on src/main/java/com/walking/intensive/chapter1/task5/Task5.java
> +    static double[] sortArrays (double doubles1, double doubles2, double doubles3) {
вопрос снят, дошло!

2024-11-30 15:40 UTC, KFalcon2022 requested changes

2024-11-30 15:40 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter1/task5/Task5.java
> +        return 2 * Math.sqrt(adjacent1 * adjacent2 * halfPerimeter * (halfPerimeter - opposite)) / (adjacent1 + adjacent2);
Строка не должна превышать 120 символов. Считается, что именно столько влазит в один экран при стандартных настройках

2024-11-30 15:40 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter1/task5/Task5.java
> +        if (check1 > check2 && check1 > check3) {
Можно проще, если не просто подставляться нужную check-переменную в нужный индекс, а "менять" значения местами.

Условно, если в doubles[0] подставляешь check2 - в doubles[1] подставить сразу check1. Тогда тебе не придется сравнивать все три значения для каждого индекса.

Потому что уже после блока if-else выше можно будет или оставить как есть, или поменять местами doubles[1] и doubles[2] и все будет ок:)

2024-11-30 15:40 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter1/task5/Task5.java
> +        return doubles;
в целом, можно метод сделать void - он ведь возвращает тот же массив, который получил на вход

2024-11-30 15:40 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter1/task5/Task5.java
> +        return 2 * Math.sqrt(adjacent1 * adjacent2 * halfPerimeter * (halfPerimeter - opposite)) / (adjacent1 + adjacent2);
Предлагаю вынести промежуточные вычисления в отдельную переменную. И читать будет проще, и в длину влезешь)

2024-11-30 15:40 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter1/task5/Task5.java
> +        double area = getAreaByHeron(opposite, adjacent1, adjacent2);
не логичнее в основном методе вычислить площадь и трижды передать ее в этот метод? Сейчас мы зачем-то площадь одного и того же треугольника считаем трижды - по разу на каждый вызов getHeight()

2024-11-30 15:40 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter1/task5/Task5.java
> +
Стало намного лучше, но нужно еще немного добить

2024-12-02 18:40 UTC, closed without merging