Task6
KFalcon2022/intensive-tasks-2024 pull request #429
Opened 2024-11-26 17:54 UTC by zemaumka

Задача6

2024-11-27 21:21 UTC, KFalcon2022 requested changes

2024-11-27 21:21 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter2/task6/Task6.java
> +                if (i % m == 0 && i % n == 0) {
перебор - тоже решение, но не самое оптимальное

2024-11-27 21:21 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter2/task6/Task6.java
> +            for (int i = Math.min(m, n); i > 0; i--) {
аналогично

2024-11-27 21:21 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter2/task6/Task6.java
> +        if (m > 0 && n > 0) {
Не слишком хорошая практика. Логичнее сделать валидацию с return, а потом уже писать остальной код. И вложенность меньше будет, и читать проще

2024-11-27 21:21 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter2/task6/Task6.java
> +        return m;
Для алгоритма Евклида принимается только рекурсивный алгоритм

2024-12-02 18:43 UTC, KFalcon2022 approved these changes

2024-12-02 18:43 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter2/task6/Task6.java
> +        return getGcdByEuclideanAlgorithm(n, m % n);
задача зачтена

2024-12-03 16:01 UTC, zemaumka commented on src/main/java/com/walking/intensive/chapter2/task6/Task6.java
> +        return getGcdByEuclideanAlgorithm(n, m % n);
Закроете?

2024-12-14 13:26 UTC, closed without merging