Task4
KFalcon2022/intensive-tasks-2024 pull request #430
Opened 2024-11-26 18:06 UTC by AndyRaw007

2024-11-27 21:04 UTC, KFalcon2022 requested changes

2024-11-27 21:04 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter1/task4/Task4.java
> +            double koren = (-c) / b;
И скобки лишние

2024-11-27 21:04 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter1/task4/Task4.java
> +        int num = 0;
Переменные объявляются как можно ближе к месту их использования

2024-11-27 21:04 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter1/task4/Task4.java
> +            return String.valueOf("Количество решений: 1. Корень: " + koren);
Везде

2024-11-27 21:04 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter1/task4/Task4.java
> +        if (x2 < x1) {
разделяй логические блоки кода пустыми строками. Иначе все сливается в одно полотно

2024-11-27 21:04 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter1/task4/Task4.java
> +        if (x1 == x2) {
при положительном дискриминанте такая ситуация недостижима. Соответственно, этот результат можно вернуть сильно раньше

2024-11-27 21:04 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter1/task4/Task4.java
> +        return String.valueOf("Количество решений: " + num + ". Корни: " + x1 + ";" + x2);
Много избыточных проверок

2024-11-30 13:23 UTC, AndyRaw007 commented on src/main/java/com/walking/intensive/chapter1/task4/Task4.java
> +            double koren = (-c) / b;
Поправил. На фарси забавно выглядит: risheh ))

2024-11-30 13:26 UTC, AndyRaw007 commented on src/main/java/com/walking/intensive/chapter1/task4/Task4.java
> +            return String.valueOf("Количество решений: 1. Корень: " + koren);
Убрал лишнее. Как-то без этого у меня ошибка на несоответствие типов вываливалась в предыдущих задачах, тут решил перестраховаться

2024-11-30 13:27 UTC, AndyRaw007 commented on src/main/java/com/walking/intensive/chapter1/task4/Task4.java
> +        double discriminant = (b * b) - (4 * a * c);
Перенёс ниже

2024-11-30 13:27 UTC, AndyRaw007 commented on src/main/java/com/walking/intensive/chapter1/task4/Task4.java
> +        int num = 0;
Перенёс ниже

2024-11-30 13:37 UTC, AndyRaw007 commented on src/main/java/com/walking/intensive/chapter1/task4/Task4.java
> +        if (x2 < x1) {
Разбил на блоки

2024-11-30 13:41 UTC, AndyRaw007 commented on src/main/java/com/walking/intensive/chapter1/task4/Task4.java
> +        if (x1 == x2) {
Поправил логику, перенёс выше

2024-11-30 13:41 UTC, AndyRaw007 commented on src/main/java/com/walking/intensive/chapter1/task4/Task4.java
> +        return String.valueOf("Количество решений: " + num + ". Корни: " + x1 + ";" + x2);
Убрал лишнюю проверку

2024-11-30 15:49 UTC, KFalcon2022 requested changes
Стало лучше, но надо добить

2024-11-30 15:49 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter1/task4/Task4.java
> +            double solution = - b / 2 * a;
если ты хочешь указать, что b нужно взять с противоположным знаком - пробел не ставится: `-b / 2 * a`

2024-11-30 15:49 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter1/task4/Task4.java
> +        if (a != 0 && b == 0 && c == 0) {
по-моему, это вполне уложится в решение через дискриминант. Зачем выносить отдельно?

2024-11-30 15:49 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter1/task4/Task4.java
> +        int num = 0;
бесполезная переменная. Что изменится, если ее убрать?

2024-11-30 15:49 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter1/task4/Task4.java
> +        if (discriminant == 0 || a == 0) {
Мне кажется, или к этому моменту уже нет вариантов, при которых `a == 0`? Выглядит, будто все они были отсеяны выше

2024-11-30 15:49 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter1/task4/Task4.java
> +        if (discriminant >= 0) {
а тут еще остаются сценарии, при которых дискриминант не положительный?:)

2024-11-30 16:07 UTC, AndyRaw007 commented
Переписал 60 строку, я так понял чекстайл ругается на неё

2024-11-30 16:10 UTC, AndyRaw007 commented
Поздно увидел комментарии, изменения последние пока не готовы, сори за фальшстарт ревью

2024-12-02 08:19 UTC, AndyRaw007 commented on src/main/java/com/walking/intensive/chapter1/task4/Task4.java
> +            double solution = - b / 2 * a;
Переписал эту строчку. Так лучше?

2024-12-02 08:42 UTC, AndyRaw007 commented on src/main/java/com/walking/intensive/chapter1/task4/Task4.java
> +        int num = 0;
Переписал без неё

2024-12-02 08:55 UTC, AndyRaw007 commented on src/main/java/com/walking/intensive/chapter1/task4/Task4.java
> +        if (a != 0 && b == 0 && c == 0) {
Без этого в одном из тестов выводился ответ "Количество решений: 1. Корень: -0.0", что не устраивало. Переписал, почитал интернет, добавил +0.0 и всё стало как надо. Но ведь это костыль?

2024-12-02 09:00 UTC, AndyRaw007 commented on src/main/java/com/walking/intensive/chapter1/task4/Task4.java
> +        if (discriminant == 0 || a == 0) {
Убрал лишнюю проверку

2024-12-02 09:01 UTC, AndyRaw007 commented on src/main/java/com/walking/intensive/chapter1/task4/Task4.java
> +        if (discriminant >= 0) {
Убрал лишний if

2024-12-02 09:12 UTC, AndyRaw007 commented
Внёс правки, почему-то не активна кнопка справа сверху для реквеста

2024-12-02 18:59 UTC, KFalcon2022 approved these changes
Задача зачтена

2024-12-02 18:59 UTC, closed without merging