Task6
KFalcon2022/intensive-tasks-2024 pull request #432
Opened 2024-11-26 18:37 UTC by andreyv24

2024-11-27 20:55 UTC, KFalcon2022 requested changes

2024-11-27 20:55 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter1/task5/Task5.java
> +}
Что этот класс делает в этом ПР?)

2024-11-27 20:55 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter2/task6/Task6.java
> +        {
Неименованные блоки кода в Java не используются. Удалить

2024-11-27 20:55 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter2/task6/Task6.java
> +        return  ((n <= 0) || (m <=0));
(m <=0) - потерян пробел перед 0. И скобки лишние

2024-11-27 20:55 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter2/task6/Task6.java
> +    static boolean ifNumbersNegative(int m, int n) {
методы разделяются пустой строкой. Кроме того, методы для внутреннего использования (вызывающиеся только внутри текущего класса) всегда располагаются снизу. Иначе их назначение может быть непонятно

2024-11-27 20:55 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter2/task6/Task6.java
> +            int findNok = (m * n) / getGcd(m, n);
избыточная переменная. Ну и предлагаю решить без использования НОД. Текущий подход хороший и рабочий, но неинтересный)

2024-11-27 20:55 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter2/task6/Task6.java
> +                break;
проще сюда return впихнуть, чем break использовать:)

2024-11-27 20:55 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter2/task6/Task6.java
> +            if (n % findNod == 0 & m % findNod == 0) {
& заставляет программу делать лишнее действие. Ты ей явно указываешь проверить `m % findNod == 0`, даже если `n % findNod == 0` уже вернул false

2024-11-27 20:55 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter2/task6/Task6.java
> +            if (n % findNod == 0 & m % findNod == 0) {
И в целом не слишком удачно построен цикл. Можно обойтись без if

2024-11-27 20:55 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter2/task6/Task6.java
> +        return m;
Алгоритм Евклида принимается только в рекурсивной реализации

2024-11-27 20:55 UTC, KFalcon2022 commented on src/test/java/com/walking/intensive/chapter1/task5/Task5Test.java
> +        assertArrayEquals(new double[]{4.615, 5.0, 12.0}, getHeights(12, 13, 5), 1e-10);
и что это за чудо?)

2024-12-03 17:40 UTC, andreyv24 commented on src/main/java/com/walking/intensive/chapter2/task6/Task6.java
> +        {
удалил

2024-12-03 17:42 UTC, andreyv24 commented on src/main/java/com/walking/intensive/chapter2/task6/Task6.java
> +        return  ((n <= 0) || (m <=0));
добавил пробел, скобки убрал.

2024-12-03 18:14 UTC, andreyv24 commented on src/main/java/com/walking/intensive/chapter2/task6/Task6.java
> +    static boolean ifNumbersNegative(int m, int n) {
Добавил пустые строки. Метод для внутреннего использования перенёс в низ класса.

2024-12-03 18:17 UTC, andreyv24 commented on src/main/java/com/walking/intensive/chapter2/task6/Task6.java
> +            int findNok = (m * n) / getGcd(m, n);
Убрал ненужную переменную. 

> Текущий подход хороший и рабочий, но неинтересный)
Ну согласен.... ))))

2024-12-03 18:18 UTC, andreyv24 commented on src/test/java/com/walking/intensive/chapter1/task5/Task5Test.java
> +        assertArrayEquals(new double[]{4.615, 5.0, 12.0}, getHeights(12, 13, 5), 1e-10);
У меня произошёл казус с test5. Я его случайно удалил, потом долго восстанавливал. А теперь он и связанные с ним файлы лезут во все таски. Вирус какой-то!!!

2024-12-03 18:38 UTC, andreyv24 commented on src/main/java/com/walking/intensive/chapter2/task6/Task6.java
> +        return m;
Понятно. Буду думать.

2024-12-05 20:03 UTC, KFalcon2022 commented on src/test/java/com/walking/intensive/chapter1/task5/Task5Test.java
> +        assertArrayEquals(new double[]{4.615, 5.0, 12.0}, getHeights(12, 13, 5), 1e-10);
есть повод познакомиться с гитом поближе:)

2024-12-05 20:11 UTC, KFalcon2022 requested changes

2024-12-05 20:11 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter2/task6/Task6.java
> +            findNok = findNok + Math.max(m, n);
Можно заменить на `findNok += Math.max(m, n);`. Будет лаконичнее

2024-12-05 20:11 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter2/task6/Task6.java
> +
лишняя пустая строка

2024-12-05 20:11 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter2/task6/Task6.java
> +        if (ifNumbersNegative(m, n)) {
булеан-методы обычно именуются с is

2024-12-05 20:11 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter2/task6/Task6.java
> +        int findNok = Math.max(m, n);
Никакого транслита. Nok - явно не английский термин:) Кроме того, имена переменных описывают существительное, если грубо. find - глагол

2024-12-05 20:11 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter2/task6/Task6.java
> +        int findNod = Math.min(m, n);
убрать транслит

2024-12-05 20:11 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter2/task6/Task6.java
> +        while (n % findNod != 0 | m % findNod != 0) {
| заставляет проверять все условия, даже если результат всего выражения уже известен. В 99% случаев это избыточно и лучше использовать ||. То же самое с & и &&

2024-12-05 20:11 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter2/task6/Task6.java
> +
Лишняя пустая строка

2024-12-05 20:11 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter2/task6/Task6.java
> +
Лишняя пустая строка

2024-12-05 20:11 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter2/task6/Task6.java
> +        if (m > n) {
Лучше заменить на тернарный оператор

2024-12-05 20:11 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter2/task6/Task6.java
> +
Лишняя пустая строка

2024-12-12 22:18 UTC, andreyv24 commented on src/main/java/com/walking/intensive/chapter2/task6/Task6.java
> +            findNok = findNok + Math.max(m, n);
А что, так можно было ? ))))
Круто! Заменил!

2024-12-12 22:20 UTC, andreyv24 commented on src/main/java/com/walking/intensive/chapter2/task6/Task6.java
> +
Убрал. А return не выделяется пустой строчкой от другого кода ?

2024-12-12 22:22 UTC, andreyv24 commented on src/main/java/com/walking/intensive/chapter2/task6/Task6.java
> +        if (ifNumbersNegative(m, n)) {
if заменил на is.

2024-12-12 22:26 UTC, andreyv24 commented on src/main/java/com/walking/intensive/chapter2/task6/Task6.java
> +        int findNok = Math.max(m, n);
заменил на англоязычное описание

2024-12-12 22:26 UTC, andreyv24 commented on src/main/java/com/walking/intensive/chapter2/task6/Task6.java
> +        int findNod = Math.min(m, n);
убрал

2024-12-12 22:29 UTC, andreyv24 commented on src/main/java/com/walking/intensive/chapter2/task6/Task6.java
> +        while (n % findNod != 0 | m % findNod != 0) {
Понял. Спасибо.

2024-12-12 22:30 UTC, andreyv24 commented on src/main/java/com/walking/intensive/chapter2/task6/Task6.java
> +
убрал

2024-12-12 22:30 UTC, andreyv24 commented on src/main/java/com/walking/intensive/chapter2/task6/Task6.java
> +
убрал

2024-12-12 22:32 UTC, andreyv24 commented on src/main/java/com/walking/intensive/chapter2/task6/Task6.java
> +
убрал

2024-12-12 22:46 UTC, andreyv24 commented on src/main/java/com/walking/intensive/chapter2/task6/Task6.java
> +        if (m > n) {
Заменил.

2024-12-12 22:47 UTC, andreyv24 commented on src/main/java/com/walking/intensive/chapter2/task6/Task6.java
> +        return m;
Сделал рекурсивную реализацию.

2024-12-13 00:00 UTC, andreyv24 commented on src/test/java/com/walking/intensive/chapter1/task5/Task5Test.java
> +        assertArrayEquals(new double[]{4.615, 5.0, 12.0}, getHeights(12, 13, 5), 1e-10);
Вроде task5 убрал, но это неточно. )))

2024-12-14 13:47 UTC, KFalcon2022 approved these changes
Замечание мелкое, задача зачтена

2024-12-14 13:47 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter2/task6/Task6.java
> +            lcm += Math.max(m, n);
Зачем повторно выяснять? у нас же m и n не меняются

2024-12-14 13:50 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter2/task6/Task6.java
> +
Зависит от принятых в команде правил. Я предпочитаю в пределах отделять подпрограммы (кода внутри {}). Но еще никогда не видел, чтобы оставляли пустую строку, когда вся подпрограмма состоит из reutrn:)

То есть

```java
if (expression) {
    // some code
    // some code
    // some code

    return value; //ок
}
```

```java
if (expression) {

    return value; //бесполезная пустая строка
}
```

2024-12-14 13:50 UTC, closed without merging

2025-01-04 21:24 UTC, andreyv24 commented on src/main/java/com/walking/intensive/chapter2/task6/Task6.java
> +
Понял, спасибо большое за разъяснение.