Task8
KFalcon2022/intensive-tasks-2024 pull request #436
Opened 2024-11-27 00:26 UTC by andreyv24

2024-11-28 03:25 UTC, Zawadskiy requested changes

2024-11-28 03:25 UTC, Zawadskiy commented on src/test/java/com/walking/intensive/chapter1/task5/Task5Test.java
> +        assertArrayEquals(new double[]{4.615, 5.0, 12.0}, getHeights(12, 13, 5), 1e-10);
Что єто такое?

2024-11-28 03:25 UTC, Zawadskiy commented on src/main/java/com/walking/intensive/chapter1/task5/Task5.java
>      static double getAreaByHeron(double a, double b, double c) {
Что єто делает в 8-й задаче?

2024-11-28 03:25 UTC, Zawadskiy commented on src/main/java/com/walking/intensive/chapter2/task8/Task8.java
> +                {
Error: eckstyle] [ERROR] /home/runner/work/intensive-tasks-2024/intensive-tasks-2024/src/main/java/com/walking/intensive/chapter2/task8/Task8.java:44:17: Avoid nested blocks. [AvoidNestedBlocks]

2024-11-28 03:25 UTC, Zawadskiy commented on src/main/java/com/walking/intensive/chapter2/task8/Task8.java
> +        return getProbability = getEquality / (999999 + 1);
Error: eckstyle] [ERROR] /home/runner/work/intensive-tasks-2024/intensive-tasks-2024/src/main/java/com/walking/intensive/chapter2/task8/Task8.java:56:31: Inner assignments should be avoided. [InnerAssignment]

2024-11-28 03:25 UTC, Zawadskiy commented on src/main/java/com/walking/intensive/chapter2/task8/Task8.java
> +        for (int i = 0; i < 1000; i++) {
1_000_000 повторений вместо 1_000 єфективность хромает.

2024-12-03 21:04 UTC, andreyv24 commented on src/test/java/com/walking/intensive/chapter1/task5/Task5Test.java
> +        assertArrayEquals(new double[]{4.615, 5.0, 12.0}, getHeights(12, 13, 5), 1e-10);
У меня произошёл сбой с Task5 и она как-то добавляет к другим Task'ам. Где можно посмотреть чтобы пофиксить это ?

2024-12-03 21:43 UTC, andreyv24 commented on src/main/java/com/walking/intensive/chapter2/task8/Task8.java
> +        for (int i = 0; i < 1000; i++) {
Идей другого алгоритма не знаю, буду думать.

2024-12-13 08:24 UTC, Zawadskiy commented
Срок внесения правок вышел, при необходимости ревью - откройте новый Pull Request

2024-12-13 08:24 UTC, closed without merging