Final
KFalcon2022/intensive-tasks-2024 pull request #444
Opened 2024-11-27 12:07 UTC by ruarchie

2024-11-27 12:19 UTC, EvgeneZhurov commented
просьба даль другое название по номеру задачи

2024-11-28 02:57 UTC, Zawadskiy requested changes

2024-11-28 02:57 UTC, Zawadskiy commented on src/main/java/com/walking/intensive/chapter2/task6/Task6.java
> +        return getGcdByEuclideanAlgorithm( minValue, modValue );
Error: eckstyle] [ERROR] /home/runner/work/intensive-tasks-2024/intensive-tasks-2024/src/main/java/com/walking/intensive/chapter2/task6/Task6.java:77:42: '(' is followed by whitespace. [ParenPad]
Error: eckstyle] [ERROR] /home/runner/work/intensive-tasks-2024/intensive-tasks-2024/src/main/java/com/walking/intensive/chapter2/task6/Task6.java:77:63: ')' is preceded with whitespace. [ParenPad]

2024-11-28 02:57 UTC, Zawadskiy commented on src/main/java/com/walking/intensive/chapter2/task6/Task6.java
> +        if (m <= 0 || n <= 0) {
Валидацию в отдельніій метод.

2024-11-30 00:43 UTC, Zawadskiy commented on src/main/java/com/walking/intensive/chapter2/task6/Task6.java
> +    private static boolean isNotCorrectInputValues(int m, int n) {
приватнііе методіі(методііі для личного/в пределах своего класса пользлования) лучше обьявлять в самом низу

2024-11-30 00:43 UTC, Zawadskiy commented on src/main/java/com/walking/intensive/chapter2/task6/Task6.java
> +    private static boolean isNotCorrectInputValues(int m, int n) {
isValid()

2024-11-30 00:44 UTC, closed without merging