Task10
KFalcon2022/intensive-tasks-2024 pull request #445
Opened 2024-11-27 12:18 UTC by Neverhoodof

2024-11-28 15:31 UTC, PuccaGTS requested changes
Давайте чутка поправим

2024-11-28 15:31 UTC, PuccaGTS commented on src/main/java/com/walking/intensive/chapter2/task10/Task10.java
> +import java.lang.reflect.Array;
какой-то импорт мутный и не используется)

2024-11-28 15:31 UTC, PuccaGTS commented on src/main/java/com/walking/intensive/chapter2/task10/Task10.java
> +        if (inputString == null || inputString.length() <2){
Все операции (сложения, вычитания, сравнения и тд и тп) необходимо обособлять с двух сторон пробелами, чтобы строка не сливалась в одну:)

2024-11-28 15:31 UTC, PuccaGTS commented on src/main/java/com/walking/intensive/chapter2/task10/Task10.java
> +        if (inputString == null || inputString.length() <2){
плюс Пробелчик после ) и перед {

2024-11-28 15:31 UTC, PuccaGTS commented on src/main/java/com/walking/intensive/chapter2/task10/Task10.java
> +        for (int i = cleanCharacters.length - 1; i >=0 ; i--) {
Знак >= после пробел, а вот перед точкой с запятой лишний пробле.

2024-11-28 15:31 UTC, PuccaGTS commented on src/main/java/com/walking/intensive/chapter2/task10/Task10.java
> +        inputString = inputString.replaceAll("[^\\p{L}]", "");
в целом это действие можно записать в одну строку `"str".toUpperCase().replaceAll("[^\\p{L}]", "");`
И будет лучше, если Вы создадите новую переменную, чтобы не менять параметры метода.

2024-11-28 15:31 UTC, PuccaGTS commented on src/main/java/com/walking/intensive/chapter2/task10/Task10.java
> +            outputString += cleanCharacters[i];
Если есть необходимость часто изменять строку, то обычно пользуются классом StringBuilder и его методом append() для построения нужной строки. Но в рамках курса, вроде, вы такое не затрагиваете. Править необязательно.

2024-11-30 01:37 UTC, Neverhoodof commented on src/main/java/com/walking/intensive/chapter2/task10/Task10.java
> +        if (inputString == null || inputString.length() <2){
Поторопился =((
Обычно Ctrl+Alt+L пользую =))

2024-11-30 01:56 UTC, Neverhoodof commented on src/main/java/com/walking/intensive/chapter2/task10/Task10.java
> +            outputString += cleanCharacters[i];
Сделал вторую версию кода

2024-12-01 06:26 UTC, PuccaGTS approved these changes
гуд

2024-12-01 06:28 UTC, closed without merging