Task9
KFalcon2022/intensive-tasks-2024 pull request #446
Opened 2024-11-27 13:46 UTC by Roj-han

без рекурсии

2024-11-28 15:42 UTC, PuccaGTS requested changes
Давайте чутка подправим стиль

2024-11-28 15:42 UTC, PuccaGTS commented on src/main/java/com/walking/intensive/chapter2/task9/Task9.java
> +        int[] numberPrevStage = new int[n];
В строке какие-то лишние пробелы

2024-11-28 15:42 UTC, PuccaGTS commented on src/main/java/com/walking/intensive/chapter2/task9/Task9.java
> +            pascalTriangle += String.valueOf(' ').repeat(spaceLength) +
При переносе плюсик на новую строку

2024-11-28 15:42 UTC, PuccaGTS commented on src/main/java/com/walking/intensive/chapter2/task9/Task9.java
> +                    pascalTriangleArr[i] +
Как и предыдущее

2024-11-28 17:24 UTC, Roj-han commented on src/main/java/com/walking/intensive/chapter2/task9/Task9.java
> +        int[] numberPrevStage = new int[n];
насчет лишних пробелов не поняла, что имеется в виду

2024-12-01 06:19 UTC, PuccaGTS approved these changes
гуд

2024-12-01 06:19 UTC, closed without merging