Task 7 initial commit
KFalcon2022/intensive-tasks-2024 pull request #449
Opened 2024-11-27 15:16 UTC by HellRus

2024-11-28 20:44 UTC, KFalcon2022 requested changes

2024-11-28 20:44 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter2/task7/Task7.java
> +        for (int i = 1; i < n; i++) {
по условию задачи нужно найти наибольшее число, но ты начинаешь искать с наименьших. Зачем?) Мало того, что это заставляет делать больше итераций, это еще и заставляет вводить понятие максималньой суммы и производить сравнения

К слову, 1000000 должно быть включено в расчет, если это не было умышленной оптимизацией

2024-11-28 20:44 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter2/task7/Task7.java
> +            int secondNumber = getDividers(i);
не самое удачное название переменной. Какое-то второе число. Какое? Для чего оно нужно?)

сумма делителей или претендент на дружественную пару - более информативные варианты

2024-11-28 20:44 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter2/task7/Task7.java
> +    static int getDividers(int d) {
непонятное название переменной. Ну и метод возвращает совсем не делители, а их сумму:)
P.S. Делитель в нужном тебе смысл - divisor

2024-11-28 20:44 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter2/task7/Task7.java
> +        for (int i = 1; i < limiter; i++) {
Можно оптимизировать. 
1. Вряд ли у числа есть целые делители, которые больше, чем limiter / 2
2. Чтобы перебрать все делители достаточно пройтись до sqrt(d). Ведь получая один делитель ты автоматом получаешь и второй - в виде результата выражения

2024-11-28 20:44 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter2/task7/Task7.java
> +        for (int i = 1; i < limiter; i++) {
Решение рабочее, но замечания предлагаю добить

2024-11-29 11:57 UTC, HellRus commented on src/main/java/com/walking/intensive/chapter2/task7/Task7.java
> +        for (int i = 1; i < limiter; i++) {
Спасибо, поправил замечания

2024-11-30 15:21 UTC, KFalcon2022 approved these changes

2024-11-30 15:21 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter2/task7/Task7.java
> +                sum += d / i;
Если d будет иметь целый корень - будет работать некорректно. Условно, для 9 этот код дважды запишет в делители 3, насколько вижу

2024-11-30 15:21 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter2/task7/Task7.java
> +    static int getDivisorSum(int d) {
непонятное название параметра

2024-11-30 15:21 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter2/task7/Task7.java
> +    }
Замечания считаю незначительными и рекомендую поправить самостоятельно. Задача зачтена авансом:)

2024-11-30 15:21 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter2/task7/Task7.java
> +        for (int i = 2; i < limiter; i++) {
Почему не учитываем limiter в возможные делители?

2024-11-30 15:21 UTC, closed without merging