Task10
KFalcon2022/intensive-tasks-2024 pull request #455
Opened 2024-11-27 19:13 UTC by michael-altf4

2024-11-30 16:24 UTC, KFalcon2022 requested changes

2024-11-30 16:24 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter2/task10/Task10.java
> +        if (inputString == null || inputString.length() < 2) return false;
Тело if всегда должно быть заключено в {}. Даже если оно однострочное

2024-11-30 16:24 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter2/task10/Task10.java
> +                .replaceAll("\\s", "").toLowerCase();
Можно просто оставить только валидные символы, без этих извращений. Опять же, если юзаешь регекс - зачем два replaceAll()? Вполне можно объединить в один

Не стоит использовать инструменты, принцип работы которых не понимаешь

2024-11-30 16:24 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter2/task10/Task10.java
> +        return normalized.contentEquals(new StringBuilder(normalized).reverse());
Формально задачу ты решил. А смысл?) Она ведь на закрепление работы с циклами, а не на проверку палиндрома как такового

2024-12-01 11:30 UTC, michael-altf4 commented on src/main/java/com/walking/intensive/chapter2/task10/Task10.java
> +                .replaceAll("\\s", "").toLowerCase();
Честно сказать java слабо понимаю. Что-то получается кодить, каким-то образом. Так, согласен, нужно было задать диапазон разрешенных символов если через регулярку

2024-12-01 11:31 UTC, michael-altf4 commented on src/main/java/com/walking/intensive/chapter2/task10/Task10.java
> +        if (inputString == null || inputString.length() < 2) return false;
Да, помню. Упускаю с виду нюанс

2024-12-01 11:32 UTC, michael-altf4 commented on src/main/java/com/walking/intensive/chapter2/task10/Task10.java
> +        return normalized.contentEquals(new StringBuilder(normalized).reverse());
Переделал в перебор строки на символы

2024-12-02 18:42 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter2/task10/Task10.java
> +                .replaceAll("\\s", "").toLowerCase();
Не знаешь, как через регулярку - лупи через цикл, из входящей строки собирая строку без лишних символов:)

2024-12-02 18:44 UTC, KFalcon2022 requested changes

2024-12-02 18:44 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter2/task10/Task10.java
> +        String afterReverse = new StringBuilder(normalized).reverse().toString();
С reverse() задачу не зачту:) можно за половину прохода цикла сделать полностью императивно)

2024-12-02 23:10 UTC, michael-altf4 commented on src/main/java/com/walking/intensive/chapter2/task10/Task10.java
> +        String afterReverse = new StringBuilder(normalized).reverse().toString();
Первый цикл - очищаем от "грязи". Второй цикл - реверсируем.

Если в одном цикле, там проблема с нечетными палиндромами и ветвлений if получится прилично

2024-12-03 19:22 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter2/task10/Task10.java
> +        String afterReverse = new StringBuilder(normalized).reverse().toString();
не так уж и сложно:)

2024-12-03 19:25 UTC, KFalcon2022 approved these changes
Стилистические замечания просьба добить самостоятельно. Задача зачтена небольшим авансом)

2024-12-03 19:25 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter2/task10/Task10.java
> +        for (int i = 0; i <palindrome.length(); i++) {
потерял пробел после <

2024-12-03 19:25 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter2/task10/Task10.java
> +        for (int i = normalized.length()-1; i >= 0; i--) {
пробелы вокруг "-" потерял:)

2024-12-03 19:25 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter2/task10/Task10.java
> +            if (Character.isLetter(palindrome.charAt(i))) {
palindrome.charAt(i) логичнее в переменную вынести - чего ради дважды символ извлекать. И выглядит громоздко:)

2024-12-03 19:26 UTC, closed without merging