Task7
KFalcon2022/intensive-tasks-2024 pull request #466
Opened 2024-11-28 11:16 UTC by ruarchie

2024-11-29 21:38 UTC, EvgeneZhurov requested changes

2024-11-29 21:38 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter2/task7/Task7.java
> +        do {
Конструкция do while редкая и не подходит в этой задаче. Вы вводите счетчик и знаете количество итераций. Для этого лучше использовать for.

2024-11-29 21:38 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter2/task7/Task7.java
> +
можно не писать пустую строку

2024-11-30 15:53 UTC, ruarchie commented on src/main/java/com/walking/intensive/chapter2/task7/Task7.java
> +        do {
Не соглашусь с Вами. В данном случае цикл do завершиться при нахождении максимального дружественного числа. При использовании for мы получим лишние итерации для нахождения дружественных чисел, которые уже не нужны, т.к. мы ищем максимальные.

2024-11-30 17:11 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter2/task7/Task7.java
> +        do {
Слово "завершится" пишется без мягкого знака, потому что отвечает на вопрос: что сделает.

2024-11-30 17:18 UTC, EvgeneZhurov approved these changes

2024-11-30 17:18 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter2/task7/Task7.java
> +        int sumDividers1;
Если при создании переменной ей не присваивается значение, это может указывать на то, что ей здесь не место. Необходимо стремиться использовать минимальную область видимости. То есть внутри for - не бойтесь создавать переменные внутри массива, это не повлияет существенно на скорость работы программы или память.

2024-11-30 17:18 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter2/task7/Task7.java
> +
Можно не ставить пустую строку в самом начале метода

2024-11-30 17:18 UTC, closed without merging