Task6
KFalcon2022/intensive-tasks-2024 pull request #472
Opened 2024-11-28 19:07 UTC by IVRomash

2024-11-29 00:50 UTC, KateKhodko requested changes

2024-11-29 00:50 UTC, KateKhodko commented on src/main/java/com/walking/intensive/chapter2/task6/Task6.java
> +        if (m <= 0 || n <= 0) {
По условию задачи алгоритм Евклида делаем через рекурсию, остальное гуд

2024-12-02 17:53 UTC, KateKhodko approved these changes

2024-12-02 17:53 UTC, KateKhodko commented on src/main/java/com/walking/intensive/chapter2/task6/Task6.java
> +        if (m%n == 0) {
Не забывай прожимать форматирование перед тем как пушить

2024-12-02 17:53 UTC, closed without merging

2024-12-02 18:06 UTC, IVRomash commented on src/main/java/com/walking/intensive/chapter2/task6/Task6.java
> +        if (m%n == 0) {
Извиняюсь, в следующий раз исправлюсь