Task 6
KFalcon2022/intensive-tasks-2024 pull request #473
Opened 2024-11-28 20:14 UTC by 0rloff

2024-11-29 00:25 UTC, KateKhodko requested changes

2024-11-29 00:25 UTC, KateKhodko commented on src/main/java/com/walking/intensive/chapter2/task6/Task6.java
> +
По условию надо реализовать алгоритм Евклида через рекурсию, в остальном все гуд)

2024-11-29 00:27 UTC, KateKhodko requested changes

2024-11-29 00:27 UTC, KateKhodko commented on src/main/java/com/walking/intensive/chapter2/task6/Task6.java
> +        if (!(isValidParams(m, n))){
Не забывай про форматирование, тут и далее по коду скобка `{ ` прилипла)
CTRL + ALT + L (Windows, Linux), ⌘ + ⌥ + L (Mac)

2024-11-29 12:24 UTC, 0rloff commented on src/main/java/com/walking/intensive/chapter2/task6/Task6.java
> +
Спасибо, исправил

2024-12-01 14:16 UTC, KateKhodko approved these changes

2024-12-01 14:16 UTC, closed without merging