Task10
KFalcon2022/intensive-tasks-2024 pull request #477
Opened 2024-11-29 06:34 UTC by PabloQuetzalcoatl

2024-11-30 16:21 UTC, KFalcon2022 requested changes

2024-11-30 16:21 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter2/task10/Task10.java
> +        if (inputString == null){
Не хватает пробела перед {. Ниже тоже встречаются места с дефицитом пробелов. Автоматическое форматирование кода - ctrl+alt+L

2024-11-30 16:21 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter2/task10/Task10.java
> +       if (inputString.length()<2){
можно объединить в одно условие с предыдущим

2024-11-30 16:21 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter2/task10/Task10.java
> +        return inputString.replace(symbol, "");
если полез в методы строк = лучше познакомься с replaceAll и регулярными выражениями. Можно просто оставить ТОЛЬКО нужные символы в одну строку. Либо воспользуйся иным способом получить валидную строку:)

Ну и сам метод deleteSymbol() выглядит избыточным

2024-12-02 19:01 UTC, KFalcon2022 approved these changes

2024-12-02 19:01 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter2/task10/Task10.java
> +        inputString = inputString.replaceAll("[\\p{Punct}\s]", "");
что б ты еще понимал, как это работает:)

2024-12-02 19:01 UTC, closed without merging

2024-12-02 19:38 UTC, PabloQuetzalcoatl commented on src/main/java/com/walking/intensive/chapter2/task10/Task10.java
> +        inputString = inputString.replaceAll("[\\p{Punct}\s]", "");
Если у вас есть проблема, которую вы хотите решить с помощью регулярных выражений, то.....
Теперь у вас две проблемы.