Task1
KFalcon2022/intensive-tasks-2024 pull request #48
Opened 2024-11-17 13:49 UTC by Evgencms

Реализован метод getAgeString()

2024-11-17 15:22 UTC, PuccaGTS requested changes

2024-11-17 15:22 UTC, PuccaGTS commented on src/main/java/com/walking/intensive/chapter1/task1/Task1.java
> +}
Сработал чекстайл по причине:
`Error: eckstyle] [ERROR] /home/runner/work/intensive-tasks-2024/intensive-tasks-2024/src/main/java/com/walking/intensive/chapter1/task1/Task1.java:1: File does not end with a newline. [NewlineAtEndOfFile]`

Поправьте, пожалуйста

2024-11-17 15:22 UTC, PuccaGTS commented on src/main/java/com/walking/intensive/chapter1/task1/Task1.java
> +        if (age % 100 == 11 || age % 100 == 12 || age % 100 == 13 || age % 100 == 14) {
Нет необходимости постоянно писать age % 100, когда это можно унести в отдельную переменную.

2024-11-17 15:22 UTC, PuccaGTS commented on src/main/java/com/walking/intensive/chapter1/task1/Task1.java
> +        } else if (age % 10 == 2 || age % 10 == 3 || age % 10 == 4) {
Аналогичная ситуация с age %10

2024-11-17 17:37 UTC, PuccaGTS requested changes
Давайте добьем тесты.

2024-11-17 17:37 UTC, PuccaGTS commented on src/main/java/com/walking/intensive/chapter1/task1/Task1.java
>      static String getAgeString(int age) {
Теперь не прошли тесты по негативному сценарию, в условии есть про то, что может быть некорректный ввод возраста.

Вы можете сами запускать тесты для своего задания, достаточно перейти в папку test, там под номером задания лежат тестовые классы, которые вы можете прогнать.

2024-11-17 19:34 UTC, Evgencms commented on src/main/java/com/walking/intensive/chapter1/task1/Task1.java
>      static String getAgeString(int age) {
Спасибо.
Добавил правки, тест прошёл.

2024-11-18 04:49 UTC, PuccaGTS approved these changes

2024-11-18 04:49 UTC, closed without merging