Task7
KFalcon2022/intensive-tasks-2024 pull request #481
Opened 2024-11-29 15:16 UTC by 0rloff

2024-11-30 16:14 UTC, KFalcon2022 requested changes

2024-11-30 16:14 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter2/task6/Task6.java
> +        if (!(isValidParams(m, n))){
Потерян пробел перед {. В задаче есть и другие недочеты, связанные с лишними/недостающими пробелами. Автоматическое форматирование кода - ctrl+alt+L

Также лишние скобки вокруг `isValidParams(m, n)`

2024-11-30 16:14 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter2/task6/Task6.java
> +        return n * m / getGcd(m, n);
так можно, но неинтересно. Опционально, предлагаю найти иной алгоритм, без использования НОД

2024-11-30 16:14 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter2/task6/Task6.java
> +        return (m > 0 && n > 0);
этого файла в ПР быть не должно

2024-11-30 16:14 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter2/task7/Task7.java
> +            if (i < sumOne && sumOne < n) {
переусложненное условие. Для любого sumOne < n никогда не будет справедливо `i < sumOne` - иначе бы ты нашел его на более ранней итерации цикла

2024-11-30 16:14 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter2/task7/Task7.java
> +            int sumOne = getDivisorsSum(i);
Не слишком удачное название переменной. Во-первых, непонятно, что за сумма (при инициализации понятно, но зачем заставлять человека помнить это далее по коду, если можно отразить в названии переменной?)

2024-11-30 16:14 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter2/task7/Task7.java
> +                int sumTwo = getDivisorsSum(sumOne);
избыточная переменная, на мой взгляд. Можно прям в условии if метод вызвать

2024-11-30 16:14 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter2/task7/Task7.java
> +        int maxDivisor = (int) Math.sqrt(a);
если у числа целый корень - он должен быть учтен в сумме делителей

2024-11-30 17:11 UTC, 0rloff commented on src/main/java/com/walking/intensive/chapter2/task6/Task6.java
> +        return (m > 0 && n > 0);
Файл Task6 задублировал из другой задачи случайно. Убрал

2024-11-30 17:27 UTC, 0rloff commented on src/main/java/com/walking/intensive/chapter2/task6/Task6.java
> +        return n * m / getGcd(m, n);
Спасибо, добавлю решение в PR задачи Task6, как раз еще не закрыт)

2024-12-02 18:37 UTC, KFalcon2022 approved these changes

2024-12-02 18:37 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter2/task7/Task7.java
> +                if (getDivisorsSum(firstFriendDivisorsSum) == i) {
Можно обхединить в одно условие. Мелкое замечание

2024-12-02 18:37 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter2/task7/Task7.java
> +        for (int i = 2; i <= maxDivisor; i++) {
Если у `a` целый корень - он будет учтен дважды

2024-12-02 18:37 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter2/task7/Task7.java
> +    }
Замечания легкие для самостоятельного исправления. Задача зачтена небольшим авансом:)

2024-12-02 18:37 UTC, closed without merging