Task9
KFalcon2022/intensive-tasks-2024 pull request #489
Opened 2024-11-30 13:57 UTC by LVictor-SF

2024-12-01 16:40 UTC, KFalcon2022 requested changes

2024-12-01 16:40 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter2/task9/Task9.java
> +            lastLine += (k + " ");
Лишние скобки

2024-12-01 16:40 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter2/task9/Task9.java
> +            for (int j = 0; j < amountOfSpaces(lineNumber, n); j++) {
Весь цикл выглядит как претендент на выделение в отдельный метод, возвращающий строку с пробелами

2024-12-01 16:40 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter2/task9/Task9.java
> +                line += k + " ";
Пробел в конце строки избыточен

2024-12-01 16:40 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter2/task9/Task9.java
> +    public static int amountOfSpaces(int a, int b) {
Названия прааметров должны быть осмыслены

2024-12-01 16:40 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter2/task9/Task9.java
> +            k = k * (a - i) / i;
Фактически повторять сбор всей строки, чтобы потом вычислить длину и вновь ее собирать (уже в коде `getPascalTriangle()`) - достаточно странная затея

2024-12-01 16:40 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter2/task9/Task9.java
> +        for (int i = 1; i < b; i++) {
Ты этот расчет производишь в методе, который вызывается во вложенном цикле. При чем от итерации цикла результат не зависит. Не логичнее вычислить единоразово и сохранить в переменную?

2024-12-10 12:02 UTC, LVictor-SF commented on src/main/java/com/walking/intensive/chapter2/task9/Task9.java
> +    public static int amountOfSpaces(int a, int b) {
Проблема в отсутствии глагола? исправил это в одном из предыдущих пунктов, а так, он возвращает количество  пробелов перед строкой. Всё равно что-то не так с названием?

2024-12-10 19:59 UTC, LVictor-SF commented on src/main/java/com/walking/intensive/chapter2/task9/Task9.java
> +                line += k + " ";
Мне в голову приходит добавить в for  условие на равенство lineNumber и тогда добавлять k без пробела, но это лишнее действие для каждой итерации. Второй вариант: сделать равенство строгим и добавить k после цикла. Есть ли варианты получше?

2024-12-14 14:08 UTC, KFalcon2022 requested changes
Выглядит, будто мы на финишной прямой

2024-12-14 14:08 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter2/task9/Task9.java
> +        int k = 1;
Что означает k?

2024-12-14 14:08 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter2/task9/Task9.java
> +    public static String getLineOfPascalTriangle(int lineNumber, int lastLineLength) {
getPascalTriangleLine. of - бесполезная частица в большинстве случаев. Заменяемая перестановкой слов

2024-12-14 14:08 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter2/task9/Task9.java
> +    public static int getAmountOfSpaces(int lineNumber, int lastLineLength) {
getSpaceAmount

2024-12-14 14:08 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter2/task9/Task9.java
> +        result += (line + k + "\n");
Чем этот код отличается от того, с которого начинается метод? Если эти блоки кода логически завершенные и фактически идентичные - стоит вынести в метод и не дублировать

2024-12-14 14:08 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter2/task9/Task9.java
> +        result += (line + k + "\n");
И лишние скобки после =

2024-12-14 14:09 UTC, KFalcon2022 requested changes

2024-12-14 14:09 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter2/task9/Task9.java
> +            line += (k + " ");
зачем скобки?

2024-12-14 14:09 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter2/task9/Task9.java
> +            k = k * (lineNumber - i) / i;
насколько я вижу, это уже третье дублирование одного и того же кода:)

2024-12-17 21:14 UTC, KFalcon2022 approved these changes
Отлично

2024-12-17 21:14 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter2/task9/Task9.java
> +            for (int j = 0; j < amountOfSpaces(lineNumber, n); j++) {
Не исправлено

2024-12-17 21:15 UTC, closed without merging