Task6
KFalcon2022/intensive-tasks-2024 pull request #496
Opened 2024-11-30 15:24 UTC by stillwearit

2024-12-01 16:24 UTC, KFalcon2022 requested changes

2024-12-01 16:24 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter2/task6/Task6.java
> +    static boolean isNumberNegative (int n, int m) {
Лишний пробел перед (

Кроме того, методы, которые нужны только внутри класса, должны располагаться ниже методов, которые будут вызываться извне.

ПОсле знакомства с модификаторами доступа эта концепция станет понятнее

2024-12-01 16:24 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter2/task6/Task6.java
> +    static boolean isNumberNegative (int n, int m) {
Неудачное название метода. Ты проверяешь несколько чисел, что не соответствует названию. Вполне допустимо более общее именование для таких случаев. Скажем, `isValid()`. Или `isInvalid()` (менее предпочтительный вариант)

2024-12-01 16:24 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter2/task6/Task6.java
> +            m += x;
у переменной должно быть одно назначение. Если m - это число, для которого надо найти НОК, то эту же переменную не стоит использовать для хранения НОК

2024-12-01 16:24 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter2/task6/Task6.java
> +            return getGcdIfFirstNumberIsBigger(m, n);
странное название

2024-12-01 16:24 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter2/task6/Task6.java
> +        if (m > n) {
Можно заменить на тернарный оператор

2024-12-01 16:24 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter2/task6/Task6.java
> +        }
Из-за отсутствия пустой строки код сливается в одно полотно

2024-12-01 16:24 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter2/task6/Task6.java
> +    }
Можно описать лаконичнее

2024-12-01 16:24 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter2/task6/Task6.java
> +        int x = b;
имя переменной должно быть осмысленным

2024-12-01 16:24 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter2/task6/Task6.java
> +    static int getGcdIfFirstNumberIsBigger (int a, int b) {
Если уж используются n и m для обозначения входных чисел, зачем усложнять и вводить еще 'a' и 'b'?

2024-12-03 10:49 UTC, stillwearit commented on src/main/java/com/walking/intensive/chapter2/task6/Task6.java
> +    }
что именно?

2024-12-03 11:05 UTC, stillwearit commented
Не понимаю, что нужно сделать с алгоритмом Евклида, остальное исправила.

2024-12-03 19:23 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter2/task6/Task6.java
> +    }
Алгоритм Евклида. Правда, вероятно придется использовать перегрузку/иным образом вынести рекурсивный метод отдельно от объявленного

2024-12-03 19:27 UTC, KFalcon2022 approved these changes
Последние замечания мелкие, предлагаю устранить самостоятельно. Задача зачтена

2024-12-03 19:27 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter2/task6/Task6.java
> +        int Lcm = m;
Переменные именуются с маленькой буквы

2024-12-03 19:27 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter2/task6/Task6.java
> +        return (m > n ? getGcdSet(m, n) : getGcdSet(n, m));
Скобки лишние

2024-12-03 19:28 UTC, closed without merging