Task 1
KFalcon2022/intensive-tasks-2024 pull request #500
Opened 2024-11-30 17:21 UTC by vitalykom

2024-11-30 17:29 UTC, EvgeneZhurov requested changes

2024-11-30 17:29 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task1/Task1.java
> +        if (age < 0) {
просьба добавить в валидацию ограничение по возрасту не более 127 лет

2024-11-30 17:29 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task1/Task1.java
> +        } else if (age > 4 && age <= 20 || age % 100 > 4 && age % 100 <= 20 || age % 10 == 0 || age % 10 >= 5 && age % 10 <= 9) {
после if не пишут else

2024-11-30 17:29 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task1/Task1.java
> +        } else if (age > 4 && age <= 20 || age % 100 > 4 && age % 100 <= 20 || age % 10 == 0 || age % 10 >= 5 && age % 10 <= 9) {
age % 10 <= 9 идея подсвечивает варнинг, не игнорируйте его. Остаток от деления на 10 всегда меньше или равно 9, условие всегда будет true, вот и подсвечивает.

2024-11-30 17:29 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task1/Task1.java
> +            ageString = " лет";
лучше сразу сделать return. Просьба поправить везде в коде.

2024-11-30 17:29 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task1/Task1.java
> +
можно не ставить пустую строку сразу после создания метода

2024-11-30 17:29 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task1/Task1.java
> +        }
лучше поставить пустую строку перед return отделяя блоки кода пустыми строками с обеих сторон, если это не самое начало или конец метода.

2024-12-03 08:54 UTC, vitalykom commented on src/main/java/com/walking/intensive/chapter1/task1/Task1.java
> +        } else if (age > 4 && age <= 20 || age % 100 > 4 && age % 100 <= 20 || age % 10 == 0 || age % 10 >= 5 && age % 10 <= 9) {
Не понял, почему не пишут?

2024-12-04 06:54 UTC, EvgeneZhurov approved these changes
Лучше отделять блоки кода (например if ) пустыми строками с обеих сторон, если это не начало или конец метода. Так читается легче.

2024-12-04 06:54 UTC, closed without merging