task4
KFalcon2022/intensive-tasks-2024 pull request #501
Opened 2024-11-30 19:07 UTC by AntonNikolaevich

2024-12-01 16:07 UTC, KFalcon2022 requested changes

2024-12-01 16:07 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter1/task4/Task4.java
> +        double x1;
Переменные обявляются как можно ближе к месту их использования

2024-12-01 16:07 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter1/task4/Task4.java
> +        } else if (discriminant == 0 || a == 0) {
избыточное использование else. Этот if и так не будет проверен, если if выше выполнится - ведь в нем находится return

2024-12-01 16:07 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter1/task4/Task4.java
> +            x1 = a == 0 ? (-c / b) : (-b / 2 * a);
Избыточные скобки

2024-12-01 16:07 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter1/task4/Task4.java
> +        } else if (discriminant == 0 || a == 0) {
И не логичнее вынести обработку для a == 0 отдельно, еще до расчета дискриминанта? Ты ведь все равно строчкой ниже делаешь разную обработку для `D == 0` и `a == 0`

2024-12-01 16:07 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter1/task4/Task4.java
> +
лишняя пустая строка

2024-12-01 16:07 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter1/task4/Task4.java
> +
лишняя пустая строка

2024-12-02 15:17 UTC, AntonNikolaevich commented on src/main/java/com/walking/intensive/chapter1/task4/Task4.java
> +        } else if (discriminant == 0 || a == 0) {
да, просто с отдельной проверкой два одинаковых return получается. Думал, это неправильно

2024-12-02 19:00 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter1/task4/Task4.java
> +        } else if (discriminant == 0 || a == 0) {
это не так страшно, как переусложнение условий

2024-12-02 19:03 UTC, closed without merging