Task2
KFalcon2022/intensive-tasks-2024 pull request #503
Opened 2024-11-30 20:08 UTC by rekynkovav

2024-12-01 16:00 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter1/task2/Task2.java
> +        int numberFlatInHouse = 4; // количество квартир
Комментарии (не считая Java-док) уместны только в ситуациях, когда логика непрозрачна или алгоритм запутан и может быть не очевиден

2024-12-01 16:01 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter1/task2/Task2.java
> +        if (numberEntranceHouse > 1) { // какой этаж
Чем логика этого if не укладывается в то, что описано в else?

2024-12-01 16:01 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter1/task2/Task2.java
> +        if (numberEntranceHouse > 1) { // какой этаж
Иными словами, сам if-else выглядит избыточным.

2024-12-01 16:02 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter1/task2/Task2.java
> +        if (flatNumber == 2 | flatNumber % numberFlatInHouse == 2) {
Первое условие вполне укладывается в логику второго. А для единственного условия с несколькими вариантами обработки есть более подходящая конструкция, нежели if-else

2024-12-01 16:02 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter1/task2/Task2.java
> +        } else {
избыточный else. Ничего не изменится, если его убрать

2024-12-03 18:47 UTC, rekynkovav commented on src/main/java/com/walking/intensive/chapter1/task2/Task2.java
> +        if (numberEntranceHouse > 1) { // какой этаж
непойму на что ты направляешь, переделать алгоритм в одно условие? у меня тут в else всегда когда 1 подъезд, всё остальное через if проходит

2024-12-05 20:04 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter1/task2/Task2.java
> +        if (numberEntranceHouse > 1) { // какой этаж
Так расчет в else для 1 подъезда приведет ровно к тем же результатам

2024-12-05 20:22 UTC, KFalcon2022 requested changes

2024-12-14 13:27 UTC, KFalcon2022 commented
ПР закрыт, т.к. не обновлялся более недели. При необходимости повторной проверки просьба открыть новый ПР

2024-12-14 13:27 UTC, closed without merging