Task 2
KFalcon2022/intensive-tasks-2024 pull request #509
Opened 2024-12-01 11:51 UTC by Showmeyrcode

2024-12-01 15:53 UTC, KFalcon2022 requested changes

2024-12-01 15:53 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter1/task2/Task2.java
> +        return flatNumber + " кв - " + currentEntrance + " подъезд, " + flatFloor + " этаж, " + flatElevatorLocation + " от лифта, " + flatFloorLocation;
Строка код должна содержать не более 120 символов. Считается, что именно столько помещается в один экран при стандартных настройках

2024-12-01 15:53 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter1/task2/Task2.java
> +            default -> "";
я бы предложил помещать в default какое-либо сообщение об ошибке, это позволит более наглядно отобразить внештатную ситуацию в результирующей строке

2024-12-01 15:53 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter1/task2/Task2.java
> +        int flatFloor = (flatNumber - (flatEntranceAmount * (currentEntrance - 1))) / 4; // Этаж
избыточные комментарии вредят читабельности кода. То, что это расчет этажа понятно и из названия переменной

2024-12-01 15:53 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter1/task2/Task2.java
> +        return flatNumber + " кв - " + currentEntrance + " подъезд, " + flatFloor + " этаж, " + flatElevatorLocation + " от лифта, " + flatFloorLocation;
Чуть что, при переносе на новую строку оператор ("+") должен размещаться на новой строке. Альтернативно, можно посмотреть в сторону метода `String#formatted()`

2024-12-01 15:53 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter1/task2/Task2.java
> +        if (flatNumber <= flatEntranceAmount) {
Кажется, текущее условие вполне укладывается в логику, описанную в else

2024-12-01 15:53 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter1/task2/Task2.java
> +            if (flatNumber % flatEntranceAmount == 0) {
лучше использовать тернарный оператор

2024-12-01 16:28 UTC, Showmeyrcode reviewed
Fixed

2024-12-01 16:30 UTC, Showmeyrcode commented
Исключение в default ветку idea предложила подсветила докинуть. Чекал при запуске, чтобы работало и забыл перед коммитом поменять на что-то своё ((

2024-12-02 18:56 UTC, KFalcon2022 approved these changes
Замечание небольшие, советую исправить для себя. Задача зачтена

2024-12-02 18:56 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter1/task2/Task2.java
> +        int currentEntrance = flatNumber % flatAmount == 0 ? flatNumber / flatAmount : (flatNumber / flatAmount) + 1;
Тернарки со сложными расчетами или просто формулами лучше разноси на несколько строк - так лучше читается. Например:
```java
int currentEntrance = flatNumber % flatAmount == 0
    ? flatNumber / flatAmount
    : (flatNumber / flatAmount) + 1;
```

2024-12-02 18:56 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter1/task2/Task2.java
> +        int currentEntrance = flatNumber % flatAmount == 0 ? flatNumber / flatAmount : (flatNumber / flatAmount) + 1;
Ну и скобки лишние

2024-12-02 18:56 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter1/task2/Task2.java
> +        int flatFloor = (flatNumber - (flatAmount * (currentEntrance - 1))) / 4;
лишние скобки вокруг `flatAmount * (currentEntrance - 1)`

2024-12-02 18:56 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter1/task2/Task2.java
> +            default -> throw new IllegalStateException("Unexpected value: " + flatNumber % 4);
в общем-то, так оно и было бы в промышленном коде. Но т.к. исключения не проходили - в интенсиве не требуем

На будущее - не проблема добавить лишний коммит. Я-то смотрю глобальные отличия между ветками, а не каждый отдельный коммит

2024-12-02 18:56 UTC, closed without merging