Task 1
KFalcon2022/intensive-tasks-2024 pull request #521
Opened 2024-12-01 18:48 UTC by Lizasha

2024-12-01 18:53 UTC, EvgeneZhurov requested changes

2024-12-01 18:53 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task1/Task1.java
> +        } else if (lastOneDigit == 1) {
после if не ставят else. Либо будет выход из метода, либо и без else метода продолжит выполняться. Просьба поправить везде в методе.

2024-12-01 18:53 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task1/Task1.java
> +        } else return "Вам " + age + " лет";
у Вас два return для слова "лет". Просьба создать такие логические условия, чтобы на каждое слово было ровно по одному return

2024-12-01 18:53 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task1/Task1.java
> +        if (age < 0) return "Incorrect input.";
Просьба ставить {} даже если в условии одна строка кода. Так принято в местном комьюнити.

2024-12-01 18:53 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task1/Task1.java
> +        if (age < 0) return "Incorrect input.";
просьба так же добавить ограничение по возрасту не превышающее 127 лет.

2024-12-01 20:13 UTC, Lizasha commented on src/main/java/com/walking/intensive/chapter1/task1/Task1.java
> +        if (age < 0) return "Incorrect input.";
Есть такой тест который проверяет число 19875. Ожидаемый результат должен быть "Некорректный ввод", или все же Вам 19875 лет ?

Результат теста в консоли: 

Expected :Вам 19875 лет
Actual   :Некорректный ввод

2024-12-01 23:37 UTC, EvgeneZhurov requested changes

2024-12-01 23:37 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task1/Task1.java
> +            if (lastOneDigit == 1) {
двойные вложения не нужны в данной задаче.

2024-12-01 23:37 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task1/Task1.java
> +                defaultLine = " год";
лучше сразу делать return, просьба поправить везде в коде.

2024-12-01 23:37 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task1/Task1.java
> +        }
лучше поставить пустую строку после }

2024-12-01 23:37 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task1/Task1.java
> +        String defaultLine = " лет";
можно использовать return и тогда строка не понадобится.

2024-12-02 19:41 UTC, EvgeneZhurov requested changes

2024-12-02 19:41 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task1/Task1.java
> +        if ((lastTwoDigits >= 11 && lastTwoDigits <= 14) || lastOneDigit == 0 || lastOneDigit >= 5) {
есть лишние скобки

2024-12-02 19:41 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task1/Task1.java
> +        } else
после return не ставят else.

2024-12-02 19:41 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task1/Task1.java
> +
лишняя пустая строка

2024-12-03 20:18 UTC, closed without merging