Task11
KFalcon2022/intensive-tasks-2024 pull request #526
Opened 2024-12-02 07:14 UTC by gentrus

2024-12-02 19:10 UTC, KFalcon2022 requested changes

2024-12-02 19:10 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter3/task11/Task11.java
> +            if (array[i] < 0) {
Я бы валидацию в отдельный цикл вынес. Или даже в отдельный метод. Текущий подход рабочий, но он путает читателя - ты мешаешь валидацию с основной логикой метода. Когда можно дешево этого избежать - лучше избежать

2024-12-02 19:10 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter3/task11/Task11.java
> +                continue;
Вот это не очень хорошая идея. Исторически for применяется для ситуаций, когда точно известно число обрабатываемых итераций. Из чего следует, что `continue` и `break` с ним лучше не использовать. Тоже не ошибка, но принятые в индустрии практики лучше учитывать с порога

2024-12-02 19:10 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter3/task11/Task11.java
> +        return result;
Алгоритм не самый оптимальный, но если нет идей, как улучшить - пойдет

2024-12-03 06:13 UTC, gentrus commented on src/main/java/com/walking/intensive/chapter3/task11/Task11.java
> +        return result;
То есть можно обойтись без 3-х вложенных друг в друга циклов?

2024-12-03 19:22 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter3/task11/Task11.java
> +        return result;
Недавно кто-то кидал решение в один цикл, кажется:)

2024-12-03 19:34 UTC, KFalcon2022 approved these changes
Замечания в основном стилистические. Задача в пределах интенсива засчитана. Если интересно - маякни в личку, подумаем, как довести до ума https://t.me/ironicMotherfucker

2024-12-03 19:34 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter3/task11/Task11.java
> +        for (int i = 0; i < array.length; ) {
Я в прошлой итерации писал, что for принято использовать для заранее известного числа итераций. Одно из следствий - не принято изменение итератора вне головы цикла, шаг принят стандартным (++ или --). Здесь это, очевидно, не соблюдается:)

Все еще не является ошибкой, но в реальном проекте я такой код не пропустил бы на ревью

2024-12-03 19:34 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter3/task11/Task11.java
> +    static boolean checkArray(int[] array) {
булеан-методы все-таки принято именовать с is. Например, при таком именовании ты почти гарантированно дал бы более понятное название. Сейчас непонятно, что мы проверяем, как проверяем, зачем проверяем

2024-12-03 19:34 UTC, closed without merging