Task12
KFalcon2022/intensive-tasks-2024 pull request #530
Opened 2024-12-02 10:27 UTC by gentrus

2024-12-02 20:13 UTC, KateKhodko requested changes

2024-12-02 20:13 UTC, KateKhodko commented on src/main/java/com/walking/intensive/chapter3/task12/Task12.java
> +            if (s.equals("1") || s.equals("0")) {
Здесь лучше инвертировать условие, если нашли неккоректный символ, то сразу делаем return

2024-12-02 22:11 UTC, KateKhodko approved these changes

2024-12-02 22:11 UTC, closed without merging

2024-12-03 04:55 UTC, gentrus commented on src/main/java/com/walking/intensive/chapter3/task12/Task12.java
> +            if (s.equals("1") || s.equals("0")) {
Да я хотел, но не нашёл как сделать  "не равно 1 и 0", нашел только equals.