Task 1
KFalcon2022/intensive-tasks-2024 pull request #533
Opened 2024-12-02 11:51 UTC by quperino

2024-12-02 20:59 UTC, EvgeneZhurov requested changes

2024-12-02 20:59 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task1/Task1.java
> +        else if (lastInt == 1) {
после return не ставят else. Просьба поправить везде в коде.

2024-12-02 20:59 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task1/Task1.java
>          return null; // Заглушка. При реализации - удалить
это костыль, который не нужен. Предыдущий return не должен содержать логических условий. Поскольку не осталось альтернативы.

2024-12-02 20:59 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task1/Task1.java
> +        String ageInString = Integer.toString(age);
лучше не использовать строку для работы с числами. Быстрее работают математические операции, например деление или остаток от деления на 10 или 100. Просьба убрать.

2024-12-02 20:59 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task1/Task1.java
> +        char lastChar = ageInString.charAt(length-1);
есть правила оформления кода, просьба их перечитать. Перед отправкой код нужно выравнивать

2024-12-02 20:59 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task1/Task1.java
> +        if (age < 0) {
просьба добавить условие, что возраст не должен превышать 127 лет

2024-12-02 20:59 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task1/Task1.java
>      static String getAgeString(int age) {
Vam 9 let
Vam 10 let
Vam 11 god
Vam 12 goda
Vam 13 goda
Vam 14 goda
Vam 15 let
Vam 16 let
Vam 17 let

2024-12-02 23:21 UTC, quperino commented on src/main/java/com/walking/intensive/chapter1/task1/Task1.java
> +        else if (lastInt == 1) {
Исправил. Добавил строковую переменную. Теперь идет 2 проверки, если они выполняются, то код прерывается. Если нет, то далее идет проверка и в случае выполнения в строковую переменную записывается соответствующее значение и оно же затем возвращается.

2024-12-02 23:22 UTC, quperino commented on src/main/java/com/walking/intensive/chapter1/task1/Task1.java
> +        char lastChar = ageInString.charAt(length-1);
Исправил (убрал эти переменные из-за ненадобности).

2024-12-02 23:22 UTC, quperino commented on src/main/java/com/walking/intensive/chapter1/task1/Task1.java
> +        if (age < 0) {
Добавил.

2024-12-02 23:27 UTC, quperino commented on src/main/java/com/walking/intensive/chapter1/task1/Task1.java
>          return null; // Заглушка. При реализации - удалить
Исправил.

2024-12-03 20:25 UTC, EvgeneZhurov requested changes

2024-12-03 20:25 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task1/Task1.java
> +        return (vozrast);
скобки лишние.

2024-12-03 20:25 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task1/Task1.java
> +            vozrast = ("Vam " + age + " goda");
здесь нужно делать return

2024-12-03 20:25 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task1/Task1.java
> +            vozrast = "Vam " + age + " let";
здесь нужно делать return

2024-12-03 21:05 UTC, quperino commented on src/main/java/com/walking/intensive/chapter1/task1/Task1.java
> +        return (vozrast);
Избавился от этой переменной, скобки также убраны. Скобки должны отсутствовать именно при возврате переменной на 43-й строке? Или в целом после return скобки не нужно ставить?

2024-12-03 21:06 UTC, quperino commented on src/main/java/com/walking/intensive/chapter1/task1/Task1.java
> +            vozrast = ("Vam " + age + " goda");
Изменил на return.

2024-12-03 21:26 UTC, quperino commented on src/main/java/com/walking/intensive/chapter1/task1/Task1.java
>          else {
Исправил.

2024-12-03 21:26 UTC, quperino commented on src/main/java/com/walking/intensive/chapter1/task1/Task1.java
>          if ((age < 0) || (age > 127)) {
Избавился от скобок.

2024-12-03 21:30 UTC, EvgeneZhurov requested changes

2024-12-03 21:31 UTC, EvgeneZhurov requested changes

2024-12-03 21:31 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task1/Task1.java
> +        int age = 25;
Vam 100 let
Vam 101 god
Vam 102 goda
Vam 103 goda
Vam 104 goda
Vam 105 let
Vam 106 let
Vam 107 let
Vam 108 let
Vam 109 let
Vam 110 let
Vam 111 god
Vam 112 goda
Vam 113 goda
Vam 114 goda
Vam 115 let
Vam 116 let

2024-12-18 18:30 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task1/Task1.java
> +        return (vozrast);
Менье скобок - лучше читаемость. Когда не нужны символы не нужно их писать, в том числе в return

2024-12-18 18:33 UTC, closed without merging