Task 2
KFalcon2022/intensive-tasks-2024 pull request #534
Opened 2024-12-02 11:56 UTC by quperino

2024-12-02 21:05 UTC, EvgeneZhurov requested changes

2024-12-02 21:05 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task2/Task2.java
> +        else {
после return не ставят else.

2024-12-02 21:05 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task2/Task2.java
> +        int flatAmount = 4 * floorAmount * entranceAmount; // Количество квартир
Просьба ознакомиться с темой: магическое число java и создать константу под число 4

2024-12-02 21:05 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task2/Task2.java
>      static String getFlatLocation(int floorAmount, int entranceAmount, int flatNumber) {
System.out.println(getFlatLocation(-9, -3, 108));
108 kv - 238609293 pod''ezd, -2147483641 etazh, sprava ot lifta, vpravo

2024-12-02 21:05 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task2/Task2.java
> +            while (floorNumber > floorAmount) {
Это плохой способ посчитать entranceNumber.

2024-12-03 11:31 UTC, quperino commented on src/main/java/com/walking/intensive/chapter1/task2/Task2.java
> +        else {
Исправил.

2024-12-03 11:31 UTC, quperino commented on src/main/java/com/walking/intensive/chapter1/task2/Task2.java
> +        int flatAmount = 4 * floorAmount * entranceAmount; // Количество квартир
Создал.

2024-12-03 11:34 UTC, quperino commented on src/main/java/com/walking/intensive/chapter1/task2/Task2.java
>      static String getFlatLocation(int floorAmount, int entranceAmount, int flatNumber) {
Добавил допольнительную проверку.

2024-12-03 20:30 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task2/Task2.java
> +            while (floorNumber > floorAmount) {
когда вы придумаете простую формулу для подсчета, алгоритмическая сложность будет O(1), то есть не будет зависеть от входных данных, даже если они будут принимать максимально возможные значения, сейчас Ваша алгоритмическая сложность О(n), то есть для вычисления может потребоваться сравнимое количество с входными данными и будет считать неэффективно неэффективно.  Если требуется дальнейшее объяснение, то можно обсудить это в чате. Есть методы остатков от деления или округления в большую или меньшую сторону. Подумайте и предложите или обратитесь в общий чат за подсказкой.

2024-12-03 20:33 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task2/Task2.java
> +        if ((floorAmount > 0) && (entranceAmount > 0) && (flatAmount >= flatNumber) && (flatNumber > 0)) {
много лишних скобок. Код будет читаться легче если поменять логическое условие на противоположное и поменять блоки кода под if местами. Пропадет лишний уровень вложенности. Если не очень понятно кк это сделать, лучше напишите в чате.

2024-12-03 20:34 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task2/Task2.java
> +            if (flatNumber < 5) {
Не очень понимаю зачем нужна данная проверка и чем этот подъезд и этаж отличается от любого другого. Лучше просто выкинуть.

2024-12-18 18:35 UTC, EvgeneZhurov commented
просьба открыть новый PR, если требуется проверка.

2024-12-18 18:35 UTC, closed without merging