Task 3
KFalcon2022/intensive-tasks-2024 pull request #535
Opened 2024-12-02 11:57 UTC by quperino

2024-12-02 21:05 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task3/Task3.java
> +        if ((year % 400 == 0) || ((year % 4 == 0) && (year % 100 != 0))) {
много лишних ненужный скобок.

2024-12-02 21:06 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task3/Task3.java
> +        else if ((year % 400 != 0) || (year % 100 ==0)) {
после return не пишут else

2024-12-02 21:07 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task3/Task3.java
> +        else if ((year % 400 != 0) || (year % 100 ==0)) {
Просьба объединить все логические условия воедино используя && или || и тогда ветвление не понадобится. Можно вернуть само логическое условие.

2024-12-03 13:13 UTC, quperino commented on src/main/java/com/walking/intensive/chapter1/task3/Task3.java
> +        if ((year % 400 == 0) || ((year % 4 == 0) && (year % 100 != 0))) {
Убрал лишние скобки.

2024-12-03 13:14 UTC, quperino commented on src/main/java/com/walking/intensive/chapter1/task3/Task3.java
> +        else if ((year % 400 != 0) || (year % 100 ==0)) {
Убрал условный оператор if-else из кода.

2024-12-03 13:16 UTC, quperino commented on src/main/java/com/walking/intensive/chapter1/task3/Task3.java
> +        else if ((year % 400 != 0) || (year % 100 ==0)) {
Избавился от логических условий, т.к. убрал условный оператор if-else из кода. Сейчас идет возврат самого логического условия.

2024-12-03 20:55 UTC, EvgeneZhurov requested changes

2024-12-03 20:55 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task3/Task3.java
> +        return (year % 400 == 0) || (year % 4 == 0) && (year % 100 != 0);
прошу убрать все лишние скобки

2024-12-18 18:36 UTC, EvgeneZhurov commented
Просьба открыть новый PR, если требуется новая проверка.

2024-12-18 18:36 UTC, closed without merging