task1
KFalcon2022/intensive-tasks-2024 pull request #547
Opened 2024-12-02 16:08 UTC by mslark

2024-12-02 21:17 UTC, EvgeneZhurov requested changes

2024-12-02 21:17 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task1/Task1.java
> +        } else if (age % 10 == 1) {
после return не пишут else просьба везде поправить.

2024-12-02 21:17 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task1/Task1.java
> +        if (age % 10 == 0 | age % 10 > 4 | age % 100 > 4 & age % 100 < 21) {
между | и || есть разница. Узнайте какая и поправьте

2024-12-02 21:17 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task1/Task1.java
> +        if (age % 10 == 0 | age % 10 > 4 | age % 100 > 4 & age % 100 < 21) {
блоки кода if лучше отделять пустыми строками с обеих сторон, если это не начало или конец метода. Так читается легче.

2024-12-02 21:17 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task1/Task1.java
> +        if (age < 0) {
Просьба вставить условие по ограничению возраста не более 127 лет

2024-12-02 21:18 UTC, EvgeneZhurov commented
Не могу найти Вас в таблице: просьба написать мне в телегу: @ZhurovEV

2024-12-03 07:27 UTC, mslark commented
Внёс исправления

2024-12-03 20:24 UTC, closed without merging