Task 1
KFalcon2022/intensive-tasks-2024 pull request #55
Opened 2024-11-17 16:01 UTC by demidSWD

2024-11-17 16:05 UTC, ekolokolov requested changes
Не корректное форматирование.

2024-11-17 16:05 UTC, ekolokolov commented on build.gradle
> +        languageVersion = JavaLanguageVersion.of(23)
Не надо вот такое коммитить. поправь обратно пожалуйста.

2024-11-17 16:39 UTC, demidSWD commented
Ой, извиняюсь. Это было лишним)

2024-11-17 21:15 UTC, ekolokolov requested changes
Все отлично, только надо поправить форматирование.

2024-11-17 21:15 UTC, ekolokolov commented on src/main/java/com/walking/intensive/chapter1/task1/Task1.java
> +        if(age < 0) return "Некорректный ввод";
так делать нельзя. для if стейтмента запись всегда выглядит так. 
```
if ( age < 0 ) {
    return "Некорректный ввод";
}
```
Не смотря на то что технически это тоже будет работать - твой формат записи не подходит под общий code convention.

2024-11-18 19:41 UTC, ekolokolov requested changes
Ну форматирование вообще не поправлено. 
https://github.com/KFalcon2022/intensive-tasks-2024/blob/master/README.md
Вот тут правила форматирования.

2024-11-25 21:04 UTC, ekolokolov requested changes
Нужно еще обработать возраст больше 100 лет. 
Максимум вроде 127. можно до 150 для верности

2024-11-28 15:37 UTC, ekolokolov approved these changes
Зачтено

2024-11-28 15:37 UTC, closed without merging