Task 10
KFalcon2022/intensive-tasks-2024 pull request #554
Opened 2024-12-02 17:11 UTC by HellRus

2024-12-03 21:22 UTC, EvgeneZhurov requested changes

2024-12-03 21:22 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter2/task10/Task10.java
> +            backwardString = c + backwardString;
Не лучшая идея добавлять в строку буквы. Предлагаю переписать более эффективно. Пройдитесь двумя счетчиками внутри цикла while, одним слева направо, другим наоборот, сравнивая char попарно или перескакивая, если символ не является буквой. Тогда не придется создавать новых строк.

2024-12-04 14:00 UTC, HellRus commented on src/main/java/com/walking/intensive/chapter2/task10/Task10.java
> +            backwardString = c + backwardString;
Спасибо, попробовал уложиться в один цикл while

2024-12-04 14:05 UTC, EvgeneZhurov requested changes

2024-12-04 14:05 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter2/task10/Task10.java
> +        while (a < stringLength) {
Неверное логическое условие. Не требуется идти до самого конца слева направо, нужно заканчивать раньше.

2024-12-04 15:58 UTC, HellRus commented on src/main/java/com/walking/intensive/chapter2/task10/Task10.java
> +        while (a < stringLength) {
Действительно, теперь доходим только до середины строки

2024-12-04 16:00 UTC, EvgeneZhurov requested changes
неверно.

2024-12-04 16:13 UTC, HellRus commented
А если так? Вроде и дебагер и тесты всё показывают верно

2024-12-04 17:06 UTC, EvgeneZhurov requested changes

2024-12-04 17:06 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter2/task10/Task10.java
>      }
Не пройдет тест со следующей строкой:     String str = "               Решение неверное";
;)

2024-12-06 11:03 UTC, HellRus commented on src/main/java/com/walking/intensive/chapter2/task10/Task10.java
>      }
Действительно, немного поменял решение

2024-12-10 19:42 UTC, EvgeneZhurov approved these changes

2024-12-10 19:42 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter2/task10/Task10.java
> +        for (int a = 0, z = inputString.length() - 1; a < z; a++, z--) {
Цикл for лучше использовать когда Вы знаете количество итераций цикла, здесь логическое условие выхода из цикла a < z. While смотрится логичнее. Но не критично, алгоритм верный.

2024-12-10 19:42 UTC, closed without merging