task6
KFalcon2022/intensive-tasks-2024 pull request #555
Opened 2024-12-02 17:12 UTC by ilya-baykalov

2024-12-03 21:46 UTC, EvgeneZhurov requested changes

2024-12-03 21:46 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter2/task6/Task6.java
> +            return -1;
просьба выбросить вадидацию

2024-12-03 21:46 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter2/task6/Task6.java
> +        if (m == n) {
это выбросить

2024-12-03 21:46 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter2/task6/Task6.java
> +        if (m == 1 || n == 1) {
это выбросить

2024-12-03 21:46 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter2/task6/Task6.java
> +            return 2 * getGcd(m / 2, n / 2);
это выбросить

2024-12-03 21:46 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter2/task6/Task6.java
> +        if (m % 2 == 0) {
это бывросить

2024-12-03 21:46 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter2/task6/Task6.java
> +        if (n % 2 == 0) {
это выбросить

2024-12-03 21:46 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter2/task6/Task6.java
> +        return getGcd((max - min) / 2, min);
в качестве аргументов вставить  n, m%n

2024-12-03 21:46 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter2/task6/Task6.java
> +        int min = Math.min(m, n);
это выбросить

2024-12-03 21:46 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter2/task6/Task6.java
> +
В качестве хвоста рекурсии просьба использовать: если m % n == 0, то вернуть n.

2024-12-04 07:51 UTC, ilya-baykalov commented on src/main/java/com/walking/intensive/chapter2/task6/Task6.java
> +            return -1;
Эту валидацию всё же оставлю, без неё условие задачи не выполняется.  
За остальные комментарии спасибо, прямо магия.

2024-12-04 09:30 UTC, EvgeneZhurov approved these changes

2024-12-04 09:30 UTC, closed without merging