Task17
KFalcon2022/intensive-tasks-2024 pull request #567
Opened 2024-12-03 04:53 UTC by Kegeke

2024-12-10 20:00 UTC, EvgeneZhurov requested changes

2024-12-10 20:00 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter4/task17/Task17.java
> +        boolean isFlag;
если переменная объявляется без присвоения ей значения это может означать, что выбрана неверная область видимости или ей здесь не место. Это переменной место внутри цикла. При объявлении переменной внутри цикла не будет расходоваться большое памяти и работать медленнее не станет

2024-12-10 20:00 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter4/task17/Task17.java
> +        for (int i = 0; i < array.length; i++) {
по условию задачи нужно сортировать только неотсортированную часть массива, нет смысла каждый раз идти до самого конца массива.

2024-12-11 05:18 UTC, Kegeke commented on src/main/java/com/walking/intensive/chapter4/task17/Task17.java
> +        for (int i = 0; i < array.length; i++) {
Реально, производительность улучшилась на ~100 миллисекунд, при 10000 элементах!

2024-12-12 11:28 UTC, EvgeneZhurov approved these changes

2024-12-12 11:28 UTC, closed without merging