Task12.
KFalcon2022/intensive-tasks-2024 pull request #572
Opened 2024-12-03 07:51 UTC by PabloQuetzalcoatl

2024-12-04 20:40 UTC, KFalcon2022 requested changes

2024-12-04 20:40 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter3/task12/Task12.java
> +            if (baskets.charAt(i) != '1' && baskets.charAt(i) != '0') {
baskets.charAt(i) можно вынести в переменную

2024-12-04 20:40 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter3/task12/Task12.java
> +
лишняя пустая строка

2024-12-04 20:40 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter3/task12/Task12.java
> +        // ну по сути для каждой ячейки нужно вычислить расстояние от других ячеек до неё
комменты нужны в ситуациях, когда алгоритм нестандартный или имеет специфические особенности, не очевидные из кода. В остальнымх случаях комментарии подобного типа усложняют восприятие. При необходимости лучше использовать Java-doc над методом

2024-12-04 20:40 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter3/task12/Task12.java
> +                if (j != i && baskets.charAt(j) == '1') {
да как будто можно опустить первое условие. разность == 0, погоды не делает

2024-12-04 20:40 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter3/task12/Task12.java
> +
лишняя пустая строка

2024-12-04 20:40 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter3/task12/Task12.java
> +
лишняя пустая строка

2024-12-04 20:40 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter3/task12/Task12.java
> +        return true;
Хорошее решение, но предлагаю добить оформление

2024-12-05 08:36 UTC, PabloQuetzalcoatl commented on src/main/java/com/walking/intensive/chapter3/task12/Task12.java
> +        return true;
Добью обязательно. Не закрывай пока.

2024-12-05 20:43 UTC, KFalcon2022 approved these changes
Замечания мелкие, задача зачтена

2024-12-05 20:43 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter3/task12/Task12.java
> +            char basket =baskets.charAt(i);
пробел после =

2024-12-05 20:43 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter3/task12/Task12.java
> +            if ( basket != '1' && basket != '0') {
лишний пробел после (

2024-12-14 13:28 UTC, KFalcon2022 commented
ПР закрыт, т.к. не обновлялся более недели. При необходимости повторной проверки просьба открыть новый ПР

2024-12-14 13:28 UTC, closed without merging