task9
KFalcon2022/intensive-tasks-2024 pull request #574
Opened 2024-12-03 09:26 UTC by ilya-baykalov

2024-12-04 20:54 UTC, KFalcon2022 requested changes

2024-12-04 20:54 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter2/task9/Task9.java
> +        String result = "";
Переменные должны объявляться как можно ближе к месту использования

2024-12-04 20:54 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter2/task9/Task9.java
> +        for (int i = 1; i <= n; i++) {
почему бы не вынести этот цикл в метод, возвращающий длину строки?

2024-12-04 20:54 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter2/task9/Task9.java
> +    static int getBinomCoeff(int i, int m) {
сокращение - дело неблагодарное, особенно если оно не является общепринятым

2024-12-04 20:54 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter2/task9/Task9.java
> +    static int getLength(int k) {
название переменных и параметров стоит давать осмысленные

2024-12-04 20:54 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter2/task9/Task9.java
>      }
Предлагаю добить оформление, в остальном хорошее решение

2024-12-05 06:57 UTC, ilya-baykalov commented on src/main/java/com/walking/intensive/chapter2/task9/Task9.java
>      }
Всё поправил, спасибо.  

P.S. Тесты сломались: если я правильно понял, они почему-то стали требовать пустую строку в конце.
Оставлю как есть, всё-таки в условии задачи про пустую  строку не сказано

2024-12-05 20:47 UTC, KFalcon2022 approved these changes
Замечание мелкое, задача зачтена

2024-12-05 20:47 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter2/task9/Task9.java
> +            for (int i = 1; i <= m; i++) {
имена счетчиков в цикле, если они не несут дополнительной смысловой нагрузки, принято именовать i->j->k. Каждое следующее имя используется, если область видимости предыдущей еще не завершена. В чем была идея именовать счетчик внешнего цикла как `m`?)

2024-12-05 20:47 UTC, closed without merging