Task1
KFalcon2022/intensive-tasks-2024 pull request #58
Opened 2024-11-17 16:32 UTC by Rewertkin

Решение по Задаче 1

2024-11-17 16:40 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task1/Task1.java
> +            wordAge = "год";
можно сразу делать return, тогда введение переменой wordAge не понадобится

2024-11-17 16:41 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task1/Task1.java
> +        String wordAge;
переменные лучше объявлять максимально близко к месту их первого использования.

2024-11-18 14:20 UTC, Rewertkin commented on src/main/java/com/walking/intensive/chapter1/task1/Task1.java
> +        String wordAge;
поправил

2024-11-18 14:22 UTC, Rewertkin commented on src/main/java/com/walking/intensive/chapter1/task1/Task1.java
> +            wordAge = "год";
Решил в переменную закинуть, т.к. так удобнее с текстом работать. 
Сейчас если потребуется изменить текст вывода, нужно будет менять только в одном месте. Если же отказаться от переменной - при изменение предложения потребуется корректировать в нескольких местах одно и тоже

2024-11-18 19:29 UTC, EvgeneZhurov requested changes

2024-11-18 19:29 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task1/Task1.java
>              wordAge = "год";
сделайте return cо словом "год" и с остальными словами тоже

2024-11-18 21:33 UTC, Rewertkin commented on src/main/java/com/walking/intensive/chapter1/task1/Task1.java
>              wordAge = "год";
Исправил

2024-11-18 21:37 UTC, EvgeneZhurov requested changes

2024-11-18 21:37 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task1/Task1.java
>          } else if (calcAge > 1 & calcAge < 5) {
после return не ставят else. Либо будет return, либо метод продолжит исполняться и без else

2024-11-19 16:05 UTC, EvgeneZhurov requested changes

2024-11-19 16:05 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task1/Task1.java
> +        return String.format("Вам %d лет", inAge);
"Вам " + inAge + " лет" выглядит короче и читается проще.

2024-11-19 16:05 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task1/Task1.java
> +        }
в логическом условии  if (calcAge >= 11 & calcAge <= 14) { есть варнинг. Просьба поправить

2024-11-19 18:31 UTC, closed without merging