task14
KFalcon2022/intensive-tasks-2024 pull request #581
Opened 2024-12-03 16:22 UTC by tux33me

2024-12-04 20:34 UTC, KFalcon2022 requested changes

2024-12-04 20:34 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter3/task14/Task14.java
> +        System.out.println(Arrays.toString(getObjectCounts(new int[][]{{1, 3}, {3, 3}, {5, 3}, {2, 2}}, new int[][]{{2, 3, 1}, {4, 3, 1}, {1, 1, 2}})));
Длина строки кода не должна превышать 120 символов. Считается, что именно столько влазит в один экран при стандартных настройках

2024-12-04 20:34 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter3/task14/Task14.java
> +
лишняя пустая строка

2024-12-04 20:34 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter3/task14/Task14.java
> +        int[] emptyArray = new int[0];
бесполезная переменная

2024-12-04 20:34 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter3/task14/Task14.java
> +        }
Валидацию лучше сепарировать в отдельный метод. Лишние невложенные циклы не изменят алгоритмическую сложность решения, но упростят восприятие кода

2024-12-04 20:34 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter3/task14/Task14.java
> +        double epsilon = 1e-6;
зачем, Если подгон под тесты, то избыточно. Других причин не вижу, точность double в пределах интенсива считается достаточной

2024-12-04 20:34 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter3/task14/Task14.java
> +        return Math.sqrt((objectX - radarX) * (objectX - radarX) + (objectY - radarY) * (objectY - radarY)) < radarRange + epsilon;
r^2 лучше бы в переменную вынести. Или хотя бы сам радиус

2024-12-04 20:34 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter3/task14/Task14.java
> +    static boolean isVulnerable(int objectX, int objectY, int radarX, int radarY, int radarRange) {
Не логичнее в качестве параметров передавать массивы? И уже внутри метода использовать конкретные элементы. Большое число параметров всегда сложно читать. Особенно когда при вызове метода они не имеют понятных обозначений (не очевидно, что `radars[i][2]` - радиус окружности и т.д.)

2024-12-05 03:21 UTC, tux33me commented on src/main/java/com/walking/intensive/chapter3/task14/Task14.java
> +        double epsilon = 1e-6;
Это я перемудрил на тему того, что нельзя строго сравнивать два double. Хотя в данном случае можно вообще избавиться от double

2024-12-05 03:22 UTC, tux33me commented on src/main/java/com/walking/intensive/chapter3/task14/Task14.java
> +        return Math.sqrt((objectX - radarX) * (objectX - radarX) + (objectY - radarY) * (objectY - radarY)) < radarRange + epsilon;
Вот это не совсем понял, что требовалось

2024-12-05 20:24 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter3/task14/Task14.java
> +        return Math.sqrt((objectX - radarX) * (objectX - radarX) + (objectY - radarY) * (objectY - radarY)) < radarRange + epsilon;
Вот эту штуку `Math.sqrt((objectX - radarX) * (objectX - radarX) + (objectY - radarY) * (objectY - radarY))` тяжело воспринимать, когда читаешь код. Стандартное решение - выделить часть расчета в переменные. Но логически выделить в переменную тут разве что квадрат радиуса получится - `(objectX - radarX) * (objectX - radarX) + (objectY - radarY) * (objectY - radarY)`. В других случаях задолбешься придумывать переменной значение и, соответственно, имя

2024-12-05 20:35 UTC, closed without merging