task15
KFalcon2022/intensive-tasks-2024 pull request #582
Opened 2024-12-03 17:02 UTC by tux33me

2024-12-04 20:25 UTC, KFalcon2022 requested changes

2024-12-04 20:25 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter3/task15/Task15.java
> +        if (city[0] == null || city[0].length == 0) {
Ты же ниже еще раз проверяешь эти же условия в цикле. Это действие только ради `int columns = city[0].length;`?

Кроме того, непонятно, почему валидация не вынесена в отдельный метод. Если это была экономия на лишних прогонах цикла - она скорее избыточна. У тебя и так квадратичная сложность алгоритма, отделение валидации не изменит сложность, но ощутимо облегчит читабельность

2024-12-04 20:25 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter3/task15/Task15.java
> +        int overallCounter = 0;
неудачное название. Уточнение, счетчик "чего", могло быть исправить ситуацию

Кроме того, объявление переменной должно происходит как можно ближе к месту ее использования

2024-12-04 20:25 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter3/task15/Task15.java
> +
лишняя пустая строка

2024-12-04 20:25 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter3/task15/Task15.java
> +                    overallCounter += Math.min(maxInColumn[j] - city[i][j], maxInRow[i] - city[i][j]);
Если используешь min - почему бы выше не использовать max? Для определения наибольших значений по строке и столбцу

2024-12-04 20:25 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter3/task15/Task15.java
> +        int[] maxInColumn = new int[columns];
columnMax чуть короче и дает ту же информацию о смысле значения. Предлоги достаточно часто можно избегать без потери смысла

2024-12-04 20:25 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter3/task15/Task15.java
> +        return overallCounter;
Алгоритм понятен, но оформление решения стоит доработать - сейчас код выглядит переусложненным

2024-12-05 03:53 UTC, tux33me commented on src/main/java/com/walking/intensive/chapter3/task15/Task15.java
> +        if (city[0] == null || city[0].length == 0) {
Проверка на null, да, чтобы int columns = city[0].length не вылетел по exception. Проверка на ноль или здесь лишняя или в цикле. Убрал в цикле

2024-12-05 20:37 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter3/task15/Task15.java
> +        if (city[0] == null || city[0].length == 0) {
То есть вместо большего однообразия и меньшего количества кода ты решил сделать с точностью до наоборот?)

2024-12-05 20:40 UTC, KFalcon2022 requested changes
Хорошее решение, хорошее оформление, но надо доправить валидацию:)

2024-12-05 20:40 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter3/task15/Task15.java
> +            if (row == null || row.length != columns) {
у тебя же город N x N по условию. То есть квадрат. Достаточно проверять, что row.length == city.length. И не придется выше городить огород с city[0]

2024-12-06 07:12 UTC, tux33me commented on src/main/java/com/walking/intensive/chapter3/task15/Task15.java
> +        if (city[0] == null || city[0].length == 0) {
Нет, просто в цикле получалась избыточной)

2024-12-06 07:15 UTC, tux33me commented on src/main/java/com/walking/intensive/chapter3/task15/Task15.java
> +            if (row == null || row.length != columns) {
Да, вчера после сообщения в чате, что условия задачи поменялись, пока искал что именно поменялось, заметил, что город оказывается и до изменения условий был квадрат N x N. Поменять решение уже не успел. Моё решение предполагало, что город это прямоугольник M x N) Как и в некоторых предыдущих зачах сначала делал более сложный случай, потом замечал, что по условию, например, мячик 1, а не любое кол-во)) В общем, нужно внимательнее читать условия. Спасибо!

2024-12-09 17:16 UTC, KFalcon2022 approved these changes

2024-12-09 17:16 UTC, closed without merging