Task5
KFalcon2022/intensive-tasks-2024 pull request #594
Opened 2024-12-04 07:36 UTC by AndyRaw007

2024-12-04 17:56 UTC, EvgeneZhurov requested changes

2024-12-04 17:56 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task5/Task5.java
> +        return !(a <= 0) && !(b <= 0) && !(c <= 0) && !(a + b <= c) && !(a + c <= b) && !(b + c <= a);
если развернуть логические условия, то ! можно не писать. Читаться будет легче.

2024-12-04 17:56 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task5/Task5.java
> +        if (isCheck(a, b, c)) {
нужно развернуть логическое условие на противоположное и поменять блоки кода местами. Читаться будет сильно легче. Нужно поправить во всех методах.

2024-12-04 17:56 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task5/Task5.java
> +        return -1;
лучше поставить пустую строку перед return

2024-12-04 17:56 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task5/Task5.java
> +            double p = (a + b + c) / 2;
полупериметр встречается много раз, лучше выносить в метод

2024-12-04 17:56 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task5/Task5.java
> +            area = Math.pow(area, 0.5);
Math.sqrt

2024-12-04 17:56 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task5/Task5.java
> +            return outRad;
Лучше называть переменные по имени класса(без глагола), так повысится читаемость кода.

2024-12-05 11:01 UTC, AndyRaw007 commented on src/main/java/com/walking/intensive/chapter1/task5/Task5.java
> +        return !(a <= 0) && !(b <= 0) && !(c <= 0) && !(a + b <= c) && !(a + c <= b) && !(b + c <= a);
Изначально так и было реализовано, но IJ предложила так упростить запись и я согласился). Вернул обратно

2024-12-05 19:41 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task5/Task5.java
> +        return !(a <= 0) && !(b <= 0) && !(c <= 0) && !(a + b <= c) && !(a + c <= b) && !(b + c <= a);
жду код

2024-12-06 07:38 UTC, AndyRaw007 commented on src/main/java/com/walking/intensive/chapter1/task5/Task5.java
> +        return !(a <= 0) && !(b <= 0) && !(c <= 0) && !(a + b <= c) && !(a + c <= b) && !(b + c <= a);
В тот момент отвлекли и не запушил изменения. Думал о комментариях уведомляется лишь после нажатия кнопки Re-request review

2024-12-06 07:38 UTC, AndyRaw007 commented on src/main/java/com/walking/intensive/chapter1/task5/Task5.java
> +        return -1;
Поставил везде в аналогичных моментах

2024-12-06 07:38 UTC, AndyRaw007 commented on src/main/java/com/walking/intensive/chapter1/task5/Task5.java
> +            double p = (a + b + c) / 2;
Вынес

2024-12-06 07:38 UTC, AndyRaw007 commented on src/main/java/com/walking/intensive/chapter1/task5/Task5.java
> +            area = Math.pow(area, 0.5);
Заменил везде

2024-12-06 07:38 UTC, AndyRaw007 commented on src/main/java/com/walking/intensive/chapter1/task5/Task5.java
> +            return outRad;
Переименовал. Оставил избыточную переменную в этой задаче чтоб читаемость была лучше

2024-12-06 18:54 UTC, EvgeneZhurov requested changes

2024-12-06 18:54 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task5/Task5.java
> +        if (isCheck(a, b, c)) {
Покажу на примере, нужно поменять везде: 
        if (!isCheck(a, b, c)) {
            return new double[0];
        }

            double area = getAreaByHeron(a, b, c);
            double heightA = 2 * area / a;
            double heightB = 2 * area / b;
            double heightC = 2 * area / c;
            double[] heights = {heightA, heightB, heightC};
            Arrays.sort(heights);
        
            return heights;

2024-12-07 08:24 UTC, AndyRaw007 commented on src/main/java/com/walking/intensive/chapter1/task5/Task5.java
> +        if (isCheck(a, b, c)) {
Теперь понял, спасибо. Поправил везде

2024-12-10 19:38 UTC, EvgeneZhurov requested changes

2024-12-10 19:38 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task5/Task5.java
> +        return ((a + b >= c) && (a + c >= b) && (b + c >= a) && (a >= 0) && (b >= 0) && (c >= 0));
много лишних ненужных скобок, просьба убрать

2024-12-10 19:38 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task5/Task5.java
> +    static double getP(double a, double b, double c) {
Старайтесь давать максимально релевантные имена. Вы забудете что делает этот метод через неделю, остальные просто не поймут.

2024-12-10 19:38 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task5/Task5.java
> +        return heights;
Перед return лучше поставить пустую строку. Читаться будет легче.

2024-12-10 19:38 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task5/Task5.java
> +        double[] bis = {bisA, bisB, bisC};
не сокращайте имена, старайтесь писать так, чтобы было максимально понятно

2024-12-10 19:38 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task5/Task5.java
> +        double sinA = Math.pow(1 - cosA * cosA, 0.5);
Math.sqrt :)

2024-12-19 12:36 UTC, AndyRaw007 commented on src/main/java/com/walking/intensive/chapter1/task5/Task5.java
> +        return ((a + b >= c) && (a + c >= b) && (b + c >= a) && (a >= 0) && (b >= 0) && (c >= 0));
Убрано

2024-12-19 12:51 UTC, AndyRaw007 commented on src/main/java/com/walking/intensive/chapter1/task5/Task5.java
> +    static double getP(double a, double b, double c) {
На мой взгляд Р, как стандартная переменная для формулы площади по Герону, вполне лаконично тут смотрится, но заменил на getHalfPerimeter)

2024-12-19 12:52 UTC, AndyRaw007 commented on src/main/java/com/walking/intensive/chapter1/task5/Task5.java
> +        return heights;
Добавил

2024-12-19 12:58 UTC, AndyRaw007 commented on src/main/java/com/walking/intensive/chapter1/task5/Task5.java
> +        double[] bis = {bisA, bisB, bisC};
Поправил

2024-12-19 13:00 UTC, AndyRaw007 commented on src/main/java/com/walking/intensive/chapter1/task5/Task5.java
> +        double sinA = Math.pow(1 - cosA * cosA, 0.5);
Пропустил) Исправил

2024-12-19 18:06 UTC, EvgeneZhurov approved these changes

2024-12-19 18:06 UTC, closed without merging