task14
KFalcon2022/intensive-tasks-2024 pull request #599
Opened 2024-12-04 08:23 UTC by Superbia101

2024-12-04 22:55 UTC, KateKhodko requested changes

2024-12-04 22:55 UTC, KateKhodko commented on src/main/java/com/walking/intensive/chapter3/task14/Task14.java
> +        for (int[] i : objectLocations) {
i, j и т д не совсем понятные названия, лучше `objectLocation`

2024-12-04 22:55 UTC, KateKhodko commented on src/main/java/com/walking/intensive/chapter3/task14/Task14.java
> +        for (int[] i : radars) {
Аналогично, лучше `radar`

2024-12-04 22:55 UTC, KateKhodko commented on src/main/java/com/walking/intensive/chapter3/task14/Task14.java
> +                validationFlag = false;
Нет смысла заводить флажок и менять его значения, можно сразу `return false;`

2024-12-04 22:55 UTC, KateKhodko commented on src/main/java/com/walking/intensive/chapter3/task14/Task14.java
> +        for (int i = 0; i < countRadars; i++) {
i, j тоже переименуй тут

2024-12-04 22:55 UTC, KateKhodko commented on src/main/java/com/walking/intensive/chapter3/task14/Task14.java
> +                if (Math.pow(j[0] - radars[i][0], 2) + Math.pow(j[1] - radars[i][1], 2) <= Math.pow(radars[i][2], 2)) {
Тут лучше вынести вычисления из самой проверки, и сравнивать потом расстояние до объекта с радиусом действия радара, сейчас трудновато читать

2024-12-05 06:18 UTC, Superbia101 commented
Спасибо, всё исправил.

2024-12-05 15:49 UTC, KateKhodko approved these changes

2024-12-05 15:50 UTC, closed without merging