Task1
KFalcon2022/intensive-tasks-2024 pull request #60
Opened 2024-11-17 17:57 UTC by zemaumka

На проверку

2024-11-17 18:05 UTC, EvgeneZhurov requested changes

2024-11-17 18:05 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task1/Task1.java
> +        if (age < 0) {
сделайте еще условие, что не более 127 лет

2024-11-17 18:05 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task1/Task1.java
> +        } else if (ostHundred > 10 && ostHundred < 15) {
после return не пишут else. Либо метод вернет строку, либо пойдет исполняться дальше и без else. Просьба поправить везде в коде.

2024-11-17 18:05 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task1/Task1.java
> +            result = "Вам " + age + " лет";
не требуется заводить переменную, чтобы ее сразу вернуть. Можно в двойных кавычках написать в return

2024-11-17 18:05 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task1/Task1.java
> +            result = "Вам " + age + " лет";
два разных return возвращают "лет". Напишите логические условия так, чтобы одно слово возвращалось одним return.

2024-11-17 18:05 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task1/Task1.java
> +        String result;
эта переменная не требуется.

2024-11-17 18:59 UTC, zemaumka commented on src/main/java/com/walking/intensive/chapter1/task1/Task1.java
> +        String result;
все три удалить?

2024-11-17 19:07 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task1/Task1.java
> +        String result;
Вы автор решения, Вам решать. Суть проста, если можно не заводить переменную, лучше не заводить. Если переменная заводится, то лучше делать это максимально близко с использованию и с минимальной областью видимости.

2024-11-18 20:36 UTC, EvgeneZhurov requested changes

2024-11-18 20:36 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task1/Task1.java
> +            if (age % 10 == 1){
просьба обойтись без двойных вложений.

2024-11-18 20:36 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task1/Task1.java
> +            if (age % 10 == 2 || age % 10 == 3 || age % 10 ==4) {
Просьба перечитать требования к оформлению кода. Нужно делать выравнивание.

2024-11-18 20:36 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task1/Task1.java
> +            if (age % 10 == 2 || age % 10 == 3 || age % 10 ==4) {
лучше ставить пустые строки между блоками кода, если они стоят не в самом начла еи не самом конце метода.

2024-11-18 20:36 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task1/Task1.java
> +            if (age % 10 == 2 || age % 10 == 3 || age % 10 ==4) {
можно написать короче, если использовать <= например.

2024-11-18 21:10 UTC, closed without merging