task15
KFalcon2022/intensive-tasks-2024 pull request #600
Opened 2024-12-04 08:24 UTC by Superbia101

2024-12-04 23:05 UTC, KateKhodko requested changes

2024-12-04 23:05 UTC, KateKhodko commented on src/main/java/com/walking/intensive/chapter3/task15/Task15.java
> +                        break;
Вот тут убрать флаг, делать сразу `return false;`

2024-12-04 23:05 UTC, KateKhodko commented on src/main/java/com/walking/intensive/chapter3/task15/Task15.java
> +        int[][] availableNumberFloors = new int[lenCity][2];
Тут для читаемости кода лучше разбить на 2 одномерных массива

2024-12-05 06:29 UTC, Superbia101 commented
Разделил)

2024-12-05 16:33 UTC, KateKhodko approved these changes

2024-12-05 16:34 UTC, closed without merging