task12
KFalcon2022/intensive-tasks-2024 pull request #601
Opened 2024-12-04 08:24 UTC by ilya-baykalov

2024-12-04 23:14 UTC, KateKhodko requested changes

2024-12-04 23:14 UTC, KateKhodko commented on src/main/java/com/walking/intensive/chapter3/task12/Task12.java
> +            }
Вот это лучше вынести в отдельный метод валидации и вызывать его в начале метода

2024-12-04 23:14 UTC, KateKhodko commented on src/main/java/com/walking/intensive/chapter3/task12/Task12.java
> +            int element = baskets.charAt(i) - '0';
baskets.charAt(i) оставить в отдельной переменной, потом можно сразу сравнивать element ==  '1'

2024-12-05 06:32 UTC, ilya-baykalov commented on src/main/java/com/walking/intensive/chapter3/task12/Task12.java
> +            }
Тогда мы сделаем лишний проход только для валидации. Зачем, если тут удобно провалидировать "на ходу"?

2024-12-05 06:37 UTC, ilya-baykalov commented on src/main/java/com/walking/intensive/chapter3/task12/Task12.java
> +            int element = baskets.charAt(i) - '0';
> baskets.charAt(i) оставить в отдельной переменной

нет смысла, мы используем её один раз. только лишнюю строку кода добавим

> потом можно сразу сравнивать element == '1'

Это и так можно, если вы про строку 58. Поправил.

2024-12-05 16:24 UTC, KateKhodko requested changes

2024-12-05 16:24 UTC, KateKhodko commented on src/main/java/com/walking/intensive/chapter3/task12/Task12.java
> +            int element = baskets.charAt(i) - '0';
Нет смысла заниматься вычитанием и приведением к инту, почему сразу не сравнивать символы?

2024-12-05 16:24 UTC, KateKhodko commented on src/main/java/com/walking/intensive/chapter3/task12/Task12.java
> +            }
В случае расширения функционала не хочется иметь цикл, в котором намешана и валидация, и сам расчет. Удобно, но не практично, т.к. в той же валидации могут произойти изменения, которые ну вообще не хочется видеть в основной логике.
Позднее познакомитесь с регулярными выражениями, с помощью их можно избежать цикла.
Ассимптотика в случае дополнительного прогона для валидации будет n + n^2, что, соответственно, сворачивается в n^2, то есть все равно будет квадратичная сложность, вне зависимости будет ли тут этот  цикл или нет

2024-12-05 19:23 UTC, ilya-baykalov commented on src/main/java/com/walking/intensive/chapter3/task12/Task12.java
> +            int element = baskets.charAt(i) - '0';
Хм, действительно, я как-то не понял сначала, что имелось в виду.
Поправил, спасибо

2024-12-05 19:27 UTC, ilya-baykalov commented on src/main/java/com/walking/intensive/chapter3/task12/Task12.java
> +            }
Звучит логично, поправил

2024-12-05 20:16 UTC, KateKhodko approved these changes

2024-12-05 20:16 UTC, KateKhodko commented on src/main/java/com/walking/intensive/chapter3/task12/Task12.java
> +            }
Наверное убрать валидацию здесь забыл)

2024-12-05 20:16 UTC, closed without merging