task11
KFalcon2022/intensive-tasks-2024 pull request #612
Opened 2024-12-04 14:47 UTC by Rewertkin

2024-12-04 18:42 UTC, EvgeneZhurov requested changes

2024-12-04 18:42 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter3/task11/Task11.java
> +                        return -1;
читаемость повысится и сейчас это работает как костыль, когда валидация спрятана в самую дальнюю часть метода. Место валидации в самом начале метода. Пройдите по массиву 1 раз и верните -1, если нужно и потом работайте с валидными данными

2024-12-05 10:06 UTC, Rewertkin commented on src/main/java/com/walking/intensive/chapter3/task11/Task11.java
> +                        return -1;
скорректировал. 
Первоначально отталкивался от того, что два раз один и тот же массив прогонять - плохая идея, т.к. скорее всего скорость обработки данного метода увеличивается как минимум в два раза.

2024-12-05 19:49 UTC, EvgeneZhurov approved these changes

2024-12-05 19:49 UTC, closed without merging