Task14
KFalcon2022/intensive-tasks-2024 pull request #615
Opened 2024-12-04 19:05 UTC by gentrus

2024-12-05 20:38 UTC, KateKhodko requested changes

2024-12-05 20:38 UTC, KateKhodko commented on src/main/java/com/walking/intensive/chapter3/task14/Task14.java
> +        double distance;
Переменные нужно объявлять как можно ближе к месту их использования и если переменной нельзя пока присвоить значение, значит она скорее всего объявлена слишком рано

2024-12-05 20:38 UTC, KateKhodko commented on src/main/java/com/walking/intensive/chapter3/task14/Task14.java
> +        int b;
a, b надо переименовать, сейчас непонятно для чего эти переменные и что в них хранится

2024-12-05 20:38 UTC, KateKhodko commented on src/main/java/com/walking/intensive/chapter3/task14/Task14.java
> +    static boolean isValidData(int[][] objects, int[][] radars) {
Метод лучше называть  с глагола, по которому понятно что метод делает, в данном случае это `validate`. C `is` можно булевые переменные называть)

2024-12-05 20:38 UTC, KateKhodko commented on src/main/java/com/walking/intensive/chapter3/task14/Task14.java
> +        }
Тут два практически одинаковых цикла, можно тоже в метод вынести и вызвать для каждой проверки его

2024-12-05 20:38 UTC, KateKhodko commented on src/main/java/com/walking/intensive/chapter3/task14/Task14.java
> +import java.util.Arrays;
Вот этот импорт нигде не используется, надо убрать)

2024-12-07 19:41 UTC, gentrus commented on src/main/java/com/walking/intensive/chapter3/task14/Task14.java
> +    static boolean isValidData(int[][] objects, int[][] radars) {
Я так понимаю это не критично? В прошлой задаче Колоколов Евгений меня поругал за отсутствие is в булевом методе)

2024-12-07 21:11 UTC, gentrus commented
Всё поправил. Спасибо)

2024-12-08 15:45 UTC, KateKhodko commented on src/main/java/com/walking/intensive/chapter3/task14/Task14.java
> +    static boolean isValidData(int[][] objects, int[][] radars) {
Не критично, можно так и так

2024-12-08 15:46 UTC, KateKhodko approved these changes

2024-12-08 15:49 UTC, closed without merging