Task8 - S9-User
KFalcon2022/intensive-tasks-2024 pull request #623
Opened 2024-12-05 10:28 UTC by S9-User

Попытка первая. Умение декомпозиции получило серьёзный апгрейд!

2024-12-07 16:30 UTC, PuccaGTS requested changes
Добрый день!
Программа выглядит так, как будто Вы пытались подогнать код к результата без написания алгоритма расчета. Во всем методе используются магические числа, который нет в условии, такого быть не должно, постарайтесь избавиться от чисел из Вашего кода, пока на входе у Вас есть только то, что билет содержит 6 цифр, напишите в начале метода `final long totalTickets = 1_000_000L;` или другое число, которое вам дано в условии, например: 999_999 максимально возможный билет, и разрабатывайте метод относительно этой перменной.

2024-12-07 16:30 UTC, PuccaGTS commented on src/main/java/com/walking/intensive/chapter2/task8/Task8.java
> +        int[] countOfSums = new int[28];
Что такое 28? Почему 28, а не 29?

2024-12-07 16:30 UTC, PuccaGTS commented on src/main/java/com/walking/intensive/chapter2/task8/Task8.java
> +        for (int i = 0; i <= 9; i++) {
Почему 9?

2024-12-07 16:30 UTC, PuccaGTS commented on src/main/java/com/walking/intensive/chapter2/task8/Task8.java
> +            for (int j = 0; j <= 9; j++) {
тот же вопрос

2024-12-07 16:30 UTC, PuccaGTS commented on src/main/java/com/walking/intensive/chapter2/task8/Task8.java
> +        for (int sum = 0; sum <= 27; sum++) {
сверху было 28, а тут стало 27, а может 83?

2024-12-07 16:30 UTC, PuccaGTS commented on src/main/java/com/walking/intensive/chapter2/task8/Task8.java
> +        final long totalTickets = 1_000_000L;
а вот это уже хорошо и понятно:)

2024-12-09 08:20 UTC, S9-User commented on src/main/java/com/walking/intensive/chapter2/task8/Task8.java
> +        int[] countOfSums = new int[28];
28 - потому что три числа в интервале от 0 до 9 могут дать 28 вариантов сумм. И именно такое количество вариантов целесообразно перебирать в этой задаче.
Условие дано конкретно, и я не подгонял - я пытался выверить оптимальный алгоритм для конкретного условия.

2024-12-09 08:21 UTC, S9-User commented on src/main/java/com/walking/intensive/chapter2/task8/Task8.java
> +        for (int i = 0; i <= 9; i++) {
Потому что в кадом разряде числа могут быть от 0 до 9. Мы же в десятичной системе работаем здесь.

2024-12-09 08:22 UTC, S9-User commented on src/main/java/com/walking/intensive/chapter2/task8/Task8.java
> +        for (int sum = 0; sum <= 27; sum++) {
Поотму что 28 - это количество вариантов, а 27 - это максимальное число, которое может содержаться в любом из вариантов.

2024-12-09 08:25 UTC, PuccaGTS commented on src/main/java/com/walking/intensive/chapter2/task8/Task8.java
> +        int[] countOfSums = new int[28];
Очень хорошо, что Вы знаете, что такое 28, но мне всё ещё пока не понятно, почему именно 28 целесообразно, а 27 не целесообразно, оно же меньше.

2024-12-09 08:25 UTC, S9-User commented on src/main/java/com/walking/intensive/chapter2/task8/Task8.java
> +        final long totalTickets = 1_000_000L;
Решение оптимально по алгоритмической сложности, я не вижу смысла переписывать этот код на более костыльные варианты.

2024-12-09 08:27 UTC, PuccaGTS commented on src/main/java/com/walking/intensive/chapter2/task8/Task8.java
> +        for (int i = 0; i <= 9; i++) {
Супер, тогда можно 9 унести в переменную и использовать её тогда, когда Вам нужно, а не писать постоянно 9 бесконечное количество раз:)

2024-12-09 08:28 UTC, PuccaGTS commented on src/main/java/com/walking/intensive/chapter2/task8/Task8.java
> +        for (int sum = 0; sum <= 27; sum++) {
Опять же, очень хорошо, что Вы это знаете и понимаете, но пока не понятно, как вы это определили)

2024-12-09 08:28 UTC, S9-User commented on src/main/java/com/walking/intensive/chapter2/task8/Task8.java
> +        int[] countOfSums = new int[28];
Если элементов массива будет 27 - одна из возможных сумм в него не поместится.

2024-12-09 08:29 UTC, PuccaGTS requested changes
Всё ещё ничего не понятно

2024-12-09 08:30 UTC, PuccaGTS commented on src/main/java/com/walking/intensive/chapter2/task8/Task8.java
> +        int[] countOfSums = new int[28];
так а откуда взялось это число 28? из головы?

2024-12-09 08:30 UTC, PuccaGTS commented on src/main/java/com/walking/intensive/chapter2/task8/Task8.java
> +        final long totalTickets = 1_000_000L;
Ну, никто не заставляет Вас писать костыли) Не переписывайте)

2024-12-11 06:55 UTC, PuccaGTS approved these changes

2024-12-11 06:55 UTC, closed without merging