Task6
KFalcon2022/intensive-tasks-2024 pull request #628
Opened 2024-12-05 15:15 UTC by johnmango

2024-12-09 20:29 UTC, KFalcon2022 requested changes

2024-12-09 20:29 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter2/task6/Task6.java
> +        int increasedM, increasedN;
Каждая переменная объявляется на отдельной строке. И я не вижу ни одной причины объявлять эти переменные здесь, а не внутри цикла

2024-12-09 20:29 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter2/task6/Task6.java
> +            } while (increasedN < increasedM);
Бесконечный цикл, да еще и с вложенным циклом внутри - очень переусложненный алгоритм

2024-12-09 20:29 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter2/task6/Task6.java
> +            } while (increasedN < increasedM);
При том что в целом идея мало отличается от обычного перебора, насколько я вижу

2024-12-09 20:29 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter2/task6/Task6.java
> +        return getGcdByEuclideanAlgorithm(lower, greater % lower);
можно описать лаконичнее. Опционально

2024-12-09 20:29 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter2/task6/Task6.java
> +        int greater = max(m, n);
Статик импорт - не самая лучшая практика. По крайней мере, на текущем этапе

2024-12-12 12:13 UTC, johnmango commented on src/main/java/com/walking/intensive/chapter2/task6/Task6.java
> +        return getGcdByEuclideanAlgorithm(lower, greater % lower);
не могу догадаться, как это сделать лаконичнее

2024-12-14 14:58 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter2/task6/Task6.java
> +        return getGcdByEuclideanAlgorithm(lower, greater % lower);
Тернарка вместо if выше, в первую очередь

2024-12-14 15:04 UTC, KFalcon2022 approved these changes
Замечание не критичное, задача зачтена

2024-12-14 15:04 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter2/task6/Task6.java
> +import java.lang.Math;
Зачем явный импорт? весь пакет `java.lang` доступен без импортирования

2024-12-14 15:05 UTC, KFalcon2022 approved these changes

2024-12-14 15:05 UTC, closed without merging