Task7
KFalcon2022/intensive-tasks-2024 pull request #630
Opened 2024-12-05 18:06 UTC by johnmango

2024-12-16 22:09 UTC, KFalcon2022 commented
Кажется я потерял этот ПР и не отписал. Извини

2024-12-16 22:10 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter2/task7/Task7.java
> +            if (i == getDivisorsSum(sum) && sum != getDivisorsSum(sum)) {
getDivisorsSum(sum) - зачем считать дважды? Получается, делаем расчет, результат которого нам уже известен

2024-12-16 22:11 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter2/task7/Task7.java
> +        while (++i < n) {
for тут ложится лучше. К тому же, зачем мы идем от единицы, если задача найти наибольшее значение? Очевидно, что мы придем к нему ближе к концу для большого `n`

2024-12-16 22:12 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter2/task7/Task7.java
> +                if (maxDivisor == i) {
тернарное выражение подошло бы лучше

2024-12-16 22:12 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter2/task7/Task7.java
> +        return divisorsSum + 1;
не проще единицу еще при инициализации переменной учесть?

2024-12-16 22:13 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter2/task7/Task7.java
> +        while (++i < maxDivisor) {
опять же, for ложится лучше, мы заранее знаем число итераций. К тому же тяжело разобрать логику ограничения цикла - изменяемы оба параметра в условии

2024-12-17 22:35 UTC, johnmango commented on src/main/java/com/walking/intensive/chapter2/task7/Task7.java
> +        while (++i < n) {
нам в любом случае надо перебрать весь диапазон, чтобы найти максимальное значение (оно не обязательно будет у самого большого i). Или там есть математическая закономерность?

2024-12-20 07:39 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter2/task7/Task7.java
> +        while (++i < n) {
Если у тебя значения ограничены сверху (1000000) и ты идешь от максимального, то найдя подходящее число и убедившись, что его пара не превышает 1000000, ты гарантированно можешь утверждать, что задача выполнена. Потому что:
1. Числа больше 1000000 тебя не интересуют
2. А для чисел меньше 1000000 ты уже сделал перебор всех значений, больше найденного

2024-12-20 07:44 UTC, KFalcon2022 requested changes

2024-12-20 07:44 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter2/task7/Task7.java
> +                maxDivisor = a / i;
цикл for традиционно используется для ситуаций, когда число итераций известно. Соответственно, менять maxDivisor или i за пределами шапки - очень плохая затея

2024-12-20 07:44 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter2/task7/Task7.java
> +                divisorsSum = maxDivisor == i ? divisorsSum + i : divisorsSum + i + maxDivisor;
Лучше на несколько строк разнеси, чтобы выражение не сливалось воедино:
```java
divisorsSum = maxDivisor == i 
    ? divisorsSum + i
    : divisorsSum + i + maxDivisor;
```

2024-12-20 07:44 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter2/task7/Task7.java
> +                maxDivisor = a / i;
Алгоритм хороший, наверно, наиболее эффективный из возможных. Но читаемость очень страдает

2024-12-20 07:44 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter2/task7/Task7.java
> +                if (maxSum < i + sum) {
избыточная вложенность, это легко объединить с предыдущим if

2024-12-20 21:57 UTC, johnmango commented on src/main/java/com/walking/intensive/chapter2/task7/Task7.java
> +        while (++i < n) {
Все понял. Пришлось очень много раз перечитывать условие задачи, пока дошло.

2024-12-22 17:00 UTC, KFalcon2022 approved these changes
Зачтено авансом. Правки выглядят очевидными, рекомендую добить самостоятельно. Если возникнут проблему - маякуй в лс

2024-12-22 17:00 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter2/task7/Task7.java
> +                || sum > n);
тут вроде в одну строку помещалось

2024-12-22 17:00 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter2/task7/Task7.java
> +            n--;
то есть заданное число принципиально не проверяем?) Тогда для ряда ситуаций ответ будет неверным

2024-12-22 17:01 UTC, closed without merging