Task 7
KFalcon2022/intensive-tasks-2024 pull request #633
Opened 2024-12-05 22:24 UTC by Lizasha

2024-12-05 22:32 UTC, Lizasha commented on src/main/java/com/walking/intensive/chapter1/task5/Task5.java
>  package com.walking.intensive.chapter1.task5;
по ошибке отправила task 5, удалю этот файл из pr

2024-12-09 19:47 UTC, KFalcon2022 requested changes

2024-12-09 19:47 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter2/task7/Task7.java
> +        int sumDividersN;
переменные необходимо объявлять как можно ближе к месту их использования. Расширять область видимости переменной без необходимости тоже не стоит. Для чего нужна переменная sumDividersN за пределами цикла?

2024-12-09 19:47 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter2/task7/Task7.java
> +        for (int i = 2; i < n; i++) {
Если n == 81, есть ли смысл проверять делится ли n на 80? А на 41? А на 10?

2024-12-09 19:47 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter2/task7/Task7.java
> +                sum += i;
Если n % i == 0, не будет ли n % (n/i) - тоже 0?

2024-12-09 19:47 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter2/task7/Task7.java
> +        for (int i = 1; i < n; i++) {
Нам необходимо найти наибольшее число, подходящее под условия. Стоит ли перебирать сначала наименьшие числа, а лишь затем - наибольшие?

2024-12-09 19:47 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter2/task7/Task7.java
> +                continue;
для цикла for не особо приветствуется использование break, continue или манипуляции со счетчиком за пределами шапки цикла. Считается, что условия цикла полностью помещаются в шапке. Для всего остального есть ~~мастеркард~~ while

2024-12-09 19:47 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter2/task7/Task7.java
> +            int sumDividersM = getSumOfDividers(sumDividersN);
зачем выносить в переменную, если используется единожды?

2024-12-09 19:47 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter2/task7/Task7.java
> +            if (sumDividersM == i && i != sumDividersN) {
Второе условие можно проверить еще до расчета getSumOfDividers(). Зачем заставлять программу производить лишние вычисления?

2024-12-16 22:08 UTC, KFalcon2022 commented
ПР закрыт, т.к. по нему не было активности более недели. При необходимости проверки просьба открыть новый ПР

2024-12-16 22:08 UTC, closed without merging