Task16
KFalcon2022/intensive-tasks-2024 pull request #635
Opened 2024-12-06 02:08 UTC by Neverhoodof

2024-12-09 20:14 UTC, KFalcon2022 requested changes

2024-12-09 20:14 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter4/task16/Task16.java
> +        return result;
Просто для информации: `System.arraycopy()` мог бы здорово упростить тебе жизнь в этой задаче

2024-12-09 20:14 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter4/task16/Task16.java
> +
Лишняя пустая строка

2024-12-09 20:14 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter4/task16/Task16.java
> +
Лишняя пустая строка

2024-12-09 20:14 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter4/task16/Task16.java
> +
Лишняя пустая строка. В начале метода действительно в некоторых командах принято оставлять пустую строку. В ситуациях, когда шапка методы многострочная (например, много параметров) и начало тела метода сливается с шапкой. Тебе такое пока не грозит:)

2024-12-09 20:14 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter4/task16/Task16.java
> +
Лишняя пустая строка

2024-12-09 20:14 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter4/task16/Task16.java
> +
Лишняя пустая строка

2024-12-09 20:14 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter4/task16/Task16.java
> +
Лишняя пустая строка

2024-12-09 20:14 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter4/task16/Task16.java
> +
Лишняя пустая строка

2024-12-09 20:14 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter4/task16/Task16.java
> +
Лишняя пустая строка

2024-12-09 20:14 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter4/task16/Task16.java
> +            return arr;
метод должен вернуть **копию** исходного массива

2024-12-09 20:14 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter4/task16/Task16.java
> +        if (arr.length == 0 || index < 0) {
Если index < 0, но длина массива больше 0 - почему возвращаем пустой массив?

2024-12-09 20:14 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter4/task16/Task16.java
> +
Лишняя пустая строка

2024-12-09 20:14 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter4/task16/Task16.java
> +                    markedIndex[i] = 1;
почему не массив boolean для такой цели?

2024-12-09 20:14 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter4/task16/Task16.java
> +        int length = 0;
назначение переменной не очевидно. То, что можно предположить из названия, расходится с реальностью

2024-12-09 20:14 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter4/task16/Task16.java
> +
Лишняя пустая строка

2024-12-09 20:14 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter4/task16/Task16.java
> +
Лишняя пустая строка

2024-12-09 20:14 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter4/task16/Task16.java
> +
Лишняя пустая строка

2024-12-09 20:14 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter4/task16/Task16.java
> +
Лишняя пустая строка

2024-12-09 20:14 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter4/task16/Task16.java
> +
Лишняя пустая строка. Ниже не дублирую, принцип, полагаю, понятен:)

2024-12-09 20:14 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter4/task16/Task16.java
> +                    firstCounter++;
Можно оптимизировать алгоритм. Если к концу вложенного цикла искомое число не найдено во втором массиве - возвращать из метода false. Поможет избавиться от избыточных вычислений

2024-12-09 20:14 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter4/task16/Task16.java
> +        result[0] = lastElement;
это логично сделать еще до цикла

2024-12-11 11:34 UTC, Neverhoodof commented on src/main/java/com/walking/intensive/chapter4/task16/Task16.java
> +
Не понимаю. Вроде блок "if" требовали пустыми строками выделять.

2024-12-11 11:35 UTC, Neverhoodof commented on src/main/java/com/walking/intensive/chapter4/task16/Task16.java
> +        int[] result = arr;
Так, собственно, новый массив - result - для этого и создается.

2024-12-11 11:57 UTC, Neverhoodof commented on src/main/java/com/walking/intensive/chapter4/task16/Task16.java
> +        return result;
Цитата из условия: "Но пока этого не произошло - даже типовые операции приходится производить вручную".

2024-12-11 12:01 UTC, Neverhoodof commented on src/main/java/com/walking/intensive/chapter4/task16/Task16.java
> +
If сверху не выделять?

2024-12-11 12:01 UTC, Neverhoodof commented on src/main/java/com/walking/intensive/chapter4/task16/Task16.java
> +
If?

2024-12-11 12:11 UTC, Neverhoodof commented on src/main/java/com/walking/intensive/chapter4/task16/Task16.java
> +            return arr;
Да, если бы мы меняли входящий массив. Здесь просто проверка валидности входных данных.

2024-12-11 12:17 UTC, Neverhoodof commented on src/main/java/com/walking/intensive/chapter4/task16/Task16.java
> +        if (arr.length == 0 || index < 0) {
Цитирую: "Если индекс некорректный - метод должен вернуть пустой массив".

2024-12-14 14:49 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter4/task16/Task16.java
> +
Вообще от команды зависит и договоренностей в команде. Но это требование, даже если присутствует, актуально для одной подпрограммы (кода внутри {}):

```java
for (int i = 0; i < arr1.length; i++) {
    // some code
    // some code
    // some code

    if (condition) { // if отделен пустой строкой, чтобы не сливался с предыдущим кодом, все норм
        // some code
    }
}
```

```java
for (int i = 0; i < arr1.length; i++) {

    if (condition) { // бесполезная пустая строка выше, код и так не сливается благодаря табуляции
        // some code
    }
}
```

То же самое актуально для других подпрограмм, оно же может быть актуально для `return`. Правила оформления могут отличаться, но они почти всегда имеют под собой обоснование. В частности, требования к пустой строке, как во втором примере, я не встречал еще ни разу. Видимо, потому что выглядит нелогично:)

2024-12-14 14:50 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter4/task16/Task16.java
> +        int[] result = arr;
int[] result = arr; - это не создание нового массива. Ты присвоил новой переменной ссылку на существующий массив. В этом легко убедиться, посмотрев на содержимое `arr` после выполнения метода

До знакомства со ссылочными типами это может быть не очевидно, но это так

2024-12-14 14:51 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter4/task16/Task16.java
> +        return result;
Вообще там речь про коллекции. Но вообще, я же не зря написал "Просто для информации":) Коммент выше - не замечание, а просто инфа к сведенью:)

2024-12-14 14:52 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter4/task16/Task16.java
> +
Отписал выше логику требования с пустой строкой

2024-12-14 14:54 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter4/task16/Task16.java
> +            return arr;
Зачастую в разработке ты знаешь, как дальше будут использоваться входные параметры твоего метода и его результат. Вполне возможно, что arr (переданный тебе параметром) и услвоный arr2 (полученный как результат твоего метода) будут обрабатываться по-своему и каждый будет по-своему меняться далее в коде, который вызовет твой метод. И для такой ситуации это решение может поломать алгоритм

2024-12-14 14:55 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter4/task16/Task16.java
> +        if (arr.length == 0 || index < 0) {
Да, согласен

2024-12-14 14:57 UTC, KFalcon2022 requested changes
Просьба исправить оставленные ранее замечания

2024-12-15 02:38 UTC, Neverhoodof commented on src/main/java/com/walking/intensive/chapter4/task16/Task16.java
> +        int[] result = arr;
Fixed

2024-12-15 02:39 UTC, Neverhoodof commented on src/main/java/com/walking/intensive/chapter4/task16/Task16.java
> +        return result;
Рекомендации принял. Код поменял.

2024-12-15 02:39 UTC, Neverhoodof commented on src/main/java/com/walking/intensive/chapter4/task16/Task16.java
> +                    firstCounter++;
Fixed

2024-12-17 21:27 UTC, KFalcon2022 requested changes

2024-12-17 21:27 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter4/task16/Task16.java
> +        int[] result = arr;
Не исправлено. Все еще не вижу создания нового массива

2024-12-17 21:27 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter4/task16/Task16.java
> +            System.arraycopy(arr1, minLength, result, minLength, maxLength - minLength);
лучше здесь же сделать return. И тогда не придется увеличивать вложенность кода ниже из-за else

2024-12-17 21:27 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter4/task16/Task16.java
> +            for (int i = 0; i < arr.length; i++) {
У тебя все еще есть метод isContains(), который сделает этот код легче для восприятия при той же семантике

2024-12-17 21:27 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter4/task16/Task16.java
> +                    lengthLessening++;
lesseningLength скорее. или removingLength

2024-12-17 21:27 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter4/task16/Task16.java
> +            for (int j : arr2) {
Опять же, isContains()? и ниже

2024-12-17 21:27 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter4/task16/Task16.java
> +                if (i == j) {
isContains()

2024-12-20 07:34 UTC, KFalcon2022 approved these changes

2024-12-20 07:34 UTC, closed without merging