Task 12
KFalcon2022/intensive-tasks-2024 pull request #642
Opened 2024-12-06 17:20 UTC by HellRus

2024-12-09 21:55 UTC, KateKhodko requested changes

2024-12-09 21:55 UTC, KateKhodko commented on src/main/java/com/walking/intensive/chapter3/task12/Task12.java
> +import java.sql.SQLOutput;
Неиспользуемые импорты убираем

2024-12-09 21:55 UTC, KateKhodko commented on src/main/java/com/walking/intensive/chapter3/task12/Task12.java
> +
лишняя пустая строка

2024-12-10 06:38 UTC, HellRus commented
Спасибо, внёс изменения

2024-12-17 19:05 UTC, KateKhodko approved these changes

2024-12-17 19:05 UTC, closed without merging