task1
KFalcon2022/intensive-tasks-2024 pull request #65
Opened 2024-11-17 19:44 UTC by r0nery

2024-11-17 20:04 UTC, EvgeneZhurov requested changes

2024-11-17 20:04 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task1/Task1.java
> +        if (age < 0) {
Просьба создать условие, при котором некорректным будет возраст более 127 лет.

2024-11-17 20:04 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task1/Task1.java
> +        } else if (age > 10 && age < 15) {
после return не нужно ставить else. Код, либо выйдет из метода, либо продолжит исполняться и без else, просьба поправить везде.

2024-11-17 20:04 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task1/Task1.java
> +        } else if (lastDigit == 1) {
при вводе числа 112 в качестве аргумента, метод вернет: Вам 112 года

2024-11-17 20:21 UTC, EvgeneZhurov requested changes

2024-11-17 20:21 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task1/Task1.java
> +        return "Вам " + age + " лет";
просьба написать такие логические условия, чтобы на один return было одно слово . Сейчас слово "лет" содержится в двух return

2024-11-17 20:21 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task1/Task1.java
> +        if (lastTwoDigits > 10 && lastTwoDigits < 15) {
между блоками if лучше ставить пустые строки, если это не начало или конец метода. Так читается легче.

2024-11-18 20:06 UTC, r0nery commented on src/main/java/com/walking/intensive/chapter1/task1/Task1.java
> +        return "Вам " + age + " лет";
Сделал. Правда, не уверен, что стало читаться лучше.

2024-11-18 20:10 UTC, EvgeneZhurov requested changes

2024-11-18 20:10 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task1/Task1.java
> +        if ((lastTwoDigits > 10 && lastTwoDigits < 15) || List.of(5, 6, 7, 8, 9, 0).contains(lastDigit)) {
без коллекций пожалуйста

2024-11-18 20:10 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task1/Task1.java
>          return "Вам " + age + " лет";
У Вас два return с одним словом "лет". Попробуйте написать такие логические условия, чтобы был ровно один return на каждое слово.

2024-11-18 20:24 UTC, EvgeneZhurov approved these changes

2024-11-18 20:24 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task1/Task1.java
лишняя пустая строка

2024-11-18 20:25 UTC, closed without merging