Task11
KFalcon2022/intensive-tasks-2024 pull request #655
Opened 2024-12-08 15:29 UTC by johnmango

2024-12-10 21:39 UTC, KFalcon2022 requested changes
Алгоритм понятен и неплох (хоть и может быть сильно оптимизирован), как и попытка в оптимизацию. Но стоит добить

2024-12-10 21:39 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter3/task11/Task11.java
> +                continue;
continue, break и изменение счетчика массива внутри цикла for - зачастую неодобряемая практика. Считается, что  for предназначен для ситуаций, когда число итераций известно заранее

2024-12-10 21:39 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter3/task11/Task11.java
> +    static int getSumOfArray(int[] array) {
массивы складывать противоестественно) sumElements()? getElementsSum()?

2024-12-10 21:39 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter3/task11/Task11.java
> +        int sumOfArray = 0;
достаточно просто sum. of - вообще вредная в 99% случаев частица, от нее почти всегда можно избавиться просто поменяв порядок слов

2024-12-10 21:39 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter3/task11/Task11.java
> +        for (int j = length; j >= 3; j--) {
счетчик внешнего цикла традиционно именуется как i, счетчик вложенного - наоборот. Текущий вариант - не ошибка, но он заставляет читающего код напрячься и пытаться понять, почему отошли от общепринятого паттерна. Или перепроверять, не пропустил ли еще один цикл выше

2024-12-14 15:15 UTC, KFalcon2022 requested changes

2024-12-14 15:15 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter3/task11/Task11.java
> +        int largestOddArray = (length % 2 == 0) ? length - 1 : length;
лишние скобки

2024-12-14 15:15 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter3/task11/Task11.java
> +                int[] smallArray = Arrays.copyOfRange(array, j, i + j);
Создавать новые массивы - достаточно дорогая операция. Да и зачем? Ты ведь можешь просто в метод подсчета суммы передавать исходный массив, начальный и конечный индексы. И суммировать только значения по подходящим индексам

2024-12-14 15:15 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter3/task11/Task11.java
> +        int sumOfArray = 0;
Не исправлено

2024-12-14 15:15 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter3/task11/Task11.java
> +        for (int j : array) {
не вижу внешнего массива) Кроме того, для for-each цикла стараются давать осознанное название переменной - это ведь не просто счетчик, как в классическом for. Скажем, `number` - вполне норм имя в данном случае

2024-12-14 15:15 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter3/task11/Task11.java
> +        for (int i : array) {
аналогично комменту вышу

2024-12-14 15:30 UTC, johnmango commented on src/main/java/com/walking/intensive/chapter3/task11/Task11.java
> +        int largestOddArray = (length % 2 == 0) ? length - 1 : length;
мне показалось со скобками удобочитаемее. Убрал.

2024-12-17 21:09 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter3/task11/Task11.java
> +        int largestOddArray = (length % 2 == 0) ? length - 1 : length;
Как говорила мой препод по ОАиП - скобки как гандоны. Надежно, но когда много - ощущения не те

2024-12-17 21:11 UTC, KFalcon2022 approved these changes
Замечания мелкие, задача зачтена

2024-12-17 21:11 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter3/task11/Task11.java
> +        for (int j = firstElement; j <= lastElement; j++) {
i. Это не вложенный цикл

2024-12-17 21:11 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter3/task11/Task11.java
> +
лишняя пустая строка

2024-12-17 21:11 UTC, closed without merging