Task12
KFalcon2022/intensive-tasks-2024 pull request #671
Opened 2024-12-09 16:22 UTC by ElowLiet

2024-12-11 17:38 UTC, KFalcon2022 requested changes

2024-12-11 17:38 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter3/task12/Task12.java
> +        if (baskets == null || !baskets.matches("[01]*")) {
И как это работает?)

2024-12-11 17:38 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter3/task12/Task12.java
> +            totalBalls += (value - '0');
лишние скобки. И что за странная история с вычитанием символа? Я понимаю, что там коды у 1 и 0 соседние и будет либо 1, либо 0. Но выглядит как непонятная фигня

2024-12-11 17:38 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter3/task12/Task12.java
> +        // Подсчет перемещений для каждой корзинки
Комментарии в коде необходимы для объяснения запутанной или специфичной логики, в остальных случаях они лишь усложняют чтение кода

2024-12-17 21:34 UTC, KFalcon2022 requested changes

2024-12-17 21:34 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter3/task12/Task12.java
> +                forwardCount += ballsArray[j] * (j - i);
Не могу понять, зачем ballsArray нужен. Для символьного перебора строки через charAt() можно ограничиться проверкой: если символ - '1', сделать вычисление. Создавать дополнительный массив чисел для этого избыточно

2024-12-17 21:34 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter3/task12/Task12.java
> +                backwardCount += ballsArray[j] * (i - j);
аналогично комментарию выше

2024-12-17 21:34 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter3/task12/Task12.java
> +        }
Зачем разделять перемещение влево и вправо? Если брать разность по модулю - можно будет удалить один из циклов выше. И цикл ниже не потребуется

Чуть что, метод для получения модуля числа - `Math.abs()`

2024-12-18 07:08 UTC, ElowLiet commented
Добрый день! Избавился от лишних переменных по типу: ballsArray, movementsLeft, movementsRight. Воспользовался методом Math.abs() для подсчета расстояния между корзинками.

2024-12-20 07:49 UTC, KFalcon2022 approved these changes
Замечание мелкое. Задача зачтена

2024-12-20 07:49 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter3/task12/Task12.java
> +        int[] movementNumber = new int[length];
Объявление переменной должно происходить как можно ближе к ее первому использованию

2024-12-20 07:49 UTC, closed without merging