task16
KFalcon2022/intensive-tasks-2024 pull request #675
Opened 2024-12-09 20:37 UTC by ilya-baykalov

2024-12-11 18:10 UTC, KFalcon2022 requested changes
По совокупности - лучшее решение этой задачи из тех, которые я ревьюил

2024-12-11 18:10 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter4/task16/Task16.java
> +        return arr1.length != 0 && arr2.length != 0 && arr1.length == arr2.length;
если условия 1 и 3 выполнятся, останется смысл проверять условие 2?

2024-12-11 18:10 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter4/task16/Task16.java
> +        int[] incrementArr = new int[arr.length];
incrementedArr

2024-12-11 18:10 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter4/task16/Task16.java
> +            incrementArr[i] = arr[i] + 1;
++arr[i]?

2024-12-11 18:10 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter4/task16/Task16.java
> +            int elementOfArr1 = i < arr1.length ? arr1[i] : 0;
Хороший вариант реализации метода. Только elementOfArr1 -> element1, будет вполне достаточно

2024-12-11 18:10 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter4/task16/Task16.java
> +        int[] result = new int[arr.length - matchCounter];
Для такого есть методы Arrays. Для выделения подмассива, например

2024-12-11 18:10 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter4/task16/Task16.java
> +        if (arr1.length != arr2.length) {
Из условия задачи это не следует. Одни и те же числа вполне могут дублироваться в массиве, например

2024-12-11 18:10 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter4/task16/Task16.java
> +        if (arr1.length != arr2.length) {
По итоге реализация метода некорректна

2024-12-11 19:17 UTC, ilya-baykalov commented on src/main/java/com/walking/intensive/chapter4/task16/Task16.java
> +            incrementArr[i] = arr[i] + 1;
Но ведь тогда мы ещё и `arr[i]` поменяем, а по условию исходный массив изменять нельзя

2024-12-11 19:21 UTC, ilya-baykalov commented on src/main/java/com/walking/intensive/chapter4/task16/Task16.java
> +            int elementOfArr1 = i < arr1.length ? arr1[i] : 0;
Ну чёт совсем придирка)
Оставлю так

2024-12-11 20:18 UTC, ilya-baykalov commented on src/main/java/com/walking/intensive/chapter4/task16/Task16.java
> +            int elementOfArr1 = i < arr1.length ? arr1[i] : 0;
для меня `element1` читается как `элемент [номер] один`

2024-12-14 14:42 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter4/task16/Task16.java
> +            int elementOfArr1 = i < arr1.length ? arr1[i] : 0;
Тогда уж firstArrayElement. Of в абсолютном большинстве случаев выглядит стремно. Цифры в именах тоже не особо приветствуются, но иногда являются меньшим из зол

2024-12-14 14:42 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter4/task16/Task16.java
> +            incrementArr[i] = arr[i] + 1;
Согласен, херню предложил)

2024-12-14 14:44 UTC, KFalcon2022 approved these changes
Оставшееся замечание мелкое, задача зачтена

2024-12-14 14:44 UTC, closed without merging