task16
KFalcon2022/intensive-tasks-2024 pull request #678
Opened 2024-12-10 04:15 UTC by Roj-han

2024-12-11 17:57 UTC, KFalcon2022 requested changes

2024-12-11 17:57 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter4/task16/Task16.java
> +        int[] incrementArray = new int[arr.length];
incrementedArray скорее

2024-12-11 17:57 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter4/task16/Task16.java
> +            incrementArray[i] = arr[i] + 1;
++arr[i]?

2024-12-11 17:57 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter4/task16/Task16.java
> +        int[] multiplyArray = new int[Math.max(arr1.length, arr2.length)];
Math.max(arr1.length, arr2.length) - это лучше в переменную, тяжело читать

2024-12-11 17:57 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter4/task16/Task16.java
> +        int[] subtractArray = new int[Math.max(arr1.length, arr2.length)];
subtractedArray

2024-12-11 17:57 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter4/task16/Task16.java
> +        int i = 0;
В шапку цикла

2024-12-11 17:57 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter4/task16/Task16.java
> +        if (arr1.length < arr2.length) {
не проще пересохранить больший или меньший массив (какой нужен для решения) в другую переменную? Чтобы не дублировать однотипный код в if-else. Ну и для одинаковой длины можно просто раньше метод закончить, чтобы else-if не городить

2024-12-11 17:57 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter4/task16/Task16.java
> +            for (; i < subtractArray.length; ++i) {
Выглядит стремно:) Проще новый i  определить

2024-12-11 17:57 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter4/task16/Task16.java
> +            addArray[arr.length] = newValue;
если сделать здесь return - else можно будет убрать. Лишняя вложенность - так себе затея

2024-12-11 17:57 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter4/task16/Task16.java
> +            for (; i < addArray.length; i++) {
опять же, огород с переиспользованием i

2024-12-11 17:57 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter4/task16/Task16.java
> +        for (int i = 0; i < arr.length; i++) {
не проще массив с конца перебирать? Сейчас делаешь лишние операции

2024-12-11 17:57 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter4/task16/Task16.java
> +        } else {
Где-то выше было замечание насчет лишнего else.

2024-12-11 17:57 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter4/task16/Task16.java
> +            for (int i = 0; i < index; i++) {
В целом, в текущем else вообще можно одним циклом на все обойтись

2024-12-11 17:57 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter4/task16/Task16.java
> +        int[] reducedArray = new int[reducedArrLength];
Для ситуаций, как здесь, есть методы в Arrays:) для выделения подмассива

2024-12-11 19:30 UTC, Roj-han commented on src/main/java/com/walking/intensive/chapter4/task16/Task16.java
> +            incrementArray[i] = arr[i] + 1;
это изменит значение в исходном массиве, а мы исходный массив не трогаем

2024-12-14 14:40 UTC, KFalcon2022 requested changes

2024-12-14 14:40 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter4/task16/Task16.java
> +        int multiArrLength = Math.max(arr1.length, arr2.length);
multipliedArrLength. Сокращения в большинстве случаев не приветствуются

2024-12-14 14:40 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter4/task16/Task16.java
> +        int lastIndex = -1;
бесполезная переменная

2024-12-14 14:40 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter4/task16/Task16.java
> +        return lastIndex;
не логичнее `return -1;` написать?)

2024-12-14 14:40 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter4/task16/Task16.java
> +        int[] reducedArray;
Проще объявить внутри if. И отдельно объявить после if. Логика понятна, но ,пытаясь оперировать одной результирующей переменной, ты не получаешь от этого плюсов, зато получаешь минус в виде худшей ситабельности

2024-12-14 14:40 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter4/task16/Task16.java
> +            if (i < index) {
тернарный оператор

2024-12-14 14:40 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter4/task16/Task16.java
> +            if (getFirstIndex(removingValues, arr[i]) == -1) {
есть же isContains(), который лучше сюда ляжет, насколько вижу

2024-12-14 14:40 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter4/task16/Task16.java
> +        int[] removedArray = new int[arr.length];
filteredArray будет более понятно

2024-12-14 14:40 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter4/task16/Task16.java
> +            if (getFirstIndex(arr2, num) != -1) {
опять же, isContains()?

2024-12-14 14:40 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter4/task16/Task16.java
> +            if (getFirstIndex(arr1, num) != -1) {
и здессь

2024-12-26 17:52 UTC, KFalcon2022 commented
ПР закрыт, так как не обновлялся более недели. При необходимости проверки просьба открыть новый

2024-12-26 17:52 UTC, closed without merging