task16
KFalcon2022/intensive-tasks-2024 pull request #691
Opened 2024-12-11 06:58 UTC by Superbia101

2024-12-16 19:35 UTC, EvgeneZhurov requested changes

2024-12-16 19:35 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter4/task16/Task16.java
> +        return arr1.length != 0 && arr2.length != 0 && arr1.length == arr2.length;
arr2.length != 0 - условие избыточно. Если длина первого массива не равна нулю и их длины равны, то и длина второго не равна нулю

2024-12-16 19:35 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter4/task16/Task16.java
> +        if (arr1.length == arr2.length) {
Лучше поменять логическое условие на противоположное и поменять блоки кода в if местами, тогда читаемость кода повысится. Пропадет лишний уровень вложенности

2024-12-16 19:35 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter4/task16/Task16.java
> +            result[i] = lengthArr1 > lengthArr2 ? arr1[i] : -arr2[i];
На каждой итерации цикла будет считаться одно и то же значение.

2024-12-16 19:35 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter4/task16/Task16.java
> +            System.arraycopy(arr, 0, result, 0, lengthArr);
Если результат известен пора делать return

2024-12-16 19:35 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter4/task16/Task16.java
> +                    result = removeByIndex(result, i);
Можно написать эффективнее, откинуть дубли сначала и не пересоздавать массив каждый раз уменьшая его на один индекс. Еще эффективность зависит от длин массивов. Если arr меньше removingValues, то один алгоритм работы метода, если removingValues, то другой. Но в целом засчитано.

2024-12-17 06:34 UTC, Superbia101 commented on src/main/java/com/walking/intensive/chapter4/task16/Task16.java
> +            result[i] = lengthArr1 > lengthArr2 ? arr1[i] : -arr2[i];
Честно говоря не понял. Условное выражение вынести?

2024-12-17 07:26 UTC, EvgeneZhurov approved these changes

2024-12-17 07:26 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter4/task16/Task16.java
> +            result[i] = lengthArr1 > lengthArr2 ? arr1[i] : -arr2[i];
Вы считаете на каждой итерации цикла одно и то же логическое условие, которое можно посчитать 1 раз, не стоит заставлять процессор делать пустую работу. Реализация может быть разной, но в целом засчитано.

2024-12-17 07:26 UTC, closed without merging