Task1
KFalcon2022/intensive-tasks-2024 pull request #71
Opened 2024-11-17 20:28 UTC by beamingrus

2024-11-17 21:01 UTC, EvgeneZhurov requested changes

2024-11-17 21:01 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task1/Task1.java
> +        System.out.println("Введи возраст");
Если вы использовали ИИ, то просьба так не делать. Начните с самого начала.

2024-11-17 21:12 UTC, beamingrus commented on src/main/java/com/walking/intensive/chapter1/task1/Task1.java
> +        System.out.println("Введи возраст");
@EvgeneZhurov не использовал

2024-11-17 21:15 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task1/Task1.java
> +        System.out.println("Введи возраст");
Просьба начать с самого начала без try, циклов и прочих ненужных для решения задачи вещей. Метод должен возвращать строку согласно условию задачи, ввода с клавиатуры не требуется.

2024-11-17 21:49 UTC, beamingrus commented on src/main/java/com/walking/intensive/chapter1/task1/Task1.java
> +        System.out.println("Введи возраст");
в связи с чем возникло такое предположение? гуглом пользовался безусловно

2024-11-18 19:51 UTC, EvgeneZhurov requested changes
Просьба поправить замечания и продолжим общаться по существу.

2024-11-18 19:51 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task1/Task1.java
> +            if (ageLastNumber == 1) {
Попробуйте обойтись без двойных вложений.

2024-11-18 19:51 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task1/Task1.java
> +            sYears = "вам " + (age) + " лет";
лучше делать return, тогда переменная string не понадобится. поправьте везде в коде

2024-11-18 19:51 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task1/Task1.java
> +            } else sYears = "вам " + (age) + " лет";
Просьба выделить ветвление {}, даже если всего одна строка кода. Так принято в местном комьюнити.

2024-12-04 09:32 UTC, closed without merging