Task1
KFalcon2022/intensive-tasks-2024 pull request #717
Opened 2024-12-13 19:53 UTC by bansheeYV

С незнания немного напутал в очередности создания branches, надеюсь в остальном проблем не будет)

2024-12-13 20:27 UTC, EvgeneZhurov requested changes

2024-12-13 20:27 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task1/Task1.java
> +            result = "Вам " + age + " лет";
Лучше сразу сделать return, по одному return на каждое слово.

2024-12-13 20:27 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task1/Task1.java
> +          result = "Вам " + age + " лет";
У Вас 2 логических условия на слово "лет". Просьба составить логические условия так, чтобы на каждое слово было по одному return

2024-12-13 20:27 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task1/Task1.java
> +        return result;// Заглушка. При реализации - удалить
если называть возвращаемую переменную именем метода(без глагола), то читаемость кода повысится. А вообще переменная не нужна. если сразу делать return

2024-12-13 20:27 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task1/Task1.java
> +        if (age == 0 || (age % 100 > 10 && age % 100 < 20) || (age > 10 && age < 20)) {
Лишние скобки можно убрать, так читается легче.

2024-12-13 20:27 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task1/Task1.java
> +        }
после } можно поставить пустую строку, так читается легче. Блоки кода лучше отделять пустыми строками с обеих сторон, если это не начало или конец метода.

2024-12-13 20:27 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task1/Task1.java
> +        }
после } можно поставить пустую строку

2024-12-15 20:03 UTC, bansheeYV commented on src/main/java/com/walking/intensive/chapter1/task1/Task1.java
> +            result = "Вам " + age + " лет";
Исправил. Через return объективно компактнее, но немного лично для меня непривычно, пришлось переписывать логические условия, времени затратил на исправление больше, чем писал первый раз)

2024-12-17 07:14 UTC, EvgeneZhurov approved these changes

2024-12-17 07:14 UTC, closed without merging