Task2
KFalcon2022/intensive-tasks-2024 pull request #718
Opened 2024-12-13 19:55 UTC by bansheeYV

2024-12-13 20:32 UTC, EvgeneZhurov requested changes

2024-12-13 20:32 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task2/Task2.java
> +        if (flatNumber > (floorAmount * entranceAmount * 4)){
лишние скобки лучше убрать

2024-12-13 20:32 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task2/Task2.java
> +        if (flatNumber > (floorAmount * entranceAmount * 4)){
советую почитать про магическое число java и поправить в коде

2024-12-13 20:32 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task2/Task2.java
> +        int result = flatNumber / (floorAmount * 4);
старайтесь давать максимально релевантные имена. Имя result намекает, что это значение, которое будет возвращаться из метода, хотя к строке не имеет отношения.

2024-12-13 20:32 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task2/Task2.java
> +        if (flatNumber == 1 || flatNumber % 4 == 1){
У Вас заданное число исходов. Логичнее использовать switch case

2024-12-15 20:31 UTC, bansheeYV commented on src/main/java/com/walking/intensive/chapter1/task2/Task2.java
> +        if (flatNumber > (floorAmount * entranceAmount * 4)){
Исправил. Я понимал, что 4 у нас является магическим числом, но из условий у нас и нет других вариантов. Мы все равно не всегда может их избежать, например, в Task 5 мы используем готовые формулы и там есть 1/2 или 1/4, мы же не будем их отдельно описывать

2024-12-15 20:33 UTC, bansheeYV commented on src/main/java/com/walking/intensive/chapter1/task2/Task2.java
> +        int result = flatNumber / (floorAmount * 4);
Исправил. Банальная лень, использовал одну и ту же переменную для промежуточных вычислений

2024-12-16 19:10 UTC, EvgeneZhurov approved these changes

2024-12-16 19:10 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task2/Task2.java
> +        int numberOfFlats = 4;
лучше стараться избегать предлогов в названиях меняя местами слова. Так же старайтесь давать максимально релевантные названия переменным.

2024-12-16 19:10 UTC, closed without merging