Task4
KFalcon2022/intensive-tasks-2024 pull request #720
Opened 2024-12-13 19:56 UTC by bansheeYV

2024-12-13 20:45 UTC, EvgeneZhurov requested changes

2024-12-13 20:45 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task4/Task4.java
> +            return result = "Бесконечное множество решений.";
не требуется присваивать переменной значение, чтобы его вернуть. Можно вернуть строку и без присвоения. Просьба поправить везде в коде.

2024-12-13 20:45 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task4/Task4.java
> +        double discriminant = (b * b) - (4 * a * c);
старайтесь объявлять переменную максимально близко к месту первого использования. Если сценарий в следующем if выполнит return получится, что переменная была заведена зря.

2024-12-13 20:45 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task4/Task4.java
> +        if (a == 0 && b == 0 && c == 00){
00 - тут требуется пояснение зачем так писать?

2024-12-13 20:45 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task4/Task4.java
> +        double discriminant = (b * b) - (4 * a * c);
много лишних ненужных скобок. Меньше символов - легче читается. Просьба поправить везде в коде

2024-12-13 20:45 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task4/Task4.java
> +        if (discriminant < 0 || (a == 0 && b == 0)){
лишние скобки

2024-12-13 20:45 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task4/Task4.java
> +        if (discriminant > 0 && a == 0){
если a = 0 уравнение не является квадратным и дискриминант считать не нужно. Ранее были проверки на неположительный дискриминант, он точно положительный, если существует.

2024-12-13 20:45 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task4/Task4.java
> +        if (discriminant > 0){
discriminant > 0 - он и так положительный

2024-12-13 20:45 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task4/Task4.java
> +                result = "Количество решений: 2. Корни: " + x1 + ";" + x2;
лучше сделать return

2024-12-16 06:21 UTC, bansheeYV commented on src/main/java/com/walking/intensive/chapter1/task4/Task4.java
> +        if (a == 0 && b == 0 && c == 00){
Исправил. Просто описка

2024-12-16 19:12 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task4/Task4.java
> +        if (discriminant < 0 || a == 0 && b == 0){
старайтесь качественно отрабатывать замечания. Писал ранее: старайтесь объявлять переменную максимально близко к месту первого использования. Если сценарий в верхнем if выполнит return получится, что переменная была заведена зря.

2024-12-16 19:14 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task4/Task4.java
> +        String result = "";
Если переменной не присваивается значение, это может означать, что ей здесь не место.

2024-12-16 19:14 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task4/Task4.java
> +            result = "Количество решений: 2. Корни: " + x1 + ";" + x2;
Лучше сделать return, код будет читаться легче.

2024-12-17 06:50 UTC, EvgeneZhurov requested changes

2024-12-17 06:50 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter1/task4/Task4.java
> +        } else {
После return не ставят else.

2024-12-17 07:00 UTC, bansheeYV commented on src/main/java/com/walking/intensive/chapter1/task4/Task4.java
> +        } else {
Не знал, исправил

2024-12-17 07:17 UTC, EvgeneZhurov approved these changes

2024-12-17 07:17 UTC, closed without merging