Task17
KFalcon2022/intensive-tasks-2024 pull request #724
Opened 2024-12-15 03:18 UTC by Neverhoodof

2024-12-16 20:59 UTC, EvgeneZhurov requested changes

2024-12-16 20:59 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter4/task17/Task17.java
> +        int tempValue;
если переменной не задается значение при объявлении, это может указывать на то, что ей здесь не место. Старайтесь создавать переменные с минимальной областью видимости

2024-12-16 20:59 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter4/task17/Task17.java
> +        int len = array.length - 1;
старайтесь давать максимально релевантные имена, без сокращений.

2024-12-16 20:59 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter4/task17/Task17.java
> +        for (int j = len; j >= 1; j--) {
обычно счетчик первого уровня вложенности называют i

2024-12-16 20:59 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter4/task17/Task17.java
> +            for (int i = 0; i < len; i++) {
обычно счетчик второго уровня вложенности называют j

2024-12-16 20:59 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter4/task17/Task17.java
> +            for (int i = 0; i < len; i++) {
не стоит каждый раз идти до конца саммита, нужно идти до конца неотсортированной части, которая при каждой итерации цикла становится на единицу меньше.

2024-12-16 20:59 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter4/task17/Task17.java
> +                    array[i] = array[i + 1];
Если при полном проходе цикла ни один элемент не поменялся пора выходить из метода

2024-12-18 15:25 UTC, Neverhoodof commented on src/main/java/com/walking/intensive/chapter4/task17/Task17.java
> +        int tempValue;
Почему-то думалось, что постоянно объявлять переменную в теле цикла - плохая затея.

2024-12-18 18:11 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter4/task17/Task17.java
> +        int tempValue;
создайте массив в несколько тысяч цисел и сравните. По памяти тоде не будет работать примерно так же. Так же почитайте об этом более подробно. Ничего плохого в этом нет.

2024-12-18 18:14 UTC, EvgeneZhurov approved these changes

2024-12-18 18:14 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter4/task17/Task17.java
> +        boolean isSwapped;
эту переменную лучше объявлять внутри цикла, где ей и место.

2024-12-18 18:14 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter4/task17/Task17.java
> +            for (int j = 0; j < comparisonRange - i; j++) {
бло кода for можно отделить пустыми строками с обеих сторон.

2024-12-18 18:14 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter4/task17/Task17.java
> +        }
можно поставить пустую строку после }

2024-12-18 18:14 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter4/task17/Task17.java
> +                    int tempValue = array[j];
и так понятно, что это Value, можно просто temp

2024-12-18 18:15 UTC, closed without merging

2024-12-18 18:15 UTC, EvgeneZhurov commented
Поздравляю с окончанием курса