Task3
KFalcon2022/intensive-tasks-2024 pull request #73
Opened 2024-11-17 20:40 UTC by ilya-baykalov

2024-11-17 23:32 UTC, Zawadskiy requested changes

2024-11-17 23:32 UTC, Zawadskiy commented on src/main/java/com/walking/intensive/chapter1/task3/Task3.java
> +        if (year % 400 == 0) {
Логику строк 36-44 можно записать как одно boolean вііражение.

2024-11-17 23:32 UTC, Zawadskiy commented on src/main/java/com/walking/intensive/chapter1/task3/Task3.java
> +        } else if (year % 100 == 0) {
Когда у нас есть return в if, тогда міі не пишем else/else if (вместо else if просто if).

2024-11-18 07:31 UTC, ilya-baykalov commented on src/main/java/com/walking/intensive/chapter1/task3/Task3.java
> +        if (year % 400 == 0) {
сообразил, спасибо

2024-11-18 15:12 UTC, closed without merging