Task16
KFalcon2022/intensive-tasks-2024 pull request #732
Opened 2024-12-15 20:55 UTC by iamlonelyplanet

Прошу совета в методах multiplyEach и isSimilar.

2024-12-18 16:12 UTC, PuccaGTS requested changes
Уберите ненужные файлы, поправьте комментарии, подумайте, как можно оптимизировать некоторые моменты.

2024-12-18 16:12 UTC, PuccaGTS commented on src/main/java/com/walking/intensive/chapter2/task10/Lesson7_Task4_Recurse.java
Этого файла в PR не должно быть.

2024-12-18 16:12 UTC, PuccaGTS commented on src/main/java/com/walking/intensive/chapter4/task16/Printer.java
Этот файл тоже тут не нужен.

2024-12-18 16:12 UTC, PuccaGTS commented on src/main/java/com/walking/intensive/chapter4/task16/point.java
И этот тут тоже не нужен:)

2024-12-18 16:12 UTC, PuccaGTS commented on src/main/java/com/walking/intensive/chapter4/task16/Task16.java
> +            return multiplyEach(arr2, arr1); /* Прошу коммент от ревьюера: правильно ли я использовал тут рекурсивную
Выглядит очень сложно и костыльно, почему просто не сравнить размеры и дальше использовать больший размер?)

2024-12-18 16:12 UTC, PuccaGTS commented on src/main/java/com/walking/intensive/chapter4/task16/Task16.java
> +        boolean isFirstArrayBigger = arr1.length >= arr2.length;
Тоже выглядит сложновато
Можно попробовать первой операцией дополнить нулями массив, чтобы массивы были одинаковой длины, а потом просто вычитать.

2024-12-18 16:12 UTC, PuccaGTS commented on src/main/java/com/walking/intensive/chapter4/task16/Task16.java
> +        if (isEmpty(arr1) || isEmpty(arr2)) { // Прошу совета: эта проверка лишняя, но ускорит при пустом массиве. Так?
в данном случае да

2024-12-18 17:12 UTC, iamlonelyplanet commented on src/main/java/com/walking/intensive/chapter4/task16/Task16.java
> +        boolean isFirstArrayBigger = arr1.length >= arr2.length;
Исправлено

2024-12-18 17:12 UTC, iamlonelyplanet commented on src/main/java/com/walking/intensive/chapter4/task16/Task16.java
> +            return multiplyEach(arr2, arr1); /* Прошу коммент от ревьюера: правильно ли я использовал тут рекурсивную
Казалось, что такой код будет лаконичнее. Исправил.

2024-12-22 10:37 UTC, PuccaGTS approved these changes

2024-12-22 10:37 UTC, closed without merging