Task6
KFalcon2022/intensive-tasks-2024 pull request #735
Opened 2024-12-16 09:17 UTC by bansheeYV

2024-12-17 18:56 UTC, EvgeneZhurov requested changes

2024-12-17 18:56 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter2/task6/Task6.java
> +        } else {
после return не пишут else

2024-12-17 18:56 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter2/task6/Task6.java
> +            return getGcdByEuclideanAlgorithm(m, n - m);
в алгоритме используется остаток от деления, а не вычитание

2024-12-17 18:56 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter2/task6/Task6.java
> +                n = n -m;
код необходимо выравнивать.

2024-12-17 18:56 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter2/task6/Task6.java
> +        }
после } можно поставить пустую строку

2024-12-17 18:56 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter2/task6/Task6.java
> +                m = m - n;
неэффективно использовать вычитание.

2024-12-18 08:32 UTC, bansheeYV commented on src/main/java/com/walking/intensive/chapter2/task6/Task6.java
> +            return getGcdByEuclideanAlgorithm(m, n - m);
Я согласен, что более интересно написать через рекурсию, но тогда у меня не проходит тест на (0, 20), или при кривой проверка на валидность выдает 20, или с корректной не проходит тест. Запушил с рекурсией

2024-12-18 17:52 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter2/task6/Task6.java
> +            return getGcdByEuclideanAlgorithm(m, n - m);
я писал не про рекурсию, а про остаток от деления.

2024-12-18 17:54 UTC, EvgeneZhurov requested changes

2024-12-18 17:54 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter2/task6/Task6.java
> +                m = m - n;
просьба написать более эффективный алгоритм

2024-12-18 18:58 UTC, bansheeYV commented on src/main/java/com/walking/intensive/chapter2/task6/Task6.java
> +            return getGcdByEuclideanAlgorithm(m, n - m);
Значит неправильно понял. Но теперь уже я хочу понять как "изолировать" часть с рекурсией. Вынес в отдельный метод, теперь нет конфликта, тесты все проходят

2024-12-18 19:37 UTC, EvgeneZhurov approved these changes
ок, принято. Предлагаю двигаться дальше по курсу. Удачи.

2024-12-18 19:37 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter2/task6/Task6.java
> +    static int recursion(int m, int n) {
лучше добавить модификатор доступа privat

2024-12-18 19:37 UTC, closed without merging