task19
KFalcon2022/intensive-tasks-2024 pull request #741
Opened 2024-12-17 06:48 UTC by Superbia101

По правде говоря, я не удовлетворён кодом) - я чувствую, что можно сделать красивее, элегантнее, без постоянного повтора почти одинаковых условий, но пока не знаю как)

В любом случае, большое спасибо Вам! За навыки)

2024-12-17 11:50 UTC, Superbia101 commented
Вообще, я не уверен в решении)
Ещё раз проверил - вроде работает))
Но всё ещё не уверен

2024-12-17 11:51 UTC, Superbia101 commented
Просто случайно до него дошёл и сам удивлюсь, если оно рабочее.

2024-12-20 07:00 UTC, KFalcon2022 requested changes

2024-12-20 07:00 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter5/task19/Parallelepiped.java
> +        setX1(x1);
в конструкторе обычно используется явное присваивание. Задача сеттеров и геттеров обеспечивать инкапсуляцию за пределами класса. А внутри ты волен вертеть своим объектом и его полями как угодно

2024-12-20 07:00 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter5/task19/Parallelepiped.java
> +    private double x1, y1, z1, x2, y2, z2;
и для переменных, и для полей: каждое объявление на своей строке

2024-12-20 07:00 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter5/task19/Parallelepiped.java
> +    private double x1, y1, z1, x2, y2, z2;
Кроме того, а точно ли нам удобно взаимодействовать с 6 непонятными числами? Особенно если смотреть на ситуацию с точки зрения **объектно**-ориентированного программирования и того факта, что эти числа - координаты двух **точек**

2024-12-20 07:00 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter5/task19/Parallelepiped.java
> +    static public boolean isIntersectParallelepiped(Parallelepiped objectA, Parallelepiped objectB) {
public static. Порядок модификаторов достаточно строго определен и является общепринятым

И статик-метод - странная история. Parallelepiped - это некая сущность, объекты которой могут обладать каким-то поведением. Когда ты создаешь статик-метод - ты ломаешь эту логику, фактически возвращаясь из ООП в процедурный стиль

Конкретно здесь выглядят логичными два вариант:
1. Это должен быть не статик-метод. Тогда текущий объект (this) можно будет проверять на пересечение с другим параллелепипедом, переданном в параметре
2. Это поведение - вообще не ответственность класса Parallelepiped и принадлежит иной сущности, как-то контролирующей и обрабатывающей параллелепипеды/фигуры/что-тотретье

2024-12-20 07:00 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter5/task19/Parallelepiped.java
> +        double min1, min2, max1, max2;
одна переменная - одна строка

2024-12-20 07:00 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter5/task19/Parallelepiped.java
> +        switch (coordinate) {
не логичнее передать нужные значения координат параметрами? Зачем городить огород со switch-case?

2024-12-20 07:00 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter5/task19/Parallelepiped.java
> +    public void setX1(double x) {
а точно ли наш параллелепипед должен быть изменяемым? Что нам это дает?

2024-12-20 07:00 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter5/task19/Parallelepiped.java
> +            if (x == getX2()) {
опять же, более оправдано работать с полем напрямую, а не через геттер:
`x == this.x`

2024-12-20 07:00 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter5/task19/Parallelepiped.java
> +        } catch (Exception ex) {
Хорошо, что ты стараешься разобраться с темами, до которых еще не дошли. Но конкретно здесь - в чем отличие того, что ты написал, от примерно такого:

```java
if (z == getZ1() {
    System.out.println("Главная диагональ должна находиться в объёме(3-х плоскостях). " +
                        "Такой параллелограмм не может существовать!");
    return;
}

this.z2 = z;
```
?

2024-12-20 07:00 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter5/task19/Sphere.java
> +    }
набор замечаний полностью аналогичен указанным в предыдущем классе

2024-12-20 07:00 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter5/task19/Parallelepiped.java
> +    static public boolean isIntersectParallelepiped(Parallelepiped objectA, Parallelepiped objectB) {
Также остается вопрос - а нужен ли этот метод в принципе? У тебя не стоит задачи проверять пересечение параллелепипедов. Если бы был общий предок параллелепипеда и сферы - условно, фигура - было бы логично. Но какая ценность в текущей реализации?

2024-12-20 07:00 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter5/task19/Task19.java
> +            testX = minCoordinateX;
тело if и циклов всегда заключается в {}. Даже однострочное

2024-12-20 07:00 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter5/task19/Task19.java
> +        double testX = sphere.getX();
Название переменной не отражает суть

2024-12-20 07:00 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter5/task19/Task19.java
> +        double lengthParallelepiped = Math.abs(parallelepiped.getX1() - parallelepiped.getX2());
вот такая история - получение длины стороны - хороший претендент на метод параллелепипеда

2024-12-20 07:19 UTC, Superbia101 commented on src/main/java/com/walking/intensive/chapter5/task19/Parallelepiped.java
> +        setX1(x1);
понял

2024-12-20 07:20 UTC, Superbia101 commented on src/main/java/com/walking/intensive/chapter5/task19/Parallelepiped.java
> +    static public boolean isIntersectParallelepiped(Parallelepiped objectA, Parallelepiped objectB) {
думал идти шаг за шагом))

2024-12-20 07:22 UTC, Superbia101 commented on src/main/java/com/walking/intensive/chapter5/task19/Parallelepiped.java
> +        switch (coordinate) {
скорее всего, глаз за мылился - я несколько раз полностью меня функцию, соответственно реализация менялась - для последнего варианта, так и нужно было)

2024-12-20 07:23 UTC, Superbia101 commented on src/main/java/com/walking/intensive/chapter5/task19/Parallelepiped.java
> +        } catch (Exception ex) {
Хотел попробовать, я думал будет не так работать - я хотел чтобы, при не выполнении условия валидации, выполнение кода останавливалось - не вышло. оставил наработки

2024-12-20 07:24 UTC, Superbia101 commented on src/main/java/com/walking/intensive/chapter5/task19/Task19.java
> +            testX = minCoordinateX;
просто зевнул видимо)

2024-12-20 07:24 UTC, Superbia101 commented on src/main/java/com/walking/intensive/chapter5/task19/Parallelepiped.java
> +    private double x1, y1, z1, x2, y2, z2;
обдумаю

2024-12-20 07:25 UTC, Superbia101 commented
Спасибо)
Исправлю!)

2024-12-22 06:30 UTC, Superbia101 commented
Всё исправил, не стал только делать отдельный метод для определения длин сторон параллелограмма - я менял код и вычисления и так хорошо "встали". На мой взгляд смотрится органично)

2025-01-03 20:14 UTC, EvgeneZhurov reviewed
В целом огромный респект. Идея супер. Как можно было улучшить код: Можно было ввести класс Point и не развлекаться с массивами, задавать все нужные координаты этими объектами. Для поиска ближайшей координаты можно было не создавать массив присваивая минимальные значения и длины, а можно было создать объект Point сразу сравнивая с максимальными и минимальными значениями координат или нужных. Создавать testSphere не требовалось. У Вас есть две координаты в пространстве, можно и без создания объекта посчитать квадрат расстояния и сравнить с квадратом радиуса. Но в целом огромный респект. Остальное думаю придет с опытом и общением с Егором. Я готов зачесть задачу. Как Егор заопрувит свою часть.

2025-01-03 20:14 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter5/task19/Parallelepiped.java
> +    private double[] pointNumberOne = new double[3];
слово Number можно выкинуть без ущерба для названия

2025-01-03 20:15 UTC, EvgeneZhurov commented
после опрува Егора напишите мне, я закрою PR и внесу в таблицу результат

2025-01-04 10:19 UTC, closed without merging