Task10
KFalcon2022/intensive-tasks-2024 pull request #750
Opened 2024-12-17 14:22 UTC by bansheeYV

2024-12-18 20:08 UTC, EvgeneZhurov requested changes

2024-12-18 20:08 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter2/task10/Task10.java
> +        return string.toLowerCase().replaceAll("[\\p{Punct}\\s]", "");
без регекс, стримов и прочих тем, выходящих за рамки курса.

2024-12-19 11:41 UTC, bansheeYV commented on src/main/java/com/walking/intensive/chapter2/task10/Task10.java
> +        return string.toLowerCase().replaceAll("[\\p{Punct}\\s]", "");
Убрал regex, в цикле нарезал строку на символы (подстроки) через .substring() и проверил каждый элемент на наличие пунктуации

2024-12-19 18:52 UTC, EvgeneZhurov requested changes

2024-12-19 18:52 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter2/task10/Task10.java
> +        if (inputString == null || inputString.length() < 2 || inputString.isEmpty()){
если заглянуть внутрь метода inputString.isEmpty(), то можно заметить, что условие дублируется и idea просвечивает варнингом. Не игнорируйте их

2024-12-19 18:52 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter2/task10/Task10.java
> +        StringBuilder builder = new StringBuilder(removePunctuation(inputString));
Есть два варианта развития событий. Могу засчитать Вам задачу или попросить переписать все без создания строк проходя по входящей строке слева направо и одновременно наоборот перескакивая символы, если они не являются буквами сравнивая попарно например в нижней раскладке, так метод будет работать эффективнее. Отпишите как предпочитаете.

2024-12-19 20:25 UTC, bansheeYV commented on src/main/java/com/walking/intensive/chapter2/task10/Task10.java
> +        if (inputString == null || inputString.length() < 2 || inputString.isEmpty()){
Имеется в виду, что .isEmpty() проверяет на длину (0) и после inputString.length() < 2 нет смысла этой проверки?

2024-12-19 20:49 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter2/task10/Task10.java
> +        if (inputString == null || inputString.length() < 2 || inputString.isEmpty()){
да

2024-12-20 08:55 UTC, bansheeYV commented on src/main/java/com/walking/intensive/chapter2/task10/Task10.java
> +        StringBuilder builder = new StringBuilder(removePunctuation(inputString));
Поправил первый вариант и дописал альтернативный с перебором символов. Я так понимаю, альтернатива эффективнее по двум причинам - мы не создаем новых строк и во втором случае перебор идет только до половины строки, что явно быстрее, я правильно понял?
Если Вас не затруднит, то посмотрите, пожалуйста, Task 8, по ней и комментариев новых, но она и не закрыта
https://github.com/KFalcon2022/intensive-tasks-2024/pull/738

2024-12-24 06:58 UTC, EvgeneZhurov approved these changes

2024-12-24 06:58 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter2/task10/Task10.java
> +        StringBuilder builder = new StringBuilder(removePunctuation(inputString));
верно, не совсем до половины.

2024-12-24 06:58 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter2/task10/Task10.java
> +            if (!Character.isLetter(checkCharLeft)) {
можно чуть эффективнее, здесь лучше использовать while, потому что нижний if отрабатывая continue возвращает код на проверку уже отработанного блока кода заставляя его проверять уже проделанную работу

2024-12-24 06:58 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter2/task10/Task10.java
> +            char checkCharLeft = inputString.toLowerCase().charAt(i);
Слово check читается как глагол, а название переменной имя существительное.

2024-12-24 06:58 UTC, closed without merging