Task16
KFalcon2022/intensive-tasks-2024 pull request #755
Opened 2024-12-18 21:23 UTC by zemaumka

Задача16

2024-12-19 19:55 UTC, EvgeneZhurov requested changes

2024-12-19 19:55 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter4/task16/Task16.java
> +
int[] arr1 = new int[]{1, 2, 3};
        int[] arr2 = new int[]{1, 2, 3, 4};
ожидалось false

2024-12-19 19:55 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter4/task16/Task16.java
> +            result[i] = i >= Math.min(arr1.length, arr2.length) ? 0 : arr1[i] * arr2[i];
результат уже известен

2024-12-19 19:55 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter4/task16/Task16.java
> +            result[i] = i >= Math.min(arr1.length, arr2.length) ? 0 : arr1[i] * arr2[i];
в целом логика неверная. Цикл должен быть до минимальной длины без лишних логических условий умножать значения одинаковых индексов.

2024-12-19 19:55 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter4/task16/Task16.java
> +        int[] tmp = new int[maxLength];
можно обойтись без введения второго массива

2024-12-26 17:11 UTC, zemaumka commented on src/main/java/com/walking/intensive/chapter4/task16/Task16.java
> +            result[i] = i >= Math.min(arr1.length, arr2.length) ? 0 : arr1[i] * arr2[i];
наименование массива result поменять? или что-то другое?

2025-01-03 17:25 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter4/task16/Task16.java
> +            result[i] = i >= Math.min(arr1.length, arr2.length) ? 0 : arr1[i] * arr2[i];
Имеется ввиду, что на каждой итерации цикла не нужно каждый раз считать выражение  Math.max(arr1.length, arr2.length) и Math.min(arr1.length, arr2.length) ? 0 тоже каждый раз не нужно считать, это неэффективно.

2025-01-03 17:29 UTC, EvgeneZhurov approved these changes

2025-01-03 17:29 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter4/task16/Task16.java
> +
лишняя пустая строка

2025-01-03 17:29 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter4/task16/Task16.java
> +        for (int i = 0; i < Math.max(arr1.length, arr2.length); i++) {
то же самое, что и в другом цикле, не нужно каждый раз считать одно и то же

2025-01-03 17:29 UTC, EvgeneZhurov commented on src/main/java/com/walking/intensive/chapter4/task16/Task16.java
> +            int element2 = i < arr2.length ? arr2[i] : 0;
и здесь тоже не нужно считать одно и то же на каждой итерации цикла

2025-01-03 17:29 UTC, closed without merging