Task4
KFalcon2022/intensive-tasks-2024 pull request #76
Opened 2024-11-17 21:35 UTC by ilya-baykalov

2024-11-18 00:11 UTC, Zawadskiy requested changes

2024-11-18 00:11 UTC, Zawadskiy commented on src/main/java/com/walking/intensive/chapter1/task4/Task4.java
> +        double D = b * b - 4 * a * c;
Дай переменной норм название (оно и так норм, но мне нужен пройденніій чекстайл=) )
[ERROR] /home/runner/work/intensive-tasks-2024/intensive-tasks-2024/src/main/java/com/walking/intensive/chapter1/task4/Task4.java:50:16: Name 'D' must match pattern '^[a-z][a-zA-Z0-9]*$'. [LocalVariableName]

2024-11-18 00:11 UTC, Zawadskiy commented on src/main/java/com/walking/intensive/chapter1/task4/Task4.java
> +                } else {
Если в блоке if есть return, то міі не пишем else.

2024-11-18 00:11 UTC, Zawadskiy commented on src/main/java/com/walking/intensive/chapter1/task4/Task4.java
>      static String solveEquation(double a, double b, double c) {
30 tests completed, 16 failed.
16 тестов померло) Исправь или убеди меня что ошибка в тестах)

2024-11-18 15:07 UTC, Zawadskiy requested changes

2024-11-18 15:07 UTC, Zawadskiy commented on src/main/java/com/walking/intensive/chapter1/task4/Task4.java
>      }
Ну почти. 
Количество решений: 1. Корень: 0.0, 1, 0, 0 FAILED

2024-11-18 15:18 UTC, ilya-baykalov commented on src/main/java/com/walking/intensive/chapter1/task4/Task4.java
>      }
Так это же из-за того, что тесты для целых чисел написаны
```
Expected :Количество решений: 1. Корень: 0
Actual   :Количество решений: 1. Корень: -0.0
```

![image](https://github.com/user-attachments/assets/66a7fb74-3ccb-481f-83a0-8648d522f7dc)

2024-11-18 16:45 UTC, Zawadskiy commented on src/main/java/com/walking/intensive/chapter1/task4/Task4.java
>      }
Почему -0 ? =)

2024-11-28 04:17 UTC, Zawadskiy commented
Срок внесения правок вышел, при необходимости ревью - откройте новый Pull Request

2024-11-28 04:17 UTC, closed without merging