Task13
KFalcon2022/intensive-tasks-2024 pull request #764
Opened 2024-12-19 23:47 UTC by andreyv24

2024-12-22 17:36 UTC, KFalcon2022 requested changes

2024-12-22 17:36 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter1/task5/Task5.java
> +}
этого класса не должно быть в ПР

2024-12-22 17:36 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter3/task13/Task13.java
> +                currentWateringCanVolume = wateringCanVolume - plants[i];
Достаточно оставить внутри if логику "наполнения" лейки и не придется городить огород с continue

2024-12-22 17:36 UTC, KFalcon2022 commented on src/test/java/com/walking/intensive/chapter1/task5/Task5Test.java
> +        assertArrayEquals(new double[]{4.615, 5.0, 12.0}, getHeights(12, 13, 5), 1e-10);
Этого класса в ПР быть не должно

2024-12-22 17:36 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter3/task13/Task13.java
> +            if (plants[i] <= 0) {
То есть мы можем дойти до конца грядки и понять, что все вычисления были избыточны, потому что входные данные некорректны?)

Логичнее вынести валидацию в отдельный метод и проверять все до основной логики. Дополнительный проход по циклу чаще всего будет дешевле, чем выполнение массы вычислений вхолостую

2024-12-22 17:36 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter3/task13/Task13.java
> +        return counter;
не стесняйся отделять логические блоки кода пустыми строками. Иначе весь метод сливается в одно полотно кода

2024-12-24 23:49 UTC, andreyv24 commented on src/main/java/com/walking/intensive/chapter3/task13/Task13.java
> +            if (plants[i] <= 0) {
> То есть мы можем дойти до конца грядки и понять, что все вычисления были избыточны, потому что входные  >  данные некорректны?)
Типа того. ))))

> Логичнее вынести валидацию в отдельный метод и проверять все до основной логики. Дополнительный           
 > проход по циклу чаще всего будет дешевле, чем выполнение массы вычислений вхолостую
Не задумывался об этом. Спасибо!

Вынес проверки в отдельный метод с прогоном по циклу на предмет неправильных значений.

2024-12-24 23:51 UTC, andreyv24 commented on src/main/java/com/walking/intensive/chapter1/task5/Task5.java
> +}
Это хвосты с Task5 тянутся в ПР других Task'ов. Устал уже удалять их.

2024-12-24 23:56 UTC, andreyv24 commented on src/main/java/com/walking/intensive/chapter3/task13/Task13.java
> +        return counter;
Добавил пустые строки. Годится ?

2024-12-25 00:16 UTC, andreyv24 commented on src/main/java/com/walking/intensive/chapter3/task13/Task13.java
> +                currentWateringCanVolume = wateringCanVolume - plants[i];
Вроде убрал "огород" с continue.

2024-12-25 00:17 UTC, andreyv24 commented on src/test/java/com/walking/intensive/chapter1/task5/Task5Test.java
> +        assertArrayEquals(new double[]{4.615, 5.0, 12.0}, getHeights(12, 13, 5), 1e-10);
Удалил файлы не относящиеся к Task13.

2024-12-26 18:05 UTC, KFalcon2022 requested changes

2024-12-26 18:05 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter3/task13/Task13.java
> +
лишняя пустая строка

2024-12-26 18:05 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter3/task13/Task13.java
> +    static boolean checkInputData(int[] plants, int wateringCanVolume) {
булеан-методы традиционно именуются с if

2024-12-26 18:05 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter3/task13/Task13.java
> +                currentWateringCanVolume = currentWateringCanVolume - plants[i];
Можно упростить: `currentWateringCanVolume -= plants[i];`

2024-12-26 18:05 UTC, KFalcon2022 commented
На будущее: чтобы убрать файл из ПР его не нужно удалять. Нужно лишь привести его к виду, в котором он находится в целевой ветке. В твоем случае - в master

2025-01-04 21:06 UTC, andreyv24 commented on src/main/java/com/walking/intensive/chapter3/task13/Task13.java
> +
Убрал строку.

2025-01-04 21:09 UTC, andreyv24 commented on src/main/java/com/walking/intensive/chapter3/task13/Task13.java
> +                currentWateringCanVolume = currentWateringCanVolume - plants[i];
Согласен. Исправлено!

2025-01-04 21:14 UTC, andreyv24 commented on src/main/java/com/walking/intensive/chapter3/task13/Task13.java
> +    static boolean checkInputData(int[] plants, int wateringCanVolume) {
Ок. Поменял.

2025-02-04 18:37 UTC, KFalcon2022 approved these changes

2025-02-04 18:37 UTC, closed without merging