Task 12
KFalcon2022/intensive-tasks-2024 pull request #766
Opened 2024-12-20 13:28 UTC by bansheeYV

2024-12-22 17:51 UTC, KFalcon2022 requested changes
Перемудрил

2024-12-22 17:51 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter3/task12/Task12.java
> +        }
Весьма избыточный подход выше. Допустимых значений всего два - '0' и '1'. При расчете результата нужны только ситуации, когда символ по индексу  - '1'. Не вижу ни одной причины взаимодействовать с входящей строкой или ее элементами как с числами

2024-12-22 17:51 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter3/task12/Task12.java
> +        }
Кроме того, объединять валидацию и преобразования чаще всего плохая идея. Есть большой риск сделать много работы вхолостую

2024-12-23 07:45 UTC, bansheeYV commented on src/main/java/com/walking/intensive/chapter3/task12/Task12.java
> +        }
Согласен, перемудрил) Исправил

2024-12-26 19:53 UTC, KFalcon2022 approved these changes
Замечания мелкие, но стоит поправить для себя. Зачтено авансом

2024-12-26 19:53 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter3/task12/Task12.java
> +            if (!Character.isDigit(baskets.charAt(i)) || Integer.parseInt(String.valueOf(baskets.charAt(i))) > 1) {
Не проще явно проверить, что не '0' и не '1'?

2024-12-26 19:53 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter3/task12/Task12.java
> +
лишняя пустая строка

2024-12-26 19:53 UTC, closed without merging