Task10
KFalcon2022/intensive-tasks-2024 pull request #767
Opened 2024-12-20 16:29 UTC by stillwearit

2024-12-22 17:20 UTC, KFalcon2022 requested changes

2024-12-22 17:20 UTC, KFalcon2022 commented on build.gradle
> +        languageVersion = JavaLanguageVersion.of(23)
Этого в PR быть не должно

2024-12-22 17:20 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter2/task10/Task10.java
> +        if (leftIndex == rightIndex) {
Как это может произойти, если выше ты проверяешь, что строка не пуста?

2024-12-22 17:20 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter2/task10/Task10.java
> +        char left = inputString.charAt(leftIndex);
зачем делать это до цикла?

2024-12-22 17:20 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter2/task10/Task10.java
> +            } else if (Character.isLetter(left) && Character.isLetter(right)) {
Зачем явно описанное условие? К этому момент возможен ровно один случай - оба символа являются буквами, т.е. достаточно обычного `else`

2024-12-22 17:20 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter2/task10/Task10.java
> +                if (!equal) {
Избыточная переменная. Чем
```java
boolean equal = left == right;
if (!equal) {
    return false;
}
```

отличается от
```java
if (left != right) {
    return false;
}
```
?

2024-12-24 16:29 UTC, stillwearit commented on src/main/java/com/walking/intensive/chapter2/task10/Task10.java
> +        if (leftIndex == rightIndex) {
я так сделала проверку для строки из одной буквы... нужно как-то по=другому её исключить?

2024-12-24 16:40 UTC, stillwearit commented on build.gradle
> +        languageVersion = JavaLanguageVersion.of(23)
а как-то можно это убрать теперь?

2024-12-26 18:01 UTC, KFalcon2022 approved these changes
Замечание мелкое, задача зачтена

2024-12-26 18:01 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter2/task10/Task10.java
> +                if (left != right) {
вот тут как раз к else if и можно свести теперь, соединив этот if и else выше

2024-12-26 18:01 UTC, closed without merging