Task 1
KFalcon2022/intensive-tasks-2024 pull request #769
Opened 2024-12-21 00:08 UTC by nothaionde

Сорри, что с опозданием, прям сильно много основной работы в декабре

2024-12-22 17:09 UTC, KFalcon2022 requested changes
Решение хорошее, но оформление стоит доработать

2024-12-22 17:09 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter1/task1/Task1.java
> +	static String getAgeString(int age) {
Опять же, поправь кодстайл в IDEA)

2024-12-22 17:09 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter1/task1/Task1.java
> +		String suffix;
не стесняйся отделять логические блоки кода пустыми строками. Иначе весь метод сливается в сплошное полотно символов

2024-12-22 17:09 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter1/task1/Task1.java
> +			suffix = "лет";
Лучше несколько return, чем такая портанка if-else. Как вариант - выделить получение суффикса в отдельный метод, ибо сейчас выглядит переусложненным

2024-12-23 05:44 UTC, nothaionde commented on src/main/java/com/walking/intensive/chapter1/task1/Task1.java
> +			suffix = "лет";
Выделил в отдельный метод, кодстайл поставил согласно схеме проекта

2024-12-26 17:55 UTC, KFalcon2022 approved these changes
Замечание легкое для исправление, задача зачтена небольшим авансом

2024-12-26 17:55 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter1/task1/Task1.java
> +        } else if (lastDigit == 1) {
избыточный else. Если сработает if выше - программа до этой строчки не дойдет и выйдет из функции раньше. Достаточно обычных if()

2024-12-26 17:55 UTC, closed without merging