Task 2
KFalcon2022/intensive-tasks-2024 pull request #770
Opened 2024-12-21 01:23 UTC by nothaionde

2024-12-22 17:12 UTC, KFalcon2022 requested changes
Решение хорошее, оформление стоит доработать

2024-12-22 17:12 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter1/task2/Task2.java
> +	}
отступ - 4 символа

2024-12-22 17:12 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter1/task2/Task2.java
> +		int flatsPerEntrance = maxFlatPerFloor * floorAmount;
не хватает пустых строк между логически завершенными блоками кода

2024-12-22 17:12 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter1/task2/Task2.java
> +		String elevatorSide = (localFlatNumber % 2 == 0) ? "справа" : "слева";
Избыточные скобки здесь и в тернарке ниже

2024-12-22 17:12 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter1/task2/Task2.java
> +		return flatNumber + " кв - "
Конкатенация - допустимый подход. Но можешь попробовать `String#formatted()` - будет смотреться аккуратнее

2024-12-23 06:15 UTC, nothaionde commented on src/main/java/com/walking/intensive/chapter1/task2/Task2.java
> +		return flatNumber + " кв - "
Расставлены отступы между логически завершенными блоками, возврат функции переделан через String#format(), мне кажется, что в данном случае format выглядит лучше, т.к. мы видим весь возврат в одной строке, а плейсхолдеры в другой, код читаемый(?).

2024-12-26 17:55 UTC, KFalcon2022 approved these changes
Теперь отлично)

2024-12-26 17:55 UTC, closed without merging