Task18
KFalcon2022/intensive-tasks-2024 pull request #773
Opened 2024-12-22 15:00 UTC by ElowLiet

2024-12-22 17:55 UTC, KFalcon2022 requested changes

2024-12-22 17:55 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter4/task18/Task18.java
> +        }
выглядит, будто лучше заменить на тернарный оператор. Чуть что, для ситуаций, когда условий несколько или по иным причинам в одну строчку читать тяжеловато, предлагаю примерно такой формат записи:

```java
return girlAges == null || girlAges.length == 0
    ? -1
    : findBinary(girlAges, targetAge, 0, girlAges.length - 1);
```

2024-12-22 17:55 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter4/task18/Task18.java
> +
пустая строка в начале метода - достаточно специфическая история. Чаще всего она не нужна

2024-12-22 17:55 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter4/task18/Task18.java
> +        if (array.length == 0) return -1;
тело if должно быть всегда заключено в {}. Даже однострочное или представленное одной операцией

2024-12-22 17:55 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter4/task18/Task18.java
> +        if (end - start == 1) return (target == array[end])
лишние скобки в условии тернарного выражения

2024-12-22 17:55 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter4/task18/Task18.java
> +                : (start == 0 ? -1 : array[start - 1]);
вложенное тернарное выражение - моветон, такие каскады тяжело читать

2024-12-22 17:55 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter4/task18/Task18.java
> +        // Старался сделать максимально коротко
коротко - вообще не всегда синоним "хорошо"

2024-12-22 17:55 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter4/task18/Task18.java
> +        return (target > array[middle])
лишние скобки

2024-12-22 17:55 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter4/task18/Task18.java
> +        if (end == start) return (target == array[start])
лишние скобки в условии тернарного выражения

2024-12-23 07:37 UTC, ElowLiet commented
Исправил

2024-12-26 17:57 UTC, KFalcon2022 requested changes

2024-12-26 17:57 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter4/task18/Task18.java
> +        if (end - start == 1) return target == array[end]
Тело if обязательно должно находиться в фигурных скобках

2024-12-26 17:57 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter4/task18/Task18.java
> +        if (target > array[middle]) {
логичнее здесь применить тернарку

2024-12-26 17:57 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter4/task18/Task18.java
> +
лишняя пустая строка

2025-01-27 20:55 UTC, KFalcon2022 commented
PR Закрыт, т.к. не было изменений более недели. При необходимости повторного ревью просьба открыть новый

2025-01-27 20:55 UTC, closed without merging