Task19
KFalcon2022/intensive-tasks-2024 pull request #776
Opened 2024-12-23 05:35 UTC by ardmtr

2025-01-02 20:51 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter5/task19/Parallelepiped.java
> +    private final Point pointA;
зачем нам дублировать имя класса в имени переменной? какую дополнительную информацию это даст?

2025-01-02 21:01 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter5/task19/Parallelepiped.java
> +
лишние пустые строки в начале и конце тела конструктора

2025-01-02 21:01 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter5/task19/Parallelepiped.java
> +    public Point[] vertices() {
методы именуются с глагола

2025-01-02 21:01 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter5/task19/Parallelepiped.java
> +
лишняя пустая строка

2025-01-02 21:01 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter5/task19/Parallelepiped.java
> +
повсеместно в начале методов

2025-01-02 21:01 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter5/task19/Parallelepiped.java
> +        double xC = (pointA.getX() + pointB.getX()) / 2;
Сокращения - плохая идея

2025-01-02 21:01 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter5/task19/Parallelepiped.java
> +    public Point getNearestVertices(Point point) {
А ближайшую точку для сферы мы рассчитать не можем?) идея на подумать

2025-01-02 21:01 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter5/task19/Parallelepiped.java
> +        double minDistanceToPoint = Double.MAX_VALUE;
собственно, а зачем? инициировать максимальным значением?

2025-01-02 21:01 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter5/task19/Parallelepiped.java
> +
лишние пустые строки в конце класса

2025-01-02 21:01 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter5/task19/Parallelepiped.java
> +    private final Point pointA;
в соседних классах аналогично

2025-01-02 21:01 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter5/task19/Point.java
> +        return Math.sqrt(Math.pow(p.getX() - x, 2) + Math.pow(p.getY() - y, 2) + Math.pow(p.getZ() - z, 2));
Тут бы выделить дополнительные переменные

2025-01-02 21:01 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter5/task19/Point.java
> +    public String toString() {
зачем?

2025-01-02 21:01 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter5/task19/Point.java
> +    public double distancePointToPoint(Point p) {
метод именуется с глагола

2025-01-02 21:01 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter5/task19/Point.java
> +        return "Point{" +
оператор принято переносить на новую строку. Я вижу, что тебе идея сгенерила метод, судя по всему. Но по дефолту далеко не все оно генерит корректно

2025-01-02 21:01 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter5/task19/Sphere.java
> +    final Point center;
приватные поля?

2025-01-02 21:01 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter5/task19/Sphere.java
> +            throw new Exception("радиус не может быть меньше 0");
обычно подобные валидации - задачи управляющего класса, а не конструктора

2025-01-02 21:01 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter5/task19/Sphere.java
> +            throw new Exception("радиус не может быть меньше 0");
Ну и checked-исключения для таких ситуаций плохо подходят - это ошибка выполнения, по сути. См. RuntimeException, unchecked exceptions

2025-01-02 21:01 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter5/task19/Sphere.java
> +        double cx = parallelepiped.getCenter().getX();
сокращения - зло

2025-01-02 21:01 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter5/task19/Sphere.java
> +        return (Math.abs(cx - x) < dx) || (Math.abs(cy - y) < dy) || (Math.abs(cz - z) < dz);
лишние скобки

2025-01-02 21:01 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter5/task19/Task19.java
> +        if (sphere.isInsideParallelepiped(parallelepiped)) {
contains и inside - из названий не следует различия логик проверки

2025-01-02 21:29 UTC, EvgeneZhurov commented
Point e = new Point(0, 0, 0);
      Point f = new Point(10, 10, 10);
      Parallelepiped parallelepiped = new Parallelepiped(e, f);

      Point g = new Point(-20, -20, 5);
      Sphere sphere = new Sphere(g, 1);

      Результат true, ожидалось false.

2025-01-02 21:37 UTC, EvgeneZhurov requested changes
Просьба исправить замечания

2025-01-27 20:54 UTC, KFalcon2022 commented
PR Закрыт, т.к. не было изменений более недели. При необходимости повторного ревью просьба открыть новый

2025-01-27 20:54 UTC, closed without merging