Task17
KFalcon2022/intensive-tasks-2024 pull request #791
Opened 2024-12-27 07:59 UTC by iamlonelyplanet

1. Прошу совета: как лучше/понятнее написать метод sortByQuicksort?
а) Используя перегрузку методов
б) Используя VarArgs (как я сделал в коммите)
2.  Вычисление опорного элемента по среднеарифметическому (min/max в массиве) - это было принципиальное условие задачи? Либо можно было просто брать в качестве опорного элемента любой элемент массива?

Спасибо!!

2024-12-29 04:32 UTC, PuccaGTS requested changes
> Прошу совета: как лучше/понятнее написать метод sortByQuicksort?
> а) Используя перегрузку методов
> б) Используя VarArgs (как я сделал в коммите)

Ни то и не другое, здесь не нужна перегрузка, т.к. в баблСорт нужно просто написать сортировку без всяких костылей, соответственно и varargs Вам тоже не понадобятся.

> Вычисление опорного элемента по среднеарифметическому (min/max в массиве) - это было принципиальное условие задачи? Либо можно было просто брать в качестве опорного элемента любой элемент массива?

В данном случае это условие задачи, а так есть много вариантов выбора опорного элемента и все они имею свои плюсы и минусы.

2024-12-29 04:32 UTC, PuccaGTS commented on src/main/java/com/walking/intensive/chapter4/task16/Task16.java
Изменения, которые не относятся к заданию, пушить в ПР не нужно)

2024-12-29 04:32 UTC, PuccaGTS commented on src/main/java/com/walking/intensive/chapter4/task17/Task17.java
> -    static int[] sortByQuicksort(int[] array) {
Не нужно менять сигнатуру метода, нужно реализовать именно тот метод, который предлагается в задании

2024-12-29 04:32 UTC, PuccaGTS commented on src/main/java/com/walking/intensive/chapter4/task17/Task17.java
> +            findMax(array);
очень сложно, пузырьковая сортировка выглядит намного проще:
1. Проходим по массиву двумя циклами
2. сравниваем два значения - текущее и следующее
3. через временную переменную меняем их местами, если текущее значение больше следующего

2024-12-29 04:32 UTC, PuccaGTS commented on src/main/java/com/walking/intensive/chapter4/task17/Task17.java
> +            findMax(array);
Она на то и пузырьковая, что время исполнения её О(n^2) в худшем случае)
А у Вас один цикл + вызов метода findMax, который принимает массив и возвращает интовое значение - на первый взгляд метод найдет максимальное в массиве и ничего не вернет, выглядит странно, нужно поправить

2024-12-29 04:32 UTC, PuccaGTS commented on src/main/java/com/walking/intensive/chapter4/task17/Task17.java
> +    static int[] sortByQuicksort(int[] array, int... borders) {
Если нужен такой метод для рекурсии, делайте его отдельно, не меняя сигнатуры

2024-12-29 04:32 UTC, PuccaGTS commented on src/main/java/com/walking/intensive/chapter4/task17/Task17.java
> +    static int findMax(int[] array, int... borders) {
Не нужна вам такая сигнатура

2024-12-29 04:32 UTC, PuccaGTS commented on src/main/java/com/walking/intensive/chapter4/task17/Task17.java
> +            right = borders[1];
Будет выход за пределы массива java.lang.ArrayIndexOutOfBoundsException если в качестве varargs передать одно значение

2024-12-29 04:32 UTC, PuccaGTS commented on src/main/java/com/walking/intensive/chapter4/task17/Task17.java
> +            int maxOfTwo = Math.max(array[i], array[i + 1]);
Строки 173, 174, 175 дубликат кода - одинаковый строки как в методе поиска минимального, так и в методе поиска максимального

2024-12-29 04:32 UTC, PuccaGTS commented on src/main/java/com/walking/intensive/chapter4/task17/Task17.java
> +            System.out.println("Результат отрицательный, значит, я накосячил, т.к. QuickSort по определению должен " +
По правилам форматирования "+" нужно перенести на новую строку

2025-01-05 18:06 UTC, iamlonelyplanet commented on src/main/java/com/walking/intensive/chapter4/task16/Task16.java
Извините, я не знаю, как исключить из ПР задачу 16. Я накосячил с этим делом с самого начала. Потом пытался удалить, не особо получилось.

2025-01-05 18:07 UTC, iamlonelyplanet commented
Извините, я не знаю, как исключить из ПР задачу 16. Я накосячил с этим делом с самого начала. Потом пытался удалить, не особо получилось.
Остальное, вроде, получилось! Особенно после вашего ревью моего таск 17.

2025-01-06 17:09 UTC, PuccaGTS approved these changes

2025-01-06 17:09 UTC, closed without merging