Task 18
KFalcon2022/intensive-tasks-2024 pull request #796
Opened 2024-12-27 13:39 UTC by iamlonelyplanet

Нужен совет: я сделал перегрузку метода. В предыдущем таске (17) делал при помощи VarArgs. Оба способа сработают и тут, и там. Но как лучше: через перегрузку, или через VarArgs? Спасибо!

2024-12-31 17:38 UTC, PuccaGTS requested changes

2024-12-31 17:38 UTC, PuccaGTS commented on src/main/java/com/walking/intensive/chapter4/task18/Task18.java
> +    static int find(int[] girlAges, int targetAge, int... borders) {
Не уловил момент зачем здесь использовать varargs, можно же просто массив.
Плюс я бы не делал перегрузку, в данном случае может это и выглядит логично, но в реальных кейсах можно будет вызвать не тот метод и всё пойдет не так, как хотелось бы, поэтому советую назвать метод по-другому:)

2025-01-01 08:38 UTC, iamlonelyplanet commented on src/main/java/com/walking/intensive/chapter4/task18/Task18.java
> +    static int find(int[] girlAges, int targetAge, int... borders) {
Спасибо, переделал, учёл замечания для переделки Task 17.

2025-01-01 08:59 UTC, PuccaGTS approved these changes
В целом всё гуд, аппрув
Но можно в метод не передавать массив из двух элементов, кажется, что это лишнее, намного читабельней и логичнее было сделать сигнатуру метода:
```java
static int findWithRecursion(int[] girlAges, int left, int right, int targetAge)
```
Ну или для границ придумать другие названия, но факт это то, что Вы всегда передаете два значения - левую и правую границу, и засовывать их в массив из двух элементов, а потом вызывать по индексам не лучшая идея, т.к. есть человеческий фактов + магические числа в коде смотрятся не очень:))) С наступившим Новым годом!

2025-01-01 08:59 UTC, closed without merging

2025-01-01 09:11 UTC, iamlonelyplanet commented
И вас с Новым годом! Спасибо за терпение и за знания.