Task4
KFalcon2022/intensive-tasks-2024 pull request #797
Opened 2024-12-27 13:50 UTC by quperino

2024-12-31 17:52 UTC, PuccaGTS requested changes
Давайте поправим

2024-12-31 17:52 UTC, PuccaGTS commented on src/main/java/com/walking/intensive/chapter1/task4/Task4.java
> +                s = "Количество решений: 2. Корни: " + x2 + "; " + x1;
Пробел между точкой с запятой не нужен, в условии его нет

2024-12-31 17:52 UTC, PuccaGTS commented on src/main/java/com/walking/intensive/chapter1/task4/Task4.java
> +        double discriminant = (Math.pow(b, 2)) - (4 * a * c);
Кажется, что в некоторых случаях нет необходимости считать дискриминант

2024-12-31 17:52 UTC, PuccaGTS commented on src/main/java/com/walking/intensive/chapter1/task4/Task4.java
> +        double discriminant = (Math.pow(b, 2)) - (4 * a * c);
Если передать значения 0, 0, -10, то получится уравнение вида:
0x^2 + 0x -10 = 0
-10 = 0 - количество решение тут 0, а у Вас Дискриминант есть и корни есть:)

2024-12-31 17:52 UTC, PuccaGTS commented on src/main/java/com/walking/intensive/chapter1/task4/Task4.java
> +            s = "Количество решений: 1. Корень: " + (-b / 2 * a);
При значениях 0, 0, 0 - хотелось бы получить "Бесконечное множество решений"
А у Вас - один корень)

2024-12-31 17:52 UTC, PuccaGTS commented on src/main/java/com/walking/intensive/chapter1/task4/Task4.java
> +        } else if (discriminant > 0) {
А вот сюда попадает кейс, когда a = 0, например:
0, -2, 2 или 0, 20, -40
У них один корень, т.к. уравнение получается линейное, то по Вашему кода Дискриминант положительный и корни вычисляются неверно.

2025-01-01 15:10 UTC, quperino commented on src/main/java/com/walking/intensive/chapter1/task4/Task4.java
> +                s = "Количество решений: 2. Корни: " + x2 + "; " + x1;
Исправил

2025-01-01 15:37 UTC, quperino commented on src/main/java/com/walking/intensive/chapter1/task4/Task4.java
> +        double discriminant = (Math.pow(b, 2)) - (4 * a * c);
Исправил

2025-01-01 15:37 UTC, quperino commented on src/main/java/com/walking/intensive/chapter1/task4/Task4.java
> +        double discriminant = (Math.pow(b, 2)) - (4 * a * c);
Исправил

2025-01-01 15:37 UTC, quperino commented on src/main/java/com/walking/intensive/chapter1/task4/Task4.java
> +            s = "Количество решений: 1. Корень: " + (-b / 2 * a);
Исправил

2025-01-01 15:38 UTC, quperino commented on src/main/java/com/walking/intensive/chapter1/task4/Task4.java
> +        } else if (discriminant > 0) {
Исправил

2025-01-04 17:01 UTC, PuccaGTS requested changes
Давайте поправим

2025-01-04 17:01 UTC, PuccaGTS commented on src/main/java/com/walking/intensive/chapter1/task4/Task4.java
> +            double discriminant = (Math.pow(b, 2)) - (4 * a * c);
Действительные корни отсутствуют при отрицательном дискриминанте

2025-01-04 17:01 UTC, PuccaGTS commented on src/main/java/com/walking/intensive/chapter1/task4/Task4.java
> +            double discriminant = (Math.pow(b, 2)) - (4 * a * c);
Если дискриминант равен 0, то корень всего один. а у вас получается два -0.0 и 0.0

2025-01-04 19:33 UTC, quperino commented on src/main/java/com/walking/intensive/chapter1/task4/Task4.java
> +            double discriminant = (Math.pow(b, 2)) - (4 * a * c);
Исправил

2025-01-04 19:33 UTC, quperino commented on src/main/java/com/walking/intensive/chapter1/task4/Task4.java
> +            double discriminant = (Math.pow(b, 2)) - (4 * a * c);
Исправил

2025-01-06 17:04 UTC, PuccaGTS requested changes
Давайте поправим

2025-01-06 17:04 UTC, PuccaGTS commented on src/main/java/com/walking/intensive/chapter1/task4/Task4.java
> +        } else if (b * b == 4 * a * c) {
Теперь под это условие попадает случай, который мы с Вами рассматривали в самом начале, когда передаем 0, 0, -10. Ждали Количество решений: 0., а получили Количество решений: 1. Корень: Infinity

2025-01-06 17:04 UTC, PuccaGTS commented on src/main/java/com/walking/intensive/chapter1/task4/Task4.java
> +            s = "Количество решений: 1. Корень: " + (-c / b);
Не всегда всегда дискриминант равный нулю значит, что это не квадратное уравнение и нужно корни считать только использую линейную функцию, например:
```
x^2 - 2x + 1 = 0
x^2 - 10x + 25 = 0
```
и т.д.

2025-01-06 17:04 UTC, PuccaGTS commented on src/main/java/com/walking/intensive/chapter1/task4/Task4.java
> +            s = "Количество решений: 1. Корень: " + (-c / b);
Плюс сюда же кейс x^2 = 0;
Ожидаем: Количество решений: 1. Корень: 0.0
Получаем: Количество решений: 1. Корень: NaN - т.к. делим 0 на 0

2025-01-06 17:04 UTC, PuccaGTS commented on src/main/java/com/walking/intensive/chapter1/task4/Task4.java
> +        } else if (b * b == 4 * a * c) {
А сюда не попал кейс, когда это линейное уравнение и нужно считать так, как Вы написали, но из-за того, что условие неправильно написано, случай не обрабатывается, пример:
```
Правильное решение:
0x^2 - 2x +8 = 0
-2x + 8 = 0
x = 4.0

Ваше решение:
if (4 == 4 * 0 * 8 = 0) false
и идем дальше в блок else, чтобы считать два корня
```
В итоге ожидаем:
Количество решений: 1. Корень: 4.0
Получаем:
Количество решений: 2. Корни: NaN;Infinity

2025-01-10 06:43 UTC, PuccaGTS requested changes
Давайте попробуем оптимизировать Ваше решение, сейчас условные блоки выглядят очень громоздко и сложно понять, какое условие работает, предлагаю пойти таким путем:
1. Сперва посмотреть на коэффициенты и сделать вывод, если это возможно.
2. Если ответа в первом пункте не было, то посчитать дискриминант и сделать вывод на основе дискриминанта, важно - дискриминант лучше всего посчитать один раз, а потом переиспользовать, чтобы избежать повторения кода, как у Вас:
`b * b == 4 * a * c`
`b * b - 4 * a * c`
Вы, по-сути, вычисляете одно и то же, но можно это сделать один раз и потом переиспользовать.

Ещё можно воспользоваться структурой switch case для множественного выбора, чтобы избежать большого количества if-else if- else if, так код будет чище.

Вы молодец, осталось совсем немного:)

2025-01-10 06:43 UTC, PuccaGTS commented on src/main/java/com/walking/intensive/chapter1/task4/Task4.java
> +        } else if (a > 0 && c < 0 || a < 0 && c > 0) {
Под это условие попало уравнение:
`x^2 + 4x - 45 = 0` - валидное уравнение, которое имеет корни -9.0 и 5.0
Ваша программа выдает NaN;NaN, т.к. вычисляет корень из отрицательного числа

2025-01-10 06:43 UTC, PuccaGTS commented on src/main/java/com/walking/intensive/chapter1/task4/Task4.java
> +        } else if (a > 0 && c < 0 || a < 0 && c > 0) {
Есть и другие примеры, похожие, которые также попадают в это условие

2025-01-11 19:32 UTC, quperino commented on src/main/java/com/walking/intensive/chapter1/task4/Task4.java
> +        } else if (a > 0 && c < 0 || a < 0 && c > 0) {
Добавил уточняющее условие && b == 0 два раза. Также убрал из верхних конструкций проверку на значение дискриминанта, вынес его в последнее условие. Switch case не воспользовался, так как пока что не совсем понял, как в нем можно будет реализовать конструкцию, подобной той, которую я написал через if-else

2025-01-14 08:48 UTC, PuccaGTS approved these changes

2025-01-14 08:48 UTC, closed without merging