Task5
KFalcon2022/intensive-tasks-2024 pull request #80
Opened 2024-11-17 22:35 UTC by ilya-baykalov

2024-11-18 13:31 UTC, PuccaGTS requested changes
Необходимо поправить

2024-11-18 13:31 UTC, PuccaGTS commented on src/main/java/com/walking/intensive/chapter1/task5/Task5.java
>      static double[] getBisectors(double a, double b, double c) {
Метод работает некорректно, попробуйте подставить значения, например, 3, 4, 5
Вы должны будете получить, что-то вроде: 2.424, 3.354, 4.216 (откинул некоторые знаки).
Ваш метод возвращает: 6.414, 9.486, 12.649 - где-то закралась ошибка.

2024-11-18 13:31 UTC, PuccaGTS commented on src/main/java/com/walking/intensive/chapter1/task5/Task5.java
>      static double[] getAngles(double a, double b, double c) {
Метод работает некорректно:
При входных данных 3, 4, 5 получаем [0.643, 0.927, 1.57] - явно это не углы в градусах)

2024-11-18 13:31 UTC, PuccaGTS commented on src/main/java/com/walking/intensive/chapter1/task5/Task5.java
>      static double getAreaAdvanced(double a, double b, double c) {
Что-то тоже не так с методов: для 3, 4, 5 площадь согласно методу равна 10.0, на на самом деле площадь равна 6.

2024-11-18 15:32 UTC, ilya-baykalov commented on src/main/java/com/walking/intensive/chapter1/task5/Task5.java
> +        double A = Math.asin(2*S/b/c);
`Math.asin(2 * S * с / b)` - это не то же самое, что `Math.asin(2 * S / b / c)`

А пробелы добавил, спасибо

2024-11-19 05:30 UTC, PuccaGTS commented on src/main/java/com/walking/intensive/chapter1/task5/Task5.java
> +        double A = Math.asin(2*S/b/c);
Вам виднее как это записать правильней)

2024-11-19 05:41 UTC, PuccaGTS approved these changes

2024-11-19 05:41 UTC, closed without merging