Task 1
KFalcon2022/intensive-tasks-2024 pull request #93
Opened 2024-11-18 08:49 UTC by gentrus

2024-11-18 09:22 UTC, ekolokolov requested changes
Не верно работает на значениях: 0, 11, 12, 13, 14, 111, 112, 113, 114.

2024-11-18 09:22 UTC, ekolokolov commented on src/main/java/com/walking/intensive/chapter1/task1/Task1.java
> +        if (age <= 0 || age > maxAge) {
Валидацию лучше ставить как можно раньше. Чтобы не выполнять ни каких вычислений если входные данные не корректны.

2024-11-21 15:02 UTC, gentrus commented on src/main/java/com/walking/intensive/chapter1/task1/Task1.java
> +        if (age <= 0 || age > maxAge) {
Исправил)

2024-11-21 15:56 UTC, gentrus commented
Исправил, спасибо)

2024-11-25 10:12 UTC, gentrus commented
Проверьте, пожалуйста)

2024-12-02 14:28 UTC, ekolokolov approved these changes
Зачтено

2024-12-02 14:28 UTC, closed without merging