Task 2
KFalcon2022/intensive-tasks-2024 pull request #97
Opened 2024-11-18 11:34 UTC by HellRus

2024-11-18 12:56 UTC, HellRus commented
Первое задание уже проверено и одобрено. 
Ошибочно создал этот бранч не из мастера и до мерджа первого задания, из-за чего оно тоже попало в пуш реквест.

2024-11-18 17:31 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter1/task2/Task2.java
> +            return flatNumber + " кв - " + entranceNumber + " подъезд, " + floorNumber + " этаж, слева от лифта, влево";
длина строки кода не должна превышать 120 символов - считается, что именно столько попадает в один экран при стандартных настройках

2024-11-18 17:32 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter1/task2/Task2.java
> +        } else if (flatNumber - (floorAmount * 4 * entranceAmount) > 0) {
если у тебя выше return, зачем else if? Хватит обычного if, ведь если сработала предыдущая проверка - сюда программа уже точно не дойдет

2024-11-18 17:32 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter1/task2/Task2.java
> +        if (isLastFlatInEntrance) {
предлагаю познакомиться с тернарным оператором

2024-11-18 17:33 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter1/task2/Task2.java
> +        } else if (flatPositionOnFloor == 2) {
кажется, есть языковая конструкция, которая здесь подходит больше, чем if-else

2024-11-18 17:33 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter1/task2/Task2.java
> +            return flatNumber + " кв - " + entranceNumber + " подъезд, " + floorNumber + " этаж, справа от лифта, вправо";
Точно ли нужно в каждом блоке полностью собирать всю итоговую строку? Ведь сами условия определяют только часть итоговой строки, а не всю ее целиком

2024-11-18 17:34 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter1/task2/Task2.java
>  }
Неплохое решения, но код можно сделать лаконичнее и более читабельным, если поправить замечания выше. Маякни в ЛС, когда подольешь правки. https://t.me/ironicMotherfucker

2024-11-19 19:44 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter1/task2/Task2.java
> +        boolean isLastFlatInEntrance = (flatNumber % flatAmountSingleEntrance) == 0;
лишние скобки

2024-11-19 19:49 UTC, KFalcon2022 requested changes

2024-11-19 19:49 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter1/task2/Task2.java
> +                (flatNumber / flatAmountSingleEntrance) : (flatNumber / flatAmountSingleEntrance) + 1;
не самое удачное оформление для тернарки. Придумать можно по-разному, главное, чтобы ее было легко читать, не путаясь, где какой- выражение. Мне, например, такой вид нравится:
```java
int entranceNumber = isLastFlatInEntrance
    ? flatNumber / flatAmountSingleEntrance
    : flatNumber / flatAmountSingleEntrance + 1;
```

И не части с избыточными скобками. Как говорила моя препод по программированию: лишние скобки - это как лишние гондоны. Оно, конечно, надежней, но ощущения не те

2024-11-19 19:49 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter1/task2/Task2.java
> +                (flatNumber / flatAmountSingleEntrance) : (flatNumber / flatAmountSingleEntrance) + 1;
И старайся смотреть на свой код, будто ты его еще и читаешь, а не только пишешь. Почти 10 строк напряженных математических вычислений без отступов могут выглядеть очень тяжеловесно:)

2024-11-19 19:49 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter1/task2/Task2.java
> +            default -> flatPositionOnFloor = " этаж, справа от лифта, вправо";
плохая затея. default - это именно поведение по умолчанию, а не замена оставшегося кейса. К слову, если уже используешь этот синтаксис - switch-case умеет возвращать значение:
```java
String flatPositionOnFloor = switch (flatNumberOnFloor) {
    case 1 -> flatPositionOnFloor = " этаж, слева от лифта, влево";
    case 2 -> flatPositionOnFloor = " этаж, слева от лифта, вправо";
...
};
```

И в такой нотации default уже не обязателен - если не сработает ни один из кейсов, произойдет ошибка выполнения

2024-11-19 20:03 UTC, HellRus commented on src/main/java/com/walking/intensive/chapter1/task2/Task2.java
> +                (flatNumber / flatAmountSingleEntrance) : (flatNumber / flatAmountSingleEntrance) + 1;
так действительно читабельнее, спасибо

2024-11-20 17:51 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter1/task2/Task2.java
>  }
Задача зачтена

2024-11-20 17:51 UTC, KFalcon2022 approved these changes

2024-11-20 17:51 UTC, closed without merging