Task1
KFalcon2022/intensive-tasks-2024 pull request #98
Opened 2024-11-18 11:44 UTC by sauza7

2024-11-18 17:39 UTC, KFalcon2022 requested changes

2024-11-18 17:39 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter1/task1/Task1.java
> +        if (age < 0 || age > 127) return "Некорректный ввод";
тело if всегда должно быть заключено в {}. И откуда ограничение на 127 лет?

2024-11-18 17:39 UTC, KFalcon2022 commented on src/main/java/com/walking/intensive/chapter1/task1/Task1.java
> +            if (age % 10 == 1) {
Кажется, age % 10 можно вынести в переменную - зачем считать это значение в каждом условии?

2024-11-19 09:05 UTC, sauza7 commented
Поправил.

2024-11-21 19:42 UTC, KFalcon2022 approved these changes

2024-11-21 19:42 UTC, closed without merging